### ISSUE TITLE
ShopifyAPI::CustomerAddress.all always returns an empty array

### ISSUE THREAD

**Issue by kaarelss** [Shopify/shopify_api#1018]
# Issue summary

ShopifyAPI::CustomerAddress.all always returns an empty array.

## Expected behavior

It should return an array of CustomerAddress objects

## Actual behavior

This happens because create_instance_from_response method is unable to create instances if normalized resource class name is different than parent attribute in API response. It tries to find normalized class_name inside response body, but it could not find it because response from API contains parent attribute `addresses` instead of `customer_addresses`. So the resource class should be named `ShopifyAPI::Addresses` or API response should contain `customer_addresses` as parent attribute.  This is same issue just with different resource - https://github.com/Shopify/shopify-api-ruby/issues/992

So this results as no objects created and returned an empty array.

```
def create_instances_from_response(response:, session:)
  objects = []

  body = T.cast(response.body, T::Hash[String, T.untyped])

  if body.key?(class_name.pluralize) || (body.key?(class_name) && body[class_name].is_a?(Array))
    (body[class_name.pluralize] || body[class_name]).each do |entry|
      objects << create_instance(data: entry, session: session)
    end
  elsif body.key?(class_name)
    objects << create_instance(data: body[class_name], session: session)
  end

  objects
end
```

## Steps to reproduce the problem

1. Create Customer with addresses
2. Find addresses for that customer with - `ShopifyAPI::CustomerAddress.all(customer_id: customer_id)`

## Specifications
- `shopify_api` version: 11.1.0
- Shopify API version used (example: `2022-04`):

@itissible/matrixify

**Comment by jagthedrummer** [comment]
Not stale.
