### ISSUE TITLE
invalid webhook HMAC

### ISSUE THREAD

**Issue by Vicapelli** [Shopify/shopify_api#1047]
# Getting "invalid webhook hmac" error

When webhook event "orders/create" calls the "route_webhook" method to process the request and validate hmac, this error is being returned and this only happens in prod env.

## Expected behavior

As long as i know the webhook event request contains the hmac value and the context setup has its api_secret_key value as well. So i don't know why this error is happening. It should be working fine.

**Comment by Halvanhelv** [comment]
I have the same problem
