### ISSUE TITLE
ActionView::Template::Error: Return value: Expected type T.nilable(T.any(Float, Integer, String)), got type TrueClass

### ISSUE THREAD

**Issue by jaimina-hulkapps** [Shopify/shopify_api#1079]
# Issue summary
On accessing Object.value of boolean metafields we are getting https://d.pr/i/TGyM8r 

## Specifications
- `shopify_api` version: 12.2.1
- Shopify API version used (example: `2022-10`):
```[tasklist]

```

**Comment by mrpunkin** [comment]
We are also having this issue. Is there any plan to fix this?
