### ISSUE TITLE
Whatever happened to the nice old GQL client?

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_api#1083]
Old code was nice, for example, in a background job. 

Get the shop_domain in a perform_later argument, and use it to find the shop and then use the Rails App convenience method with_shopify_session: 

    shop.with_shopify_session 
       query = Shopify::Queries::GetProductByHandle
       result = ShopifyAPI::GraphQL.client.query(query, variables: {handle: "memememe})
    end

So those halcyon days are over? Now with the improved? API we have this new call structure where we have to initiate a session manually, and then use the client we get using that session to get data and run queries. 

Long-winded new approach:

    session = ShopifyAPI::Auth::Session.new(
      shop: shop.shopify_domain,
      access_token: shop.shopify_token
    )
    client = ShopifyAPI::Clients::Graphql::Admin.new(
     session: session
    )
    query = Shopify::Queries::GET_SHOP_NAME
    results = client.query(query: query)

So as a Feature Request, can we get back our old convenience of issuing GQL queries in the with_shopify_session method initiated on the shop? Or at least, can you point me to a shortcut for the long-winded approach?

**Comment by emcmanus** [comment]
If you're on `shopify_app` HEAD you can:

```rb
shop.with_shopify_session do |session|
  client = ShopifyAPI::Clients::Graphql::Admin.new session: session
  # ...
end
```

Thanks to https://github.com/Shopify/shopify_app/pull/1488 (and maybe this issue?)

**Comment by sshaw** [comment]
For a saner GraphQL API client see [`ShopifyAPI::GraphQL::Tiny`](https://github.com/ScreenStaring/shopify_api-graphql-tiny)

And, for a slightly higher level wrapper see [`ShopifyAPI::GraphQL::Request`](https://github.com/ScreenStaring/shopify_api-graphql-request)

**Comment by resistorsoftware** [comment]
Keeping the home fires burning! Cool. Good for you! Like it.
