### ISSUE TITLE
Order.subtotal_price object type Error - Expected type T.nilable(Float)

### ISSUE THREAD

**Issue by assoumemba** [Shopify/shopify_api#1095]
# Issue summary

Return value: Expected type T.nilable(Float), got type String with value "40.00"
Completed 500 Internal Server Error in 47758ms (ActiveRecord: 103.2ms)

- `shopify_api` version: 12.3.0
- Ruby version: 2.6.3
- Operating system: Mac OS

```
Completed 500 Internal Server Error in 118074ms (ActiveRecord: 24.5ms)
  
TypeError (Return value: Expected type T.nilable(Float), got type String with value "40.00"
Caller: /app/shopify_services/shopify_order_item.rb:68
Definition: /.rvm/gems/ruby-2.6.3/gems/shopify_api-12.3.0/lib/shopify_api/rest/resources/2022_07/order.rb:231):
  

## Expected behavior

<!-- What do you think should happen? -->

 attr_reader :source_name
    sig { returns(T.nilable(String)) }
    attr_reader :source_url
     **sig { returns(T.nilable(String)) }**
    **attr_reader :subtotal_price**
    sig { returns(T.nilable(T::Hash[T.untyped, T.untyped])) }
    attr_reader :subtotal_price_set
    sig { returns(T.nilable(String)) }
    attr_reader :tags
    sig { returns(T.nilable(T::Array[T::Hash[T.untyped, T.untyped]])) }
    attr_reader :tax_lines
    sig { returns(T.nilable(T::Boolean)) }

## Actual behavior

<!-- What actually happens? -->

 attr_reader :source_name
    sig { returns(T.nilable(String)) }
    attr_reader :source_url
    **sig { returns(T.nilable(Float)) }**
    **attr_reader :subtotal_price**
    sig { returns(T.nilable(T::Hash[T.untyped, T.untyped])) }
    attr_reader :subtotal_price_set
    sig { returns(T.nilable(String)) }
    attr_reader :tags
    sig { returns(T.nilable(T::Array[T::Hash[T.untyped, T.untyped]])) }
    attr_reader :tax_lines
    sig { returns(T.nilable(T::Boolean)) }

## Steps to reproduce the problem

Api version: 2022-07
1-   orders = ShopifyAPI::Order.all
2-  orders.each do |order|
    ---
         amount = order.subtotal_price
   ---
      end

**Comment by g3ortega** [comment]
I'm having the same issue with `12.4`, API version: `2022-7`.

`TypeError: Return value: Expected type T.nilable(Float), got type String with value "xx.xx"`

**Comment by Fladdermuz** [comment]
@assoumemba I am also having the same issue.

**Comment by nelsonwittwer** [comment]
Thanks for your patience with this! I've track down the root problem and we are working on a fix! Unfortunately, the problem seems to be a type misunderstanding upstream with our API at Shopify so I'm not in complete control of the fix. I see this root issue affecting several other issues within our REST resources here which is a bummer :( 

As a workaround, you could use the [rest client directly](https://github.com/Shopify/shopify-api-ruby/blob/main/lib/shopify_api/clients/rest/admin.rb) directly, though you'll have to parse the response accordingly.

**Comment by nelsonwittwer** [comment]
Fixed with https://github.com/Shopify/shopify-api-ruby/pull/1137
