### ISSUE TITLE
Wrong type definition for the profile_id attribute of the ShippingZone REST resource

### ISSUE THREAD

**Issue by dhalai** [Shopify/shopify_api#1100]
# Issue summary

Starting from the `shopify-api-ruby` 10.0.0 if the REST API is used there is no way to get a `profile_id` attribute related to the particular ShippingZone resource.

- `shopify_api` version: 10.0.0 and up

## Expected behavior

The `profile_id` attribute of the ShippingZone REST resource should return a string (e.g. `gid://shopify/DeliveryProfile/<profile_id>`) or nil if there are no related profile.

It should work for all API versions. 

## Actual behavior

It returns the TypeError Exception

## Steps to reproduce the problem

1. Get an existing ShippingZone by using REST API
2. Try to access its `profile_id`

**Comment by nelsonwittwer** [comment]
Fixed with https://github.com/Shopify/shopify-api-ruby/pull/1137
