### ISSUE TITLE
response body is nil

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_api#116]
Hi,

Another fun one for the Net::HTTP crowd. Been seeing sporadic issues from this code in session.rb:

```
response = access_token_request(code)
if response.code == "200"
  token = JSON.parse(response.body)['access_token']
else
  raise RuntimeError, response.msg
end
```

The response.code method exists and is 200, but the response body is nil. Is there a better way to handle the underlying reason no body would be returned? It is likely the token at fault but it seems handling this is awkward as there is no mention of the source of the troubles.

**Comment by 0ptimusrhyme** [comment]
Closing for now - if somehow this issue is still occurring feel free to say so here with more information.

**Comment by resistorsoftware** [comment]
Shopify. On the Ball. Closing issues from 2014 like there is no tomorrow.
