### ISSUE TITLE
Delete all metafields for a product

### ISSUE THREAD

**Issue by SebastianSzturo** [Shopify/shopify_api#122]
There is an very easy way to delete all images of an product:

``` ruby
product = ShopifyAPI::Product.find("...")
product.images = []
product.save
```

But because the metafield object doesn't seam to be a real child object of product, I can't clear the metafields in the same way. 
Is there an easy way to clear all metafields of my product?

**Comment by af6140** [comment]
This is really not optimal to not be able to delete multiple/all metafields in one api call, potentially can save a lot of network calls.
