### ISSUE TITLE
shipping_address; Required parameter missing or invalid

### ISSUE THREAD

**Issue by skillmatic-co** [Shopify/shopify_api#1270]
Hello, I'm having a new issue recently where anytime I try to save an order, I'm getting `shipping_address; Required parameter missing or invalid` even though the order does not require shipping. Did something recently change here? I haven't changed any of my codebase. If it helps in Sentry it's saying this issue started 10 days ago on January 16.

I can grab any order (that does not require shipping) like this:

```
shopify_order = ShopifyAPI::Order.find(1234567890)
```

And try to update something on that order, like a note for example:

```
shopify_order.note_attributes << ShopifyAPI::NoteAttribute.new(
  name: 'some_name',
  value: "some_value"
)
```

And when I run:

```
shopify_order.save
```

I get:

```
shipping_address; Required parameter missing or invalid
```

Again, nothing in my codebase has changed. This just started happening within the last week or so.

I've tried these things, they do not work:

```
shopify_order.shipping_address = nil
shopify_order.shipping_address = {}
shopify_order.shipping_address = {
  first_name: nil,
  last_name: nil,
  address1: nil,
  city: nil,					
  province_code: nil,
  zip: nil,
  country_code: nil,
  phone: nil	
}
shopify_order.shipping_address = ShopifyAPI::ShippingAddress.new(
  first_name: nil,
  last_name: nil,
  address1: nil,
  city: nil,					
  province_code: nil,
  zip: nil,
  country_code: nil,
  phone: nil	
)

```

**What changed and how to update an order that does not require a shipping address?**

Relevant forum post here: https://community.shopify.com/c/customers-discounts-and-orders/error-updating-order-without-a-shipping-address/td-p/2161598

**Comment by skillmatic-co** [comment]
The **_hack_** I've have to implement since this massive bug started randomly wreaking havoc in my app, is doing this:

```
shopify_order.shipping_address = shopify_order.billing_address
shopify_order.save
```

I would love to get a response from Shopify on why all of a sudden the shipping address is required to save an order, even for orders that do not require shipping.

**Comment by skillmatic-co** [comment]
You can see here that shipping_address is not required to update an order:

https://shopify.dev/docs/api/admin-rest/2023-10/resources/order#put-orders-order-id

**Comment by skillmatic-co** [comment]
Hi @matteodepalo,

I don't even have to update anything for this to happen.

I can just grab any order that does not have a shipping address:

```
shopify_order = ShopifyAPI::Order.find(1234567890)
shopify_order.save
```

And I get `shipping_address; Required parameter missing or invalid`

**Comment by skillmatic-co** [comment]
> @skillmatic-co I see. Could you share the X-Request-ID from the response so we can track this down? This doesn't seem to be an issue with the ruby client as I've seen other reports coming from different sources.

Where do I find the X-Request-ID? No errors are actually being store/returned in `shopify_order` when this error happens.

For example:

```
> shopify_order = ShopifyAPI::Order.find(1234567890)
> shopify_order.save
Traceback (most recent call last):
        1: from (irb):16
ActiveResource::BadRequest (Failed.  Response code = 400.  Response message = Bad Request (shipping_address; Required parameter missing or invalid).)
> shopify_order.errors.count
=> 0
> shopify_order.errors.messages
=> {}
```

**Comment by matteodepalo** [comment]
It seems from the various reports that this is not an issue with our tooling but it's an issue with the API itself, so unfortunately we can't help you here, you'd need to contact [Shopify Partner Support](https://help.shopify.com/en/support/partners/login) to get help debugging those requests.
