### ISSUE TITLE
Listing a Collection of Orders doesn't include each orders transactions

### ISSUE THREAD

**Issue by SunnyIzr** [Shopify/shopify_api#144]
Hello:

Not sure if this is an issue as much as it's just a general question. I'm a fairly newbie dev, and had a quick question on when pulling a collection of order objects via the ruby gem. I noticed that when listing all the orders in the collection, each order's respective transactions are not listed along with it, instead you'd have to make an additional API Call for every single order in the collection to obtain that information. 
Whereas on the Shopify's API Docs, i noticed that when you request a list of all Orders "GET /admin/orders.json", they actually do list the transactions of every order in the collection. Was there a specific reason why this was eliminated from the gem's retrievals?

Let me know.

-Sunny

**Comment by carouselle** [comment]
I had the same question.  Can you tell me what the syntax would be to access a transaction?

Thanks!
D
