### ISSUE TITLE
product.image errors (when image is null)

### ISSUE THREAD

**Issue by joncalhoun** [Shopify/shopify_api#156]
When dealing with a Shopify product, you can occasionally run into a product with no image. What I would expect this to do is something like:

``` ruby
product.image # null
```

Instead an undefined method error is raised, so I have to wrap code in `if product.respond_to?(:image) ... end` which is rather obnoxious.

**Comment by dotnetwise** [comment]
so?

**Comment by kevinhughes27** [comment]
This is likely very deep in how activeresource functions. The solution above is what I would advise or use a `try(..)` if you are on Rails 4. If you can provide a specific use case that would benefit from including the try portion of the code in this lib then we'd certainly consider it
