### ISSUE TITLE
Shopify Threadsafe ActiveResource branch does not work for 3.2.18

### ISSUE THREAD

**Issue by sealabcore** [Shopify/shopify_api#157]

**Comment by anark** [comment]
+1

**Comment by peterjm** [comment]
This should be fixed now

**Comment by toriscallan** [comment]
It does not work for rails version 3.2.21.

It appears that the only supported versions are Rails 4.0 and 4.2 (based on this).
https://github.com/Shopify/activeresource/tags

```
 |16:49:19| ts+jh |master ✓| → bundle
Updating git://github.com/Shopify/activeresource
Fetching source index from https://gems.contribsys.com/
Fetching source index from https://rubygems.org/
Resolving dependencies...
Could not find gem 'activeresource (= 3.2.21) ruby', which is required by gem 'rails (= 3.2.21) ruby', in any of the sources.
```

We tried 

```
gem 'activeresource', git: 'git://github.com/Shopify/activeresource', tag: '4.0-threadsafe'
```

and

```
gem 'activeresource', git: 'git://github.com/Shopify/activeresource', tag: '4.2-threadsafe'
```

and 

```
gem 'activeresource', git: 'git://github.com/Shopify/activeresource'
```

Can we reopen this for discussion? Are you stil haveing the issue @sealabcore? Do you have any proposed solutions? 

– @toriscallan & @hjhart

**Comment by sealabcore** [comment]
@toriscallan & @hjhart I just wrote my own threadsafe gem. Since, I just piecemeal-ed what I needed from the API specifically for our app I haven't released it on rubygems or github.

**Comment by toriscallan** [comment]
We saw that as a potential solution to our problem as well. Would you be willing to share on github?

– @hjhart & @toriscallan

**Comment by sealabcore** [comment]
@toriscallan & @hjhart I would but it's just in my lib folder and I don't have time right now to extract it into it's own gem. Sorry guys!

**Comment by hjhart** [comment]
Can we please re open this ticket? The issue still exists for everyone who is not using Rails 4 and Rails 4.2.

**Comment by csaunders** [comment]
How far back should we support this? I believe there's some residual code kicking around in the shopify/activeresource project that is 3.2 compatible, we might just need to tag it.

**Comment by hjhart** [comment]
I'm not sure who in particular you are asking @csaunders, but I think 3.2 support would be good enough for the majority of applications still in use today.
