### ISSUE TITLE
When Inventory is not available, Shopify API raises a 500 error with no error message visible

### ISSUE THREAD

**Issue by hjhart** [Shopify/shopify_api#167]
```
shopify_order = ShopifyAPI::Order.new
shopify_order.line_items = [{ variant_id: 123, quantity: 1 }]
shopify_order.blah = blah blah blah
ShopifyAPI::Session.temp("shop_name.myshopify.com", 'asdfasdfadf') { shopify_order.save }
```

in some cases, returns to us a `ActiveResource::ServerError: Failed.  Response code = 500.  Response message = Internal Server Error.` error.

Unfortunately, when we look at shopify_order.errors.messages we see an empty hash. 

Similarly, when a zip code is invalid the shopify api will not be persisted, not raise an error, and populate the shopify_order.errors.messages.

This is not consistent behavior.

We had to track down the error message in `shopify_api-3.2.1/lib/active_resource/connection_ext.rb` where we `puts` out the response.body and received this.

```
{"errors":"Inventory not available; Asked for {916977441=\u003E1}, got {916977441=\u003E0}"}
```

Anyone willing to take a look at this with us?

**Comment by hjhart** [comment]
Ping!

**Comment by hjhart** [comment]
Would anyone at Shopify accept a PR if we worked on one? This continues to be an issue for us.

**Comment by pickle27** [comment]
We definitely accept PRs to this repo!

**Comment by justinstern** [comment]
This would be an awesome update to have.  

Here's another case where this bit me, which I've opened a post on [the api forums about](https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/422-unprocessable-entity-when-updating-existing-orders-261297) as there seems to be an issue with update existing order resources that have a validation error.  

Basically, the thrown exception is `ActiveResource::ResourceInvalid: Failed` meanwhile if you log the underlying response, it's a `422 Unprocessable Entity {"errors":{"shipping_address":["last name can't be blank"]}}`

**Comment by awd** [comment]
Hey folks, we recently shipped a fix which ensures this request responds with 422 instead of 500. 500s are nasty. Better error messages would definitely be considered. Let me know your ideas and I'll see what we can get implemented here.
