### ISSUE TITLE
shopify gem install with activesource(threadsafe) version fails through capistrano

### ISSUE THREAD

**Issue by coolgandhi** [Shopify/shopify_api#169]
Hello,

I am trying to install the shopify with threadsafe activeresource in aws using capistrano:

My gem file:
gem 'activeresource', git: 'git://github.com/Shopify/activeresource', branch: 'threadsafe'
gem 'shopify_api', '>= 3.2.5'

Command in capistrano which fails:
bundle exec gem install --file Gemfile 

Error message:
ERROR:  While executing gem ... (Gem::DependencyError)
DEBUG [1f077ac1] 	    Unresolved dependency found during sorting - activeresource (>= 3.0.0) (requested by shopify_api-3.2.6)

This seems to be a problem with the gem dependency ascertaining script as if I remove the threadsafe in gem file, the capistrano deployment passes.  gemfile.lock is:
activeresource (4.0.0.threadsafe) and probably fails in the check.

Wondering if anyone else has seen this error and if there is a workaround for this?

Thanks for your input.

Best,
Sachin

**Comment by justinstern** [comment]
@coolgandhi Sounds like it could be similar to my issue trying to upgrade to Rails 4.2 recently which I posted about on the Shopify API forum here: https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/recommended-library-for-multithreaded-ruby-environment-followup-224760  There's also a link to the original threadsafe discussion (fairly lengthy) there if you're curious.  Hoping that @peterjm finds it in his heart to update his awesome activeresource threadsafe branch to the latest, and even better, that the rails team actually merges!

Can you confirm whether you're using Rails 4.2 or 4.1?  If 4.2, try with 4.1 if you need the threadsafe version and see whether you have better luck with that

**Comment by peterjm** [comment]
/cc @jamesmacaulay @csaunders 

Thanks for opening the issue. I'll try to take a look sometime this month.

**Comment by justinstern** [comment]
also, possibly related to #157 ?  There's not much detail over there though

**Comment by coolgandhi** [comment]
Thanks @justinstern and @peterjm for quick replies.

I have a workaround for now in the capistrano script. This was barfing at me on Rails 4.1 as well.

There is a RubyGems issue as well which may or may not be related: https://github.com/rubygems/rubygems/issues/1062

However, I can confirm that removing threadsafe version from Gemfile, the dependency error doesn't happen.

Look forward to the threadsafe version integrated in activeresource.

**Comment by peterjm** [comment]
We now have a tag on the activeresource fork that works with Rails 4.2 -- see https://github.com/Shopify/activeresource/releases/tag/4.2-threadsafe

We've updated some of our internal apps to Rails 4.2 using the new version, and it's working well for us.
