### ISSUE TITLE
Setting up app/uninstalled webhook

### ISSUE THREAD

**Issue by shabbirun** [Shopify/shopify_api#174]
Hello - I'm fairly new to Rails and am playing around with building a Shopify app. I'd like to create a webhook for "app/uninstalled" but I'm not sure where exactly to execute the code. My guess would be somewhere in the installation process - but how can I make sure it's only called once and not again? And where is the best place to execute the ShopifyAPI::Webhook.create code? Thanks!

**Comment by kevinhughes27** [comment]
Hi there - this repo is for code issues and features etc. You'll have more luck getting your question answered if you post it on our forum: https://ecommerce.shopify.com/c/shopify-apis-and-technology
