### ISSUE TITLE
ShopifyAPI::Order.save fails due to sending source_name attribute

### ISSUE THREAD

**Issue by mrpunkin** [Shopify/shopify_api#176]
Per the changes outlined [here](https://ecommerce.shopify.com/c/api-announcements/t/order-source-deprecation-notice-upcoming-source_name-restrictions-aug-1st-2014-204378), a recent update to the Shopify API seems to prevent saving existing records when submitting source_name with the attributes (as ActiveResource does), regardless of if it has been changed or not. Others encountering errors as seen [here](https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/422-unprocessable-entity-when-updating-existing-order-resource-257259?utm_campaign=ecomu&utm_medium=email&utm_source=subscription#comment-257469)

```
PUT https://xxx.myshopify.com:443/admin/orders/nnn.json
--> 422 Unprocessable Entity 89 (192.0ms)
Response:
{"errors":{"source_name":["is only assignable during creation and may not be changed."]}}
```

**Comment by kevinhughes27** [comment]
@costford ^

**Comment by costford** [comment]
Yup I looked into this two days ago. Fix is here: https://github.com/Shopify/shopify/pull/41244

**Comment by justinstern** [comment]
@costford sweet, is there an ETA on this being rolled out?  or should we look to temporarily implement [MrPunkin's fix](https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/422-unprocessable-entity-when-updating-existing-order-resource-257259#comment-257471)

**Comment by costford** [comment]
:shrug: It looks like they're shipping it when it passes CI. You can follow the PR or ping the dudes on it, but I'm gonna guess today.

**Comment by justinstern** [comment]
awesome, thanks, looks like Shayne already updated the forum post saying this is likely coming today

**Comment by Krystosterone** [comment]
@justinstern I'm waiting for :tophat: on https://github.com/Shopify/shopify/pull/41244 and I'll ship it!

**Comment by mrpunkin** [comment]
Sounds like this has been fixed on Shopify's end, according to the forum update by Shayne. I removed my filter on my decorator and tested a save with no issues.

**Comment by costford** [comment]
Cool, thanks for testing!
