### ISSUE TITLE
Thor dependency problem

### ISSUE THREAD

**Issue by aomra015** [Shopify/shopify_api#179]
Because I'm running `foreman` in my app (which requires `thor` 0.19.1) I can't use `shopify_api` versions after this commit: https://github.com/Shopify/shopify_api/commit/a56318ab185f1f9a8b323da97ecd16bfb0436b26

So versions > **3.2.1** give the following error:

```
Bundler could not find compatible versions for gem "thor":
  In Gemfile:
    shopify_api (~> 3.2.7) ruby depends on
      thor (~> 0.18.1) ruby

    foreman (~> 0.78.0) ruby depends on
      thor (0.19.1)
```

Using `gem 'shopify_api', '~> 3.2.0'` in my gemfile loads **3.2.1** instead of the latest version because of this issue. 

Anyone deploying a Shopify app to Heroku will run into this issue.

**Comment by csaunders** [comment]
Version 4.0.0 will completely removes the `thor` dependency from the project. If you upgrade to that this should be resolved.
