### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by DannyBen** [Shopify/shopify_api#181]
Is there a page I missed, or other way to figure out which methods are supported by this library? I mean other than the useful but incomplete Examples page.

The full API documentation ( [example](https://docs.shopify.com/api/metafield) ) is nice and easy, but using this library without documentation makes it harder to work with.

It would be nice to either have a complete documentation, or perhaps, an easier task would be to let this library have simple `ShopifyApi::get(url, params)` and `ShopifyApi::post(url, params)` methods? In this case the "standard" API documentation will suffice (of course, the get ans post will only receive partial path to the resource, and will take care of authentication, as the current methods do).

Any tip or pointer in the right direction would be appreciated.

**Comment by csaunders** [comment]
All the resources are in the resources directory.

  - https://github.com/Shopify/shopify_api/tree/master/lib/shopify_api/resources

shopify_api is still using ActiveResource, [so those docs](https://github.com/rails/activeresource) are probably the best way to figure out how to use this library.

There's also the [getting started section](https://github.com/Shopify/shopify_api#getting-started) of the readme which should give you an idea of how to authenticate and use a resource.

**Comment by DannyBen** [comment]
Thanks. I was able to do exactly what I wanted with the API, but just because my tasks appeared somewhere in the examples.
