### ISSUE TITLE
Request: ability to filter on barcode/SKU with the /admin/variants.json endpoint 

### ISSUE THREAD

**Issue by dylanblanchard** [Shopify/shopify_api#183]
From an app partner: https://apps.shopify.com/simplesync
https://twitter.com/hsl/status/591055752162373633

> For my app SimpleSync I need to check for each order if there are any other products/variants with the same SKU in the shop. Right now I loop through all products I get from the 'admin/products.json' endpoint. For each product I loop through all the variants to check for matching SKU’s. This works very well for shops that are not too big, but recently some big stores installed my app and I’m seeing big delays of literally minutes if shops have thousands of products.
> 
> So I was digging in the API and found out that I could also use the '/admin/variants.json' endpoint to get all variants (actually slightly slower then looping through the products and variants) but it would awesome if I could just get all variants than only have a certain SKU or barcode. This is not something thats possible right now, but it would be a very helpful addition to the API. Do you have any idea whats the best way to send a feature request like this?

---

From @csaunders 

[scrubbed]

Something to think about, perhaps?
@Shopify/api

**Comment by hsleewis** [comment]
Yes! This was my request :-)

@csaunders for filtering on SKU's a lot af data won't be a big problem as it's not likely that there are a lot of variants with the same SKU, but that could be limited to a max of 250 items like the current admin/products endpoint.

**Comment by marisveide** [comment]
Hi, guys!

Is there any movement in this direction to have the ability to search by SKU?
Really, really need this too...

**Comment by IanFergusonZR** [comment]
I know there are a ton of posts out there already wanting/demanding this but it seems like it should at least be possible to provide the functionality for a lookup against your tables/variant data that have this sku information?  I understand sku is not necessarily guaranteed or enforced in the admin to be a unique field but not sure what the harm or limitation is on providing a lookup by sku and return a list of matching variants by sku? adding a max result limit as suggested above

thanks

**Comment by jamiemtdwyer** [comment]
Sorry, but this isn't the correct place for feature requests.

The Shopify API wrapper library is a totally separate entity from the Shopify API itself. We cannot add features to this gem that are not supported in the official Shopify API.

I suggest posting in the [Shopify API forums](https://ecommerce.shopify.com/c/shopify-apis-and-technology) for any conversations related to feature requests in the API itself.

**Comment by IanFergusonZR** [comment]
yes totally understandable, however, I think some of the confusion results from the forums themselves

it does appear to be 'supported' but undocumented in
https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/api-product-variant-search-183152

I do understand not supporting something that is technically not documented, anyways thanks for clarifying
