### ISSUE TITLE
Variant weight is not saving

### ISSUE THREAD

**Issue by SebastianSzturo** [Shopify/shopify_api#191]
Since 2 weeks ago the grams attributes of variants are not saving anymore. 
No Error response from the server.

```Ruby
variant =  ShopifyAPI::Variant.find(123456)
variant.grams 
# => 1300

variant.grams = 1900
variant.grams 
# => 1900
variant.save

variant.grams
# => 1300
variant.errors.full_messages
# => []
```
Any idea what could be wrong?

**Comment by kristianpd** [comment]
@SebastianSzturo not sure if related or not but a few weeks ago I made an "innocent" change to `weight_unit` and `grams` in relation to some bulk editing work.

https://github.com/Shopify/shopify/pull/44536/files#diff-a115cc3729f1901bb9f846e53f120789R600

Just in case that may help you. I changed weight mind you, not `grams` AFAIK.

**Comment by ilikeorangutans** [comment]
Sorry for the late response. 

Variant holds the weight in two different places, both `grams` and `weight` (+`weight_unit`). If you retrieve a product and update only one of them, one might end up overwriting the other. In your case you can either update both fields or blank weight out.

**Comment by SebastianSzturo** [comment]
Thanks for your reply!

Thanks for the information. We changed our system to update just the weight now.
It would be great to have a public changelog or information about such changes. All our weights had to be updated manually for the past few weeks.

**Comment by ilikeorangutans** [comment]
We announce API changes over at [API Announcements](https://ecommerce.shopify.com/c/api-announcements), but looks like this slipped through the cracks.  :( Really sorry about that.
