### ISSUE TITLE
Recreating the products after deleting - not working

### ISSUE THREAD

**Issue by brahmadpk** [Shopify/shopify_api#193]
I am trying to create, delete and recreate products in my Shopify store using the API. Here is what I am doing:

Step 1: Create products in Shopify store using the API. Success.
Step 2: Delete some/all products from Shopify through Admin.

Step 3: Create deleted products in Shopify store using the API. Not saving.

Error: The variant '.....' already exists. Please change at least one option value. I am not sure why it is giving variant already exists for deleted products.

Any suggestions how to do this?

**Comment by kevinhughes27** [comment]
there is a lot going on with this issue description that could be on your side and nothing with the API itself. Products are often deleted in the background - are you sure they are deleted before you try and re-create them? How are you detecting which products to re-create.

If you could provide generic replication steps then we'll be able to help out. 

Also why do you need to create, delete and re-create in the first place?

**Comment by brahmadpk** [comment]
Hi @kevinhughes27 

Thanks for replying. Yes, it was an internal issue. Somehow the request to recreate the product was having the same variant data multiple times.

To answer your questions:

1. Why do you need to create, delete and re-create in the first place?
We are currently testing the app and hence creating, deleting, and recreating the products. The app is supposed to keep the Shopify store in sync with our internal product database. If you product is deleted on Shopify, the app must recreate it. Once in production, we may never need to recreate a product, but just covering all bases right now.

2. How are you detecting which products to re-create?
 We are querying ShopifyAPI::Product.find(product.id) and listening for ActiveResource::ResourceNotFound error to check if a product is no longer on the store.

Marking as closed.

**Comment by csaunders** [comment]
Why aren't you subscribing to webhooks and using those to find out when a product has been destroyed instead? For testing you can use ngrok, and if you get a paid account you can get a custom domain so it doesn't change on you each time you launch the application.
