### ISSUE TITLE
Detect threadsafe ActiveResource

### ISSUE THREAD

**Issue by peterjm** [Shopify/shopify_api#194]
@csaunders 

We're using the ["threadsafe" PRE value to detect the threadsafe version of ActiveResource](https://github.com/Shopify/shopify_api/blob/7af53e19a24d03e4c4486df7bf6ed99359a9f92d/lib/shopify_api/resources/base.rb#L30)

We'll need to update this to detect a new version of ActiveResource, after https://github.com/rails/activeresource/pull/167 ships

**Comment by gavinballard** [comment]
@peterjm Does this mean we can't flip projects using `shopify_api` over to using the `master` branch of `rails/activeresource` instead of using the Shopify fork tagged at `4.2-threadsafe`? We'll be bumping up to Rails 5 on a number of Shopify apps once it ships and it would be good to drop the dependency on the Shopify repo.

**Comment by peterjm** [comment]
@gavinballard I think the future of the threadsafety functionality in ActiveResource might by in doubt, given some issues like https://github.com/rails/activeresource/issues/178. @methodmissing has made some attempts to fix it in https://github.com/rails/activeresource/pull/202, though.

We can probably change `shopify_api` to stop using a "threadsafe" value for `PRE` and instead just check to see if the object responds to something like `threadsafe_attribute` -- checking against version strings is always problematic.

**Comment by gavinballard** [comment]
Thanks for the quick reply @peterjm!

I guess I'll keep an eye on Active Resource and this repository and see how things pan out. For now I'll stick to using the `4.2-threadsafe` branch.

**Comment by onpaws** [comment]
Hey @peterjm and friends!
Rails dev here. Have a client interested in using this gem on a greenfield Rails 5 app.
New to this issue and just trying to get up to speed on the latest and if I might be able to help.

Piecing together the story across various GH issues, it seems like ActiveResource historically doesn't play nice with threading.
I see that rails/activeresource#167 got merged on the upstream side.
Then over on [better_detection_of_threadsafe_activeresource](/Shopify/shopify_api/tree/better_detection_of_threadsafe_activeresource) I see we're now doing feature detection vs version number checking (awesome!).

What's left at this point? (checked the wiki -- apologies if this is answered somewhere already.)
Is there a Slack/etc I should be asking these questions on?

**Comment by peterjm** [comment]
@onpaws I think all that was necessary was to give me a reminder to finally ship that change. Hopefully you can use the 4.2.0 version of the shopify_api gem, and you'll be good to go with Rails 5

**Comment by onpaws** [comment]
Thanks @peterjm. Unfortunately seems like there's a piece still missing...feels like we're close on this!
Just posted a quick update on Shopify/shopify_api/pull/244
