### ISSUE TITLE
Fulfillment Endpoint and Tracking URL

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_api#195]
The docs show that one can provide a tracking URL and a tracking company when creating fulfillments. 

When I provide these attributes, along with tracking numbers, Shopify ignores the provided values for the URL and company, and instead uses pre-computed values. 

When I provide a company and tracking URL, and tracking numbers, I expect the provided data to override the Shopify defaults, not the other way around. 

Is there some explanation as to how to provide a correct tracking URL and company and have those values actually be used when creating fulfillments?

**Comment by kevinhughes27** [comment]
do you have any objects IDs that you tried this with? It might help with troubleshooting.

@silverstreaked can you have someone look into this please?

**Comment by resistorsoftware** [comment]
I received a confirmation that this is currently a known issue with Shopify and that the developers are looking into a fix. I can of course reproduce this at will, however I have to do that with the cooperation of a merchant. So it is a bit of a production.

    #<ShopifyAPI::Fulfillment:0x007feef28c1fc0 @attributes={"tracking_number"=>"RM391548631KR", "tracking_company"=>"TNT Post", "tracking_url"=>"https://www.17track.net/en/result/post-details.shtml?nums=RM391548631KR", "notify_customer"=>true, "id"=>785878596, "created_at"=>"2015-07-06T15:56:50+09:00", "service"=>"manual", "status"=>"success", "updated_at"=>"2015-07-06T15:56:50+09:00", "tracking_numbers"=>["RM391548631KR"], "tracking_urls"=>["https://www.17track.net/en/result/post-details.shtml?nums=RM391548631KR"], "receipt"=>#<ShopifyAPI::Receipt:0x007feef2830520 @attributes={}, @prefix_options={}, @persisted=true>,


Generates this tracking URL... no match there... 

    http://parcels-uk.tntpost.com/mytrackandtrace/trackandtrace.aspx?lang=en&I=true&P=&B=RM391548631KR

**Comment by kevinhughes27** [comment]
thanks for the update!

**Comment by resistorsoftware** [comment]
Hi, I am not getting paid for what I consider to be perfect code, due to this open bug in Shopify. It has now been 28 days since this was brought to Shopify attention with ZERO response. My client is not paying till this is fixed... can you PLEASE update me on this issue. Thanks!

**Comment by kevinhughes27** [comment]
@garethson can you look at this?

**Comment by garethson** [comment]
We have a fix for this in place, will update here when it's rolled out, hopefully later today.

**Comment by kevinhughes27** [comment]
thanks @garethson!!

**Comment by resistorsoftware** [comment]
Indeed, thank you very much for looking into this and fixing it. Korea sends their love I am sure!

**Comment by garethson** [comment]
This has been deployed. @resistorsoftware Thanks for your patience with us, please report back if this doesn't seem to have fixed the issue.
