### ISSUE TITLE
Get customers total count with a specific tag

### ISSUE THREAD

**Issue by avra911** [Shopify/shopify_api#201]
Hi,

This is probably not an issue as much as is FAQ.

I have not figured how to get total customers number having a specific tag, something like: ```ShopifyAPI::Customer.find(:all, :from => :search, :params => { :q => "tag:test" })```.count()? because it will always be limited to 250 items.

Is this even possible for the moment?

Best,
Razvan

**Comment by kevinhughes27** [comment]
try `ShopifyAPI::Customer.count(....)`

**Comment by avra911** [comment]
thanks @kevinhughes27
