### ISSUE TITLE
Discounts API and PLUS

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_api#204]
Since Plus customers get access to the discount endpoint, when is that going to be supported in the this package?

**Comment by kevinhughes27** [comment]
We must just have missed it. New resources are quite easy to add - I'll accept the PR if you write it up or maybe @joshubrown can do it

**Comment by resistorsoftware** [comment]
Al already added it to my fork... will play with it, and if it works as advertised.. I will issue a PR, Thanks

**Comment by resistorsoftware** [comment]
Any reason why a *count* message sent to the discounts endpoint returns 403 forbidden?

**Comment by kevinhughes27** [comment]
it shouldn't. @joshubrown can you find someone to look into this?

**Comment by resistorsoftware** [comment]
Active Resource calls like *find*, and *all* work perfect... tacking on count, which comes from the Base class extended Countable... throws a 403... not sure why...

**Comment by resistorsoftware** [comment]
So not only does *count* not work, but I am finding there is no finder extension for parameters like for example... give me the discount code with the code set to 'fizzbuzz'. So in a PLUS Shop with 100,000 plus discounts... or more... not only is iterating through all of them stupid, but we cannot cherry pick the one we need? Can some TLC be applied to this aspect of the API?

**Comment by resistorsoftware** [comment]
[2015-08-14T15:20:53.962809 #3]  INFO -- : GET https://fizzbuzz.myshopify.com:443/admin/discounts/count.json
I, [2015-08-14T15:20:53.963207 #3]  INFO -- : --> 403 Forbidden 303 (109.6ms)
I, [2015-08-14T15:20:53.963402 #3]  INFO -- : Headers: {"Accept"=>"application/json", "User-Agent"=>"ShopifyAPI/4.0.6 ActiveResource/4.0.0 Ruby/2.2.2", "X-Shopify-Access-Token"=>"yahright"}
I, [2015-08-14T15:20:53.963465 #3]  INFO -- : Response:
{"errors":"Scope undefined for API access: discounts. Valid scopes: admin_notifications, apps, cart_scripts, channels, content, customers, disputes, fulfillments, gift_card_adjustments, gift_cards, meta_tags, orders, products, script_tags, scripts, shipping, social_network_accounts, taxes, and themes"}
ActiveResource::ForbiddenAccess: Failed.  Response code = 403.  Response message = Forbidden.

**Comment by resistorsoftware** [comment]
Here is an example of a problem with querying for a code... ask for hotrod, get back birthday... this does work in the Shopify Admin... which gives me some hope improvements are due for the API

    I, [2015-08-14T15:48:43.287014 #3]  INFO -- : GET https://fizzbuzz.myshopify.com:443/admin/discounts.json?query=hotrod
I, [2015-08-14T15:48:43.287410 #3]  INFO -- : --> 200 OK 4723 (89.8ms)
I, [2015-08-14T15:48:43.287586 #3]  INFO -- : Headers: {"Accept"=>"application/json", "User-Agent"=>"ShopifyAPI/4.0.6 ActiveResource/4.0.0 Ruby/2.2.2", "X-Shopify-Access-Token"=>"fe8e033db559b7fc55425dafe2ae70b6"}
I, [2015-08-14T15:48:43.287677 #3]  INFO -- : Response:

     #<ShopifyAPI::Discount:0x007f8af3c6a0b8 @attributes={"id"=>75300377, "code"=>"birthday", "value"=>"10.00", "ends_at"=>"2020-12-30T19:00:00-05:00", "starts_at"=>"2014-04-29T20:00:00-04:00", "status"=>"depleted", "minimum_order_amount"=>"20.00", "usage_limit"=>1, "applies_to_id"=>nil, "applies_once"=>false, "discount_type"=>"fixed_amount", "applies_to_resource"=>nil, "times_used"=>1}, @persisted=true, @prefix_options={}>

**Comment by resistorsoftware** [comment]
As per my comment on the permissions and 403 errors.. you can see from your own internal tools screenshots that there seems to be an issue that is real here. 

![shopify_dashboard_2015-08-15_13-49-54_jpg__1147x303_](https://cloud.githubusercontent.com/assets/123307/9306104/39eb8ec0-44c4-11e5-9134-a44bfb676125.png)

**Comment by joshubrown** [comment]
Thanks for all the feedback, David. We're looking into the issue with `/admin/discounts/count.json`.

**Comment by joshubrown** [comment]
Update: the `count.json` endpoint is not available for discounts and will be removed from the docs. We have also decided to leave discounts out of the shopify_api gem for now because access is limited to Plus merchants. Thanks anyways for offering to do the pull request @resistorsoftware :)

**Comment by resistorsoftware** [comment]
Can you at least support a query for a code then, as you offer in the admin?

**Comment by joshubrown** [comment]
Sounds like a good idea. I'll look into it.

**Comment by resistorsoftware** [comment]
I know you closed this issue, but as a final note, I am hoping the API team sincerely does offer a functional query for a single code, and I would also like to mention that when you said:

> We have also decided to leave discounts out of the shopify_api gem for now because access is limited to Plus merchants

Note that Gift Cards are also for Plus only customers, yet that endpoint is supported. Hence this decision to abandon support of discounts is more likely due to some other issue with discounts. Just trying to be consistent here.
