### ISSUE TITLE
CustomCollection.where is not performing an exact match

### ISSUE THREAD

**Issue by kevinmpowell** [Shopify/shopify_api#209]
Example:
`ShopifyAPI::CustomCollection.where({title: "Blankets"}).first`

Incorrectly returns:
`
# <ShopifyAPI::CustomCollection:0x007fd95cec58a0 @attributes={"id"=>138013763, "handle"=>"blankets-throws", "title"=>"Blankets & throws", "updated_at"=>"2015-10-08T20:03:15-05:00", "body_html"=>nil, "published_at"=>"2015-10-08T20:03:15-05:00", "sort_order"=>"alpha-asc", "template_suffix"=>nil, "published_scope"=>"global"}, @prefix_options={}, @persisted=true>

`

**Comment by ShayneP** [comment]
This has since been fixed, closing.
