### ISSUE TITLE
Metafields not existing for images?

### ISSUE THREAD

**Issue by reloadseo** [Shopify/shopify_api#211]
Hi Guys, 

How does one get the metafield of an images. 

```
image.metafields
```

```
ShopifyAPI::Metafield.find(owner_id: image.id)
```

Both don't work.

**Comment by kevinhughes27** [comment]
@ShayneP

**Comment by thatdom** [comment]
I have same problem, can't get metafields for product image.

This request works, but returns an empty array, although I have ALT tag set on product image:
```ruby
ShopifyAPI::Metafield.find(:all, params: { owner_resource: "product_image", owner_id: image.id })
```

How to get Metafields for Product Image?

**Comment by reloadseo** [comment]
Aah good to know I am not the only one having this problem. 
Anybody from Shopify around? :(

**Comment by reloadseo** [comment]
@ShayneP, @kevinhughes27. 
Common! I am really stuck. I modified the API to include metfields in the image class. 
However I get a: "Response code = 403.  Response message = Forbidden." 

Is it nog allowed to set the metafields? Where do we need to be to get answers from shopify?

**Comment by kevinhughes27** [comment]
The forums would probably be a better place to post a question like this since its not really an issue with this api lib but possibly more of an api issue. Shayne is looking into it when he has time.

**Comment by ShayneP** [comment]
Currently we don't support getting image Metafields with the shopify_api gem. I'll add it to the roadmap. In the meantime, you can get image metafields using the endpoint shown in the following example :

`/admin/metafields.json?metafield[owner_id]=850703190&metafield[owner_resource]=product_image`

**Comment by reloadseo** [comment]
Oh Awesome shayne! Thanxs :)

**Comment by jrdnndtsch** [comment]
Hey - just wondering if there was any update on this or if the best approach is still to hit the endpoint? thnx :)

**Comment by ShayneP** [comment]
The best approach is still to hit the endpoint - thanks for bumping this.

**Comment by higherpowerseo** [comment]
Thank you so much ShayneP, this solution saved my life.  Are there any similar endpoints for accessing/managing files under settings/files (not assets or in products)

**Comment by ShayneP** [comment]
Now that the Shopify API is GraphQL ready, we recommend querying with GraphQL to get this data. It's _much_ faster than using the REST endpoint, especially if you use a [Bulk query](https://github.com/Shopify/shopify_api#bulk-operations) to get all of the product image metadata in bulk.
