### ISSUE TITLE
Pagination Missing from Metafields

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_api#215]
Hi,

Any time you ask for metafields the gem at this point returns only 50. That has been since 2011. These days, many resources like a product could have 51 or even 251 metafields attached. 

It would be nice if the code was tricked out to allow the standard paging and limits to be sent in, to get them all back.I had a fiendish time trying to figure out where my perfect code was busted, till I discovered this gem is pinned at 50.

Any input on this most appreciated. It is an oldy but a goody. Never really dealt with.

**Comment by ShayneP** [comment]
Agree that we should have this, will look into it. Thanks!

**Comment by resistorsoftware** [comment]
I made a version for myself that responds to 

    product,metafields(250, 2)

where the first value is the limit, and the second is the page, but then I replaced that style with a slower but more inclusive method called all_metafields, that pages through them all. 

Any thing you guys do to improve paging will blow my crud away I am sure. 

Thanks for considering this.

**Comment by resistorsoftware** [comment]
So I am seeing that no matter what I do, this limit of 50 is imposed by the Shopify backend. You never release more than 50 records. This is killing me! Is there a way to fast track a way to up that limit by having it respond to limits and pages without breaking your internals? 

PLEASE!

**Comment by ShayneP** [comment]
Your second example would work if there were more than 50 metafields on the product, but in this case there are only 50 metafields associated with that product ID.

**Comment by resistorsoftware** [comment]
I will check... there should be > 50 for sure. If not something is borked
in an algorithm that does not stop at 50 but should continue infinitum...

**Comment by flux627** [comment]
I am running into this problem too, any update on this?

**Comment by resistorsoftware** [comment]
I fixed it.

On Saturday, 12 December 2015, flux627 <notifications@github.com> wrote:

> I am running into this problem too, any update on this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Shopify/shopify_api/issues/215#issuecomment-164202878>
> .
>


-- 
Sent from Gmail Mobile

**Comment by flux627** [comment]
You fixed what? I can't get more than 50 results from the metafields endpoint.

**Comment by resistorsoftware** [comment]
​You just ask for the page and limit and you get 250 per page. ​
