### ISSUE TITLE
ActiveResource::BadRequest: Failed for Fulfillments Update

### ISSUE THREAD

**Issue by yoonwaiyan** [Shopify/shopify_api#216]
Hi, I have a shopify_app gem installed with this dependencies in Gemfile.lock:

    ...
    shopify_api (3.2.1)
      activeresource (>= 3.0.0)
      thor (>= 0.14.4)
    shopify_app (6.0.0)
      omniauth-shopify-oauth2 (~> 1.1.4)
      rails (>= 3.1, < 5.0)
      shopify_api (~> 3.2.0)
    ....

Recently the Rails app is unable to process the fulfillments update by returning an error while calling the Shopify API:

    ActiveResource::BadRequest: Failed.  Response code = 400.  Response message = Bad Request.
    from /Users/yoonwaiyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activeresource-4.0.0/lib/active_resource/connection.rb:138:in `handle_response'

I've been testing on the fulfillment update like so:

    fulfillment = {
      :order_id=>1541379651, 
      :tracking_numbers=>"1Z6F91070358910000", 
      :line_items=>[{:id=>2966626435, :quantity=>1}], 
      :tracking_company=>"UPS GROUND COLLECT"
    }

And the json has been parsed in ShopifyAPI::Fulfillment as an object:

    f = ShopifyAPI::Fulfillment.new(fulfillment)

the result is

    #<ShopifyAPI::Fulfillment:0x007ffcba3a95f8 @attributes={"tracking_numbers"=>"1Z6F91070358910000", "line_items"=>[#<ShopifyAPI::LineItem:0x007ffcba3a8d38 @attributes={"id"=>2966626435, "quantity"=>1}, @prefix_options={}, @persisted=false>], "tracking_company"=>"UPS GROUND COLLECT"}, @prefix_options={:order_id=>1541379651}, @persisted=false>

But when I called `f.save` the request returns the error as shown above. This stopped working since approx. 10 days ago. Is there a change in ShopifyAPI? or I have to update the gem to make it work?

Thanks in advance.

**Comment by yoonwaiyan** [comment]
Updated the shopify_app to 6.2.0 and shopify_app to 4.0.2, no luck :(

**Comment by cyprusad** [comment]
@yoonwaiyan ```tracking_numbers``` should be an array of strings. Alternatively pass in a ```tracking_number```. Let me know if that fixes it?

**Comment by yoonwaiyan** [comment]
@cyprusad It worked! Is that a recent change on API that broken the call?

**Comment by cyprusad** [comment]
It's just stricter type validations now. API hasn't changed per se. For reference, here is the doc https://docs.shopify.com/api/fulfillment#create
You were adding an extra ```s``` to your field name. :v:

**Comment by yoonwaiyan** [comment]
Alright, thanks so much!
