### ISSUE TITLE
getting the HTTP_X_SHOPIFY_SHOP_API_CALL_LIMIT

### ISSUE THREAD

**Issue by reloadseo** [Shopify/shopify_api#217]
Hi guys, 

Just like a lot of app we currently have problems with the API call limit. 
Is there any way to get the "HTTP_X_SHOPIFY_SHOP_API_CALL_LIMIT". 

Kind regards

**Comment by kevinhughes27** [comment]
There is this module in the gem https://github.com/Shopify/shopify_api/blob/master/lib/shopify_api/limits.rb but I haven't used it personally. It is also in the header which you can see how to access in the module
