### ISSUE TITLE
default redirect_uri

### ISSUE THREAD

**Issue by idej** [Shopify/shopify_api#224]
Hey! I think that it's a good idea to provide default redurect_uri. This is very helpful for new shopify apps where redurect_uri is required. It can be specified with option and doesn't affect old application. Does it make sense?

**Comment by kevinhughes27** [comment]
Did you mean to create this issue on shopify_app? If so we already have a default there: https://github.com/Shopify/shopify_app/blob/master/lib/generators/shopify_app/install/install_generator.rb#L22 otherwise I am not sure what you mean in the context of this repo.

**Comment by idej** [comment]
@kevinhughes27 ahh, sorry for this. I mean redirect_uri that you should use in [create_permission_url](https://github.com/Shopify/shopify_api/blob/master/lib/shopify_api/session.rb#L75) method, for new shopify partner apps you should always provide it. And my suggestion is to create default like in omniauth `:host/oauth/:provider/callback`.

**Comment by kevinhughes27** [comment]
yeah I would be ok with adding the localhost callback as a default. As an aside almost no one actually uses that class to do the auth prefering to use the omniauth provider gem instead.

**Comment by ShayneP** [comment]
Closing this issue. Since the callback URL now has to be secure, making the callback `localhost` by default would likely create more annoyance than it would solve.
