### ISSUE TITLE
Customer sort incorrectly unlike other resources(Product, Order, etc)

### ISSUE THREAD

**Issue by xguox** [Shopify/shopify_api#226]
![qq20151130-3 2x](https://cloud.githubusercontent.com/assets/1177920/11467743/29ca0292-9785-11e5-9e9b-53098069109e.png)
![qq20151130-4 2x](https://cloud.githubusercontent.com/assets/1177920/11467744/29f01bd0-9785-11e5-9b6b-48755a07f3ea.png)
![qq20151130-5 2x](https://cloud.githubusercontent.com/assets/1177920/11467745/29f5aaaa-9785-11e5-9044-d12defdecbcb.png)

http://stackoverflow.com/questions/33994862/shopify-api-customer-sort-incorrectly-unlike-other-resourcesproduct-order-etc

**Comment by xguox** [comment]
![qq20151130-0 2x](https://cloud.githubusercontent.com/assets/1177920/11491606/846c5b98-981e-11e5-804d-9b8cd68c323f.png)
![qq20151130-1 2x](https://cloud.githubusercontent.com/assets/1177920/11491607/846e278e-981e-11e5-8ad8-b0e80bc056c2.png)
![qq20151130-2 2x](https://cloud.githubusercontent.com/assets/1177920/11491608/8476738a-981e-11e5-8401-3b02eae4bd14.png)

**Comment by kevinhughes27** [comment]
@ShayneP @joshubrown

**Comment by julionc** [comment]
Bump

**Comment by ShayneP** [comment]
Closing issue, this bug has been resolved. Sorting using `order` on Customers is now working correctly.
