### ISSUE TITLE
Can't update Order Tax

### ISSUE THREAD

**Issue by playmakers** [Shopify/shopify_api#227]
Hey

I'd like to update the tax value of an existing order:

```
order = ShopifyAPI::Order.find(123456)
tax = ShopifyAPI::TaxLine.new({"title"=>"MwSt", "price"=> 72.17, "rate"=>0.19})
order.tax_lines << tax
oder.total_tax = 72.17
order.save!
```

but somehow this doesn't get saved/updated. What am I doing wrong?

**Comment by kevinhughes27** [comment]
You can't update the parts of the order related to the financial information through the API since money changed hands this record needs to stay in tact. You can update things like note etc.
