### ISSUE TITLE
Support For Retrying Requests? 

### ISSUE THREAD

**Issue by sshaw** [Shopify/shopify_api#230]
It's not uncommon to get a `429`, there's even a `Retry-After` header. Why not add retry functionality to this API client? 

Something like:

```ruby
ShopifyAPI.retry { customer.update_attribute(:tags, "foo")  } 
ShopifyAPI.retry(30) { customer.update_attribute(:tags, "foo") }  

def ShopifyAPI.retry(seconds_to_wait = nil)
    raise ArgumentError, "block required" unless block_given?
    raise ArgumentError, "seconds to wait must be > 0" unless seconds_to_wait.nil? || seconds_to_wait > 0 # maybe enforce 2?

    result = nil
    retried = false

    begin
      result = yield
    rescue ActiveResource::ClientError => e
      raise unless !retried && e.response.code.to_i == 429
      seconds_to_wait = (e.response["Retry-After"] || 2).to_i unless seconds_to_wait
      sleep seconds_to_wait

      retried = true
      retry
    end

    result
end
```

**Comment by kevinhughes27** [comment]
Its an interesting idea but I think retry management is beyond the scope of this gem as users might need different approaches. For example a lot of apps will make all their API calls in background jobs and will re-queue the job with a delay to handle API limits.

Its a nice function though so thanks for sharing!

**Comment by mikeyhew** [comment]
@kevinhughes27 sure, different approaches need to be taken in different circumstances, but in a fairly common case the best approach is to block until the time specified by the Retry-After header, and then retry. This could be added to the gem if we give people a configuration option for it. We could call it `number_of_retries_on_429`, and if the default value is 0 then the gem would behave exactly as it does now.

**Comment by mikeyhew** [comment]
@sshaw With the `retry` method you suggested, you have to wrap every method invocation that makes an API call, or lose your place in control flow. If the 429-handling and retrying was done somewhere farther down in the stack, say somewhere in ActiveResource::Connection (or a subclass of it), then we could avoid having to wrap all those api calls in blocks. @kevinhughes27 I guess we'd have to be careful of messing with ActiveResource internals though if we're supporting thread-safe ActiveResource

**Comment by sshaw** [comment]
> @sshaw With the retry method you suggested, you have to wrap every method invocation 
> that makes an API call, or lose your place in control flow.

Yes, of course, that's expected. Loss of control flow for a recoverable error is the problem that this will resolve.

I've been using [a slightly modified version](https://gist.github.com/sshaw/6043fa838e1cecf9d902) of the above in production for a while. It's solved

>  If the 429-handling and retrying was done somewhere farther down in the stack, 
> say somewhere in ActiveResource::Connection

Ah, so the purpose of this issue was not to modify `ShopifyAPI`'s internals, but to add a util function that callers can use as they see fit. 

> I still prefer this as an opt in thing via adding code and not as part of the gem

Yes, my intention was opt-in.

**Comment by mikeyhew** [comment]
@sshaw 
>Ah, so the purpose of this issue was not to modify ShopifyAPI's internals

As you wish. I didn't like the idea of having to wrap all my API calls in `retry` blocks, so I did some trailblazing and created my own `ApiConnection` class that does retrial as well as some basic throttling. Gist [here](https://gist.github.com/mikeyhew/79dfd1189f14811425dad97e7f6545ca).

In order to get `ShopifyAPI::Base` to use `ApiConnection` instead of `ActiveResource::Connection`, I had to make a small change to activeresource. PR here: rails/activeresource#222. @kevinhughes27 if it gets merged, you can stop monkey-patching `ActiveResource::Connection` and use a subclass instead - see here: [https://github.com/mikeyhew/shopify_api/compare/master...mikeyhew:subclass-connection](https://github.com/mikeyhew/shopify_api/compare/master...mikeyhew:subclass-connection)

**Comment by kevinhughes27** [comment]
@mikeyhew cool! thanks for sharing! I imagine you could package this as a gem that people could add if they wanted retry functionality. That is the level of **opt** in that I think would be ideal. If you do this you can open a PR to add a link to your gem in the readme here.

**Comment by adamof** [comment]
Hey @mikeyhew I wonder if you ever packaged this as a separate gem, since we're quite interested in using it.

@radkomih

**Comment by mikeyhew** [comment]
@adamhof yes I did. The code isn't on rubygems yet, but it's up on [GitHub](https://github.com/mikeyhew/shopify_app_mixins).

Hopefully the documentation will explain how to use it, but if you have any questions, please post an issue there.

**Comment by adamof** [comment]
Great news! :) Thanks!

**Comment by adamof** [comment]
For anyone wondering: Mike made a small type and the link in his comment is going to another one of his repos
https://github.com/mikeyhew/shopify_app_mixins **should be** https://github.com/mikeyhew/shopify_api_mixins
