### ISSUE TITLE
Check gift card balance

### ISSUE THREAD

**Issue by sqlninja** [Shopify/shopify_api#231]
I need to check the balance of a gift card by it's code.
I have tried the following: ```ShopifyAPI::GiftCard.find(:all, :params => { :code => code })```
But just returns this:
```ActiveResource::ServerError: Failed.  Response code = 501.  Response message = Not Implemented.```
I also just tried to return all gift cards with: ```ShopifyAPI::GiftCard.find(:all)``` but get the same message so is this functionality not implemented in the api?

**Comment by kevinhughes27** [comment]
The gift card api is Shopify plus only https://docs.shopify.com/api/gift_card
