### ISSUE TITLE
Refund Endpoint

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_api#232]
Examining an Order with Refunds. Under Refunds Array are refund objects, A Refund Object has an array of refund line items. Even if the refunded items are identical though, the API produces an array of each one separately instead of incrementing quantity. Is this by design? 

The Transactions associated with a refund include a parent ID that has no connection to any other object in the entire order. What is the parent ID? What does it reference? There is an endpoint listed in the API as Refund, but this gem has no refund resource in it. Is that something coming soon?

**Comment by julionc** [comment]
Add the Refund Endpoint supported here. (e3886bb50a76f956d8e4bc78b557ff80de9e8121)
Does this look alright to you? LMK
