### ISSUE TITLE
association declaration missing

### ISSUE THREAD

**Issue by toyflish** [Shopify/shopify_api#234]
When I retrieve an order from the api all the transactions are send with the request for the order. Do I call order.transactions on the local object another api-request is send to retrieve transactions from the api again. I found out it's because order-transactions are not associated with has_many in the Order-ActiveResource. Instead there is this method:
```
    def transactions
      Transaction.find(:all, :params => { :order_id => id })
    end
````

**Comment by kevinhughes27** [comment]
Interesting - you used to have to specify a header if you wanted them included (thats why this method is here). Maybe this method should check the internals to see if we already have them. 

If we really do always return them now we can set the has_many

**Comment by toyflish** [comment]
sorry I was wrong, there is only one transaction returned in the order request. It's sitting in the order.refunds - I did not look at the yaml file the right way.
