### ISSUE TITLE
ActiveResource::ResourceNotFound: Failed.  Response code = 404.  Response message = Not Fo

### ISSUE THREAD

**Issue by enriquesalceda** [Shopify/shopify_api#236]
Hi guys,

I've been working on this Shopify APP, and everything was fine until today. In order to find a product, I was doing this:

``` Ruby
ShopifyAPI::Product.find 3685279297
```
That was retrieving a product. However, now every time that I try to find a product like that, I receive the following error:

```
ActiveResource::ResourceNotFound: Failed.  Response code = 404.  Response message = Not Found.
from /Users/enriquesalceda/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activeresource-4.0.0/lib/active_resource/connection.rb:144:in `handle_response'
```
Could someone help me with this? Please.

**Comment by kevinhughes27** [comment]
Are you sure the ID is right and that your api_session is for the right shop? 404 means that the object doesn't exist

**Comment by enriquesalceda** [comment]
My bad, I was connected to a different Shopify store. Thanks for your help.
