### ISSUE TITLE
Refund Endpoint Discussion with Transaction Endpoint

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_api#238]
Refund Endpoint is Read-Only. We can only Issue GET requests against it. 

So if we want to issue a refund, we need to create a Transaction of type refund. Thing is, the Transaction Endpoint accepts POST requests containing very little specific detail. So if I have an order where I need to use the API to refund one out of three of a quantity of a line item on an order, there is no way to do that. That is a big hole in the API as refunds are a very common transaction.

Would be nice if the Transaction Endpoint could be improved to allow for partial refunds with respect to actual line items, instead of just an arbitrary cash amount.

**Comment by ShayneP** [comment]
Agreed - it's something that we'll look at. Thanks David.

**Comment by resistorsoftware** [comment]
Rockin' !!
