### ISSUE TITLE
Order Endpoint, line item issue

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_api#239]
variant_title is a line item attribute. Some merchants ignore it and it is left as Default Title. Some may not like that, so they erase Default Title leaving an empty string. 

The API provides orders to an App as JSON. JSON has no concept of a nil value, but I best an empty string is ok. I am wondering why I have an App throwing a no method X on a nil object error, when the nil object is the variant_title? 

How can the variant title be nil? Should it not be just an empty string at worst? 

A Pry session shows how it could be, but I am confused about how Shopify maps a variant title to nil in the first place?

```
x = { foo: nil }.to_json
=> "{\"foo\":null}"
y = JSON.parse(x)
=> {"foo"=>nil}
y["foo"]
=> nil       # so ya, it can happen, but only if the original object is actually nil. 
```

**Comment by ShayneP** [comment]
Thankfully, this is no longer an issue. The "Default Title" label is no longer exposed to merchants, and API clients aren't able to do anything that would set it to a nil value. You shouldn't run into this again!
