### ISSUE TITLE
multiple product id find

### ISSUE THREAD

**Issue by jchen123** [Shopify/shopify_api#246]
Currently there's not a good way to retrieve multiple shopify products by getting their ids, though this exists in the Shopify API.  ShopifyAPI::Product.find() only gives you one.  :all is not a good choice since you want to filter.

**Comment by jagthedrummer** [comment]
@jchen123 Did you figure out a way to do this?

**Comment by jagthedrummer** [comment]
Ah, I found it!

```
ShopifyAPI::Product.find(:all, params: { ids: '11543795530,11543791690' })
```
