### ISSUE TITLE
RecurringApplicatiomCharge

### ISSUE THREAD

**Issue by corehook** [Shopify/shopify_api#252]
Hello
Using oauth we are getting the shop's token with the purpose of using it for creating bills using shopify_api. We successfully create ApplicationCharge and RecurringApplicatiomCharge. The user can confirm or deny that request. But we have a question regarding the RecurringApplicationCharge: will the shopify notify our backend at each withdrawal of money for subscription from the account ? Or should we check the withdrawal fact using API in order to know to prolong the subscription or not?

**Comment by julionc** [comment]
You need to create a custom method to check the subscription status using the `RecurringApplicationCharge` ID

**Comment by asecondwill** [comment]
Some more details on how to do that would be really great.

**Comment by asecondwill** [comment]
ok, i guess as simple as

```
rec_charge = ShopifyAPI::RecurringApplicationCharge.find(shopify_charge_id )
unless rec_charge.status
  # note in the db its not active
end
```
