### ISSUE TITLE
Fulfillment is being returned without an order_id

### ISSUE THREAD

**Issue by kwestein** [Shopify/shopify_api#253]
When I do
````
fulfillment = ShopifyAPI::Fulfillment.find(return_delivery.fulfillment_id, :params => {:order_id => return_delivery.order_id})
fulfillment.order_id # returns nil
````

So when I try to do fulfillment.update_attributes I am getting ````ActiveResource::MissingPrefixParam: order_id prefix_option is missing```` unless I explicitly include order_id in the params again

cc: @kevinhughes27

**Comment by kevinhughes27** [comment]
@jamiemtdwyer @dominiquesr

**Comment by dominiquesr** [comment]
This is intentional. Why do you need it? 

@garethson

**Comment by kevinhughes27** [comment]
I don't think its related to that but it would be great if someone could look. If we fetch an object it should have all the information on it ..

**Comment by garethson** [comment]
I made this change here: https://github.com/Shopify/shopify/pull/68873/files#diff-95e18e9c2fe31cfa259d2cf597f0cb5eL36 to bring us into alignment with our "Deprecated (removal March 1, 2015)" comment in https://docs.shopify.com/api/reference/fulfillmentservice. I don't *think* this is related either. Which is weird.
