### ISSUE TITLE
Value null for parameter ShippingSpeedCategory is invalid. Reason: IllegalValue. 

### ISSUE THREAD

**Issue by Trimakas** [Shopify/shopify_api#263]
Getting this error when I try and auto fulfill an order using a carrier service I setup thru the Shopify API that connects to the Amazon API.

My shipping rates are showing correctly to the end user, but on the back end it looks like this isn't being sent by Shopify to Amazon FBA.

However, I don't see how I can send this to Shopify? The only fields I'm aware of are the following:
 
`                  "service_name": "fedex-priorityovernight",
                   "service_code": "1D",
                   "total_price": "3587",
                   "currency": "USD",
                   "min_delivery_date": "2013-04-12 14:48:45 -0400",
                   "max_delivery_date": "2013-04-12 14:48:45 -0400"`

Is this a bug or am I missing something?

Thanks
Todd

**Comment by jamiemtdwyer** [comment]
Hey Trimakas,

Were you able to solve this issue? If not, I would be happy to assist.

If you were able to solve this, would you mind sharing the solution?

**Comment by Trimakas** [comment]
Yep I did.. despite the very weird error message I got, it was my shipping name that was the problem.. I had used "Standard" when in fact it should have been "Standard Shipping" so that was it..
