### ISSUE TITLE
How does find specific customer e-mail in ShopifyAPI::Customer 

### ISSUE THREAD

**Issue by prasanthrubyist** [Shopify/shopify_api#266]
Hi, I need to find particular customer e-mail 
I've tried  **ShopifyAPI::Customer.all.find(email: "yyyy.gmail.com") **But this will return all customers, How can I find that specific email customer 

Thanks

**Comment by mksm** [comment]
```
ShopifyAPI::Customer.find(:first,
  from:      '/admin/customers/search.json',
  params: { query: 'email:john@baz.org' }
)
```

**Comment by prasanthrubyist** [comment]
thanks @mksm

**Comment by prathap442** [comment]
Thanks hughes
