### ISSUE TITLE
Webhook topic orders/update

### ISSUE THREAD

**Issue by goncalopereira** [Shopify/shopify_api#269]
Hi,
Trying to use the shopify_api to create a topic for orders/update.

If I do orders/create:
```
webhook = ShopifyAPI::Webhook.create(address: "https://SHOP/orders/create", topic: "orders/create", format: "json")
webhook.save
```

I get that Webhook and it shoes up on
`ShopifyAPI::Webhook.all`

If I try
```
webhook = ShopifyAPI::Webhook.create(address: "https://SHOP/orders/update", topic: "orders/update", format: "json")
webhook.save
```

The webhook is not created.

Is this an issue or a known behaviour? My Order endpoint is Idempotent so I'd prefer to keep only Update.

Regards

**Comment by kevinhughes27** [comment]
There should be an error on the object that didn't save with more information. `webhook.errors`

**Comment by goncalopereira** [comment]
Thank you for the help.

I saw that the issue is due to the topic being called 'orders/updated' not 'orders/update' as seen in the Admin UI.
