### ISSUE TITLE
Shopify::Order#shipping_price does not reflect true shipping value

### ISSUE THREAD

**Issue by eellson** [Shopify/shopify_api#273]
Running shopify_api 4.0.7 I see the following behavior:

```ruby
> params = {
  "shipping_lines"=>[{
      "price"=>"3.99",
  }]
}
#=> {"shipping_lines"=>[{"price"=>"3.99"}]}

> order = Shopify::Order.new(params)
#=> #<Shopify::Order:0x007f9eae917ec8 @shopify_order=#<OpenStruct shipping_lines=[{"price"=>"3.99"}]>>

> order.shipping_price
=> 3

> order.shipping_price.class
=> Fixnum
```

I'm not sure if this is the intended behavior, but given the method's name I would expect `#shipping_price` to return a value which reflects the total shipping price as a float, not a Fixnum.

**Comment by kevinhughes27** [comment]
Does the issue still happen if you save the object? I am a bit surprised you can even access `shipping_price` after using new with only a shipping_line. How does activeresource even know how to reach into that data

**Comment by eellson** [comment]
There is no `#save` method on `Shopify::Order` but tbh I would assume with the params I've given in the example it would be invalid. I've cut those down from the full params I got through in a webhook request from Shopify, in order to make the testcase a little cleaner!

My usecase is this:

* customer places an order on shopify
* webhook is setup to notify an endpoint in my application upon placing an order, with order params
* I use these params to construct a `Shopify::Order` instance
* I call methods on this instance to generate a report

Perhaps I am using the gem in an unusual way?

**Comment by kevinhughes27** [comment]
there is `#save` http://api.rubyonrails.org/v3.2.6/classes/ActiveResource/Base.html#method-i-save

That use case sounds fine - so passing the full contents of the webhook results in weird data for shipping_price?. 

If you don't need to re-save the object back to Shopify you don't really need to create the ShopifyAPI::Order instance but it should still work.

**Comment by kevinhughes27** [comment]
Wait - there is your issue. Where does Shopify::Order come from? Thats not part of this gem. this Gem provided `ShopifyAPI::Order`

**Comment by eellson** [comment]
Ah, bingo! You are correct, the bug is on my end not the gem's. Thanks for spotting that @kevinhughes27, sorry for wasting your time with a poorly named class!

**Comment by kevinhughes27** [comment]
No worries!
