### ISSUE TITLE
Potential dependency issue with published gem

### ISSUE THREAD

**Issue by andriytyurnikov** [Shopify/shopify_api#274]
Hello, while bumping shopify_app dependencies I've faced build error related to dependency resolution
```
shopify_api (~> 4.2.2) was resolved to 4.2.2, which depends on
        activeresource was resolved to 2.0.1, which depends on
```
Also, if you visit rubygems.org page for 4.2.2 release [https://rubygems.org/gems/shopify_api/versions/4.2.2](https://rubygems.org/gems/shopify_api/versions/4.2.2) weird activeresource dependency version is displayed, which signals that maybe gem was published with Gemfile_ar42threadsafe, which does not specify activeresource-4.0.0 dependency.

With that in mind, it looks like re-publishing fresh gem version might be required (with right Gemfile used)

**Comment by kevinhughes27** [comment]
ping @peterjm can you take a look at this?

**Comment by Azael05x** [comment]
same issue here [#268](https://github.com/Shopify/shopify_api/issues/268)

**Comment by kevinhughes27** [comment]
ping!

**Comment by Azael05x** [comment]
Any update on this one? Rails 5 is now officially released, and this gem does not support it, because of dependency thingies

**Comment by kevinhughes27** [comment]
being handled here: #240

I am going to close this in the meantime to reduce confusion.
