### ISSUE TITLE
Coupons API

### ISSUE THREAD

**Issue by orenmazor** [Shopify/shopify_api#275]
Hey guys, I know that Coupons API is only available to Plus stores.

But as a developer, I don't necessarily know which stores have Plus and which don't.  I could look at the Plan name under `ShopifyAPI::Shop`, but you guys can change that string value anytime, which means its something I would need to watch out for.

The gem currently raises if I try to access the coupons API on a non-plus store.

```
[10] pry(main)> ShopifyAPI::Discount.count
ActiveResource::ForbiddenAccess: Failed.  Response code = 403.  Response message = Forbidden.
from /Users/orenmazor/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeresource-759ded7490cb/lib/active_resource/connection.rb:142:in `handle_response'
[9] pry(main)> ShopifyAPI::Discount.all
ActiveResource::ServerError: Failed.  Response code = 501.  Response message = Not Implemented.
from /Users/orenmazor/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeresource-759ded7490cb/lib/active_resource/connection.rb:156:in `handle_response'
```

The raise comes from AR, which is correct AR behaviour.

What I'm wondering is why does the Shopify API return a 501 instead of an empty array? wouldn't that make more sense?

cc @kevinhughes27 @perobertson

**Comment by kevinhughes27** [comment]
For your case it might but then how would you know the difference between not having the feature and not having coupons? I would wrap that api call for your app to return empty array if thats what you need.

**Comment by jamiemtdwyer** [comment]
The possible values of `plan_name` are very unlikely to change, while
`plan_display_name` may change at some point to reflect the new naming
scheme.

**Comment by orenmazor** [comment]
@jamiemtdwyer what are the current possible values? just because shopify calls it "Plus" right now, doesn't meant it's always going to be Plus, or just Plus customers get the feature. that can literally change any day.

@kevinhughes27 shit. thats a good point. it wouldn't matter to me at all, tbh, but another consumer of the API might want to know the difference between no access and empty list. I might be SOL on wanting to avoid 'flow control by rescue' here :/

**Comment by jamiemtdwyer** [comment]
`plan_name` has quite a few distinct values, but `starter`, `basic,` `professional`, `unlimited`, `shopify_plus` will cover most shops. I see your point about discount availability though.

**Comment by orenmazor** [comment]
so, I thought about this some more and I've come to the conclusion that you guys are doing the right thing here:

1. a 501 is the correct response for a resource that is not available due to plan stuff.
2. AR raising is the correct response for a 4xx or 5xx response.
3. routing by plan name is brittle.

I'm going to accept the "flow control by exception" that AR forces on us here, because that is the most antifragile thing to do.

**Comment by abrambailey** [comment]
Is this still an issue. I have a very small low-volume Shopify store and want to generate coupon codes using the API, but I am seeing `ActiveResource::ForbiddenAccess: Failed.  Response code = 403.  Response message = Forbidden.`
