### ISSUE TITLE
How can I remove {% include 'my_code' %} tag after uninstall my app in product.liquid file

### ISSUE THREAD

**Issue by prasanthrubyist** [Shopify/shopify_api#276]
Hi all,

While installing app I've insert {% include 'my_code' %} tag in templates/product.liquid file, I want to remove  {% include 'my_code' %} after uninstall my app, How can I do this in ShopifyAPI::Webhook api or is there any other way to do ?? Kindly guide me please....

**Comment by kevinhughes27** [comment]
This question should be asked on the [forums](https://ecommerce.shopify.com/c/shopify-apis-and-technology) since its not related to the api library.

What you want is the uninstall webhook.

**Comment by prasanthrubyist** [comment]
Okay thanks...
