### ISSUE TITLE
Blog Articles pagination request

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_api#278]
Hi,

Just like a lot of resource endpoints, there is a lot of potential improvement on the relations. In this case, I am migrating a blog and many articles to another shop. When I get a blog, I can access the articles via the method articles. 

```
blog = ShopifyAPI::Blog.first
blog.articles.count
=> 50
```

**This blog has 154 articles.**

It would be nice if we could have some sort of blessed by Shopify **page and limit** functionality in the API code without having to Monkeypatch our own.

**Comment by davidwparker** [comment]
Products has the same limitation:

```ruby
products = ShopifyAPI::Products
products.count
=> 50
```

Is there a good workaround for this?

**Comment by ShayneP** [comment]
I know this is an old issue, but for future people who may stumble across this, it is possible if you change your code just a bit :

```ruby
blog = ShopifyAPI::Blog.first
ShopifyAPI::Article.count(blog_id: blog.id)
```

**Comment by resistorsoftware** [comment]
I am not understanding that. If I call the Article endpoint and ask for a count how is that returning to me all the actual articles?

**Comment by ShayneP** [comment]
Sorry, I misunderstood your question — updated my response! 

I thought you were looking for a count, this will return the actual articles.

**Comment by resistorsoftware** [comment]
I will one day soon learn if these old shortcomings of the RestAPI are now put to bed with GraphQL. Perhaps they are. We'll have to see. Things like, if I am asking for the products in a collection, and there are > 50, show me them all, I am not limited to 50!
