### ISSUE TITLE
Add Rails 5 Support

### ISSUE THREAD

**Issue by wassimk** [Shopify/shopify_api#282]
I'm trying to upgrade our project to Rails 5 and am getting this:

``` shell
   shopify_api was resolved to 4.3.0, which depends on
      activeresource (>= 3.0.0) was resolved to 3.0.0, which depends on
        activemodel (= 3.0.0)
```

**Comment by kevinhughes27** [comment]
Can you paste more of the output? I don't think that snip that alone gives all the details of the issue

**Comment by wassimk** [comment]
For sure, the project is on Rails 5.0 and my next step is to add `shopify_api` back in:

``` ruby
gem 'shopify_api', github: 'Shopify/shopify_api'
```

Here is the full output of `bundle install`:

``` bash
➜  api (rails-5-upgrade) ✗ bundle install
Fetching git://github.com/Shopify/shopify_api.git
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies....
Bundler could not find compatible versions for gem "activemodel":
  In snapshot (Gemfile.lock):
    activemodel (= 5.0.0)

  In Gemfile:
    active_model_serializers (= 0.9.2) was resolved to 0.9.2, which depends on
      activemodel (>= 3.2)

    rails (~> 5.0) was resolved to 5.0.0, which depends on
      activerecord (= 5.0.0) was resolved to 5.0.0, which depends on
        activemodel (= 5.0.0)

    rails (~> 5.0) was resolved to 5.0.0, which depends on
      activerecord (= 5.0.0) was resolved to 5.0.0, which depends on
        activemodel (= 5.0.0)

    shopify_api was resolved to 4.3.0, which depends on
      activeresource (>= 3.0.0) was resolved to 3.0.0, which depends on
        activemodel (= 3.0.0)

    web-console was resolved to 3.3.1, which depends on
      activemodel (>= 5.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

**Comment by kevinhughes27** [comment]
try `bundle update activeresource`

Your activeresource is behind and a couple of versions

**Comment by wassimk** [comment]
So, even a brand new Rails 5 app with just the `shopify_api` gem was having the same error. I had to add `rails/activeresource` master branch to the `Gemfile` and it's building now. 

I'm guessing when 5.0.0 of activeresource is put on rubygems it will self-resolve for most people. Thanks for your help!

**Comment by kevinhughes27** [comment]
cc @swalkinshaw

**Comment by heliocola** [comment]
@wassimk +1
I added this on my Gemfile and it is building it successfully.
gem 'activeresource', github: 'rails/activeresource'
gem 'shopify_api', '~> 4.3'

**Comment by swalkinshaw** [comment]
Yeah, the only solution right now is adding `gem 'activeresource', github: 'rails/activeresource'`. I'll add a section to the README about Rails 5 usage.

**Comment by swalkinshaw** [comment]
Added in https://github.com/Shopify/shopify_api/pull/283
