### ISSUE TITLE
Rails 5.0.0 and shopify_api

### ISSUE THREAD

**Issue by zinyosrim** [Shopify/shopify_api#295]
Hi,

I'm getting following message with bundle install

Fetching git://github.com/rails/rails-observers.git
Fetching git://github.com/Shopify/shopify_api.git
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies...
Bundler could not find compatible versions for gem "rails":
  In snapshot (Gemfile.lock):
    rails (= 5.0.0)

  In Gemfile:
    rails (~> 5.0.0)

    shopify_app (~> 6.2.0) was resolved to 6.2.0, which depends on
      rails (< 5.0, >= 3.1)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

This is my Gemfile:

`source 'https://rubygems.org'

gem 'rails', '~> 5.0.0'
gem 'pg', '~> 0.18'
gem 'puma', '~> 3.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'rails-observers', github: 'rails/rails-observers'
gem 'activeresource'
gem 'shopify_api', github: 'Shopify/shopify_api'
gem 'shopify_app', '~> 6.2.0'
gem 'jquery-rails'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'

group :development, :test do
  gem 'byebug', platform: :mri
end

group :development do
  gem 'web-console'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]`

Checked out the 5.0.0beta3 thread but it didn't change anything

Any Ideas?
Thanks
Zin

**Comment by kevinhughes27** [comment]
You are using an old version of Shopify app. Try `7.1.0`
