### ISSUE TITLE
ERROR:  Could not find a valid gem 'activesupport' (= 2.3.0) in any repository

### ISSUE THREAD

**Issue by vrehm** [Shopify/shopify_api#299]
<img width="1243" alt="capture d ecran 2016-08-23 11 35 27" src="https://cloud.githubusercontent.com/assets/8135206/17887249/e4d5732e-6925-11e6-8411-cdcecefe694e.png">
Last login: Tue Aug 23 10:47:41 on ttys000
➜  katalog git:(master) gem install shopify_cli                                                                                                  [2.3.1]
ERROR:  Could not find a valid gem 'activesupport' (= 2.3.0) in any repository
ERROR:  Possible alternatives: activesupport

Hello, i can't use the sopify_cli gem, how can i fix it ?

**Comment by vermeeca** [comment]
I ran into the same, and found the following issue under the shopify_cli project as well.  The workaround listed here worked OK for me.

https://github.com/Shopify/shopify_cli/issues/5
