### ISSUE TITLE
Update without find

### ISSUE THREAD

**Issue by anthonator** [Shopify/shopify_api#301]
Is it possible to update a record without first issuing a `find`? I want to update a variant but I already have the id so issuing a find just seems like an unneeded API call.

**Comment by kevinhughes27** [comment]
Yes this is possible just create an instance of the object with the ID and call save. It will be sent as an update not a create.

**Comment by maartenvg** [comment]
Certainly. You can just initialize an empty object (say `p = Product.new`),
set the id and the fields you want to change. Then call `save` on it.

**Comment by anthonator** [comment]
Thank you!
