### ISSUE TITLE
How to add shopify checkout to a web app

### ISSUE THREAD

**Issue by chashmeetsingh** [Shopify/shopify_api#302]
Please help, need steps to add shopify checkout to a web app, docs would also do 
Thanks!

**Comment by jamiemtdwyer** [comment]
Programmatically creating checkouts is currently limited to a select number of clients through the Channels SDK. There is some more information [here](https://help.shopify.com/api/tutorials/sell-through-the-checkout-api). 

In the future, issues like this that are not specifically related to the `shopify_api` gem should go [in the forums](https://ecommerce.shopify.com/c/shopify-apis-and-technology).
