### ISSUE TITLE
Dormant shops returning wrong code

### ISSUE THREAD

**Issue by orenmazor** [Shopify/shopify_api#306]
Hey folks,

Weird case I just came across. 

If you query the checkouts of a shop that has gone dormant, you get a 500 

```
GET https://snowdevil.myshopify.com:443/admin/checkouts/count.json?status=open&updated_at_min=2016-09-08T00%3A03%3A31%2B00%3A00
I, [2016-09-10T00:03:32.269063 #14226]  INFO -- : --> 500 Internal Server Error 37 (162.4ms)
I, [2016-09-10T00:03:32.269174 #14226]  INFO -- : Headers: {"Accept"=>"application/json", "User-Agent"=>"ShopifyAPI/4.3.0 ActiveResource/4.1.0 Ruby/2.3.1", "X-Shopify-Access-Token"=>"OxDEADBEEF"}
I, [2016-09-10T00:03:32.269198 #14226]  INFO -- : Response:
{"errors":"Checkout System disabled"}
```

which comes up as an `ActiveResource::ServerError`. this seems weird to me because its not actually a server error. its a merchant error, which would probably be more along the lines of a 4xx. I'd pick 402, as its the closest (I mean, the shop is dormant…)

thoughts?

/cc @kevinhughes27 @maartenvg

**Comment by maartenvg** [comment]
That shouldn't be a 500. Are your timestamps in UTC? And you have a
checkout token or ID for me so I can cross-reference our logs?

**Comment by orenmazor** [comment]
Yup, we do our stuff in UTC.

a sample request ID is `de997ad7-56df-4fa7-aae3-e96163dabb50` for a sample shop `8924546`
