### ISSUE TITLE
4.3.x not compatible with ActiveResource 3.x, despite gemspec

### ISSUE THREAD

**Issue by scotchi** [Shopify/shopify_api#310]
Commit aba0fbe60334f6c27e43a5f858cb99bfc4ece7b6 breaks ActiveResource 3.x compatibility, though the Gemspec doesn't specify a minimum compatible version.  Either the Gemspec or the code should be fixed.

**Comment by kevinhughes27** [comment]
Let's bump the gemspec. There is no reason to support an old version of ActiveResource that I am aware of. PR's welcome!
