### ISSUE TITLE
Unable to create gift cards from the API

### ISSUE THREAD

**Issue by cabouffard** [Shopify/shopify_api#311]
Hi, 

We have recently changed to the Shopify plan that allows gift cards. 

When trying to use the ShopifyAPI in order to create new gift cards we are hit with that error:

```ruby
> gc = ShopifyAPI::GiftCard.new(initial_value: 25.0)
#<ShopifyAPI::GiftCard:0x007fb22d166a98 @attributes={"initial_value"=>25.0}, @prefix_options={}, @persisted=false>
> gc.save
ActiveResource::ServerError: Failed.  Response code = 501.  Response message = Not Implemented.
```

We have made sure that our Private App has the `Read and write` access in order to satisfy the API needs.

Is there something else we are missing?
Thank you!

**Comment by jamiemtdwyer** [comment]
Hey cabouffard,

Access to gift cards is granted on request to private API clients belonging to Plus stores. Please contact apps@shopify.com with your API key in order to be granted access.
