### ISSUE TITLE
Checkout.all returning nothing

### ISSUE THREAD

**Issue by nsweeting** [Shopify/shopify_api#312]
Hi there,

I have setup a Webhook for 'checkouts/create'. After creating a new checkout within the store interface, I receive this webhook. Right after this, I am then attempting to retrieve all my checkouts.

`ShopifyAPI::Checkout.all(page:0, limit:250) => [ ]`

When I hit the endpoint https://mystore.myshopify.com/admin/checkouts.json it returns the following:

```
{
  "checkouts": []
}
```

When I hit https://mystore.myshopify.com/admin/checkouts/111111.json it returns the following:

```
{
  "errors": "[API] This action requires read_checkouts scope."
}
```

If I try and add read_checkouts scope during the oauth flow, I get the following error:

Oauth error invalid_scope: The access scope is invalid: read_checkouts

Even though the webhook confirms a Checkout creation - why is it not showing up?

Any help would be appreciated.

Cheers
Nick

**Comment by nsweeting** [comment]
When I hit https://mystore.myshopify.com/admin/checkouts/111111.json it returns the following:

```
{
  "errors": "[API] This action requires read_checkouts scope."
}
```

If I try and add read_checkouts scope during the oauth flow, I get the following error:

Oauth error invalid_scope: The access scope is invalid: read_checkouts

**Comment by jamiemtdwyer** [comment]
Closing this as it is not an issue with `shopify_api`.

If anyone is interested in following this issue, please see https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/checkout-endpoint-returning-403-374973
