### ISSUE TITLE
ShopifyAPI::Fulfillment updating one line item but not all (not working)

### ISSUE THREAD

**Issue by Trimakas** [Shopify/shopify_api#313]
I have a new order, being fulfilled by my own custom fulfillment service. The order contains two line items.
line item id's 8489568775 & 8489568711
order id: 4472357127

I create a new fulfillment in order to fulfill just one item and provide its tracking number like so:
  `try = ShopifyAPI::Fulfillment.new(order_id: 4472357127, line_items: [{"id": 8489568775}] )
   try.tracking_numbers = ["doesthisworktry2"]
   try.save`

Its successful, but on the store admin, there is no tracking number, and no visible change to the order.

I then go to try and fulfill the other line item, thinking they both have to be updated before a change happens.. I do this:
  `try = ShopifyAPI::Fulfillment.new(order_id: 4472357127, line_items: [{"id": 8489568711}] )
   try.tracking_numbers = ["doesthisworktry2"]
   try.save`

And now I get an error saying that the line item has already been fulfilled.

But on the store admin, I can see there has been no change to the order.. no tracking numbers, and still in a "pending fulfillment" status.

I go and try and do this: 
  `fulfill = ShopifyAPI::Fulfillment.find(3713317639, :params => {:order_id => 4472357127})`
  'fulfill.tracking_numbers = ["didthiswork", "notatall"]'
  'fulfill.tracking_company = "USPS"'
  'fulfill.tracking_urls = ['https://google.com', 'https://joe.com']'
  'fulfill.save'

This works fine, but does not assign a tracking number to an item on the order, so the user does not know what tracking number goes with what item in their order.

Is this a bug or did I somehow do something wrong??

**Comment by DavidWard1980** [comment]
If you tracking code is your name then thats what it will post. You need to encode your tracking name to a code, then all items will be marked with your upc, or code. Kapeesh.

**Comment by DavidWard1980** [comment]
Try using [ "id" : and whatever your number id is }]  )   and that should fix it ok.

**Comment by Trimakas** [comment]
Whew.. Not sure I follow.. An example would be huge..  just from my first snippet of code.. so the "id" should go somewhere and what would the id match back too??

fulfill = ShopifyAPI::Fulfillment.find(3713317639, :params => {:order_id => 4472357127})
'fulfill.tracking_numbers = ["didthiswork", "notatall"]'
'fulfill.tracking_company = "USPS"'
'fulfill.tracking_urls = ['https://google.com', 'https://joe.com']'
'fulfill.save'

Thanks

**Comment by ayazahmadtarar-pikessoft** [comment]
@Trimakas  thansk worked for me you save my day
