### ISSUE TITLE
Automatically fulfill the order‘s line items - suggestion to update docs

### ISSUE THREAD

**Issue by Trimakas** [Shopify/shopify_api#314]
This would have saved me a couple days worth of struggle.. 

What was happening with my shipping and fulfillment mess is that I suggest that users select this:
"Automatically fulfill the order‘s line items."

So the user would have the order automatically processed and shipped out via my custom carrier service.

Well when that happens, Shopify creates a fulfillment for you.. So you CANNOT create another one on top of that.. won't let you.. that was the reason I couldn't create fulfillments and why I was so confused.

So in my testing, I turned that off, and suddenly the orders had no fulfillments, and I could finally create one, and go thru that process, and realize what had been happening all along.. whew, that hurt..

If there could be a warning or something in the documents it would have been a HUGE help..

Just my 2 cents
Todd

**Comment by kevinhughes27** [comment]
This type of feedback should be posted on the API forum. Issues here are for specific issues with the ruby client. Thanks.
