### ISSUE TITLE
Large product save causing timeout error

### ISSUE THREAD

**Issue by JodiKB** [Shopify/shopify_api#322]
I’ve run into an issue where I’m trying to save a product that has many variants and options and it’s causing a timeout error. We are using the ShopifyApi gem which has a 90 second timeout (I believe). If I try to up that I get a gateway timeout error. There are 55 variants with 3 options each as well as images. In a nutshell, I’m finding the product and removing all (but one) variants and options and rebuilding them. Do you know how to workaround this?

Thanks,
Jodi

**Comment by jamiemtdwyer** [comment]
Hey Jodi,

If you're simply trying to remove a variant from the product, I believe you should be able to destroy a product variant by calling:

`ShopifyAPI::Variant.delete(id)`

If you're trying to clone the product, I would suggest creating the product and adding the images in a separate call, perhaps even in batches.

**Comment by JodiKB** [comment]
Thanks for the reply. Maybe if I post my code it will help better illustrate what's happening.

What I'm doing is finding the product by the handle (note: I'm creating the @product_hash from a row in a CSV):
`@product = Shopify::Products.find({ handle: @product_hash['handle']})`

First I remove the variants (except one) like so:
```
var_count = @product.variants.count
@product.variants.each_with_index do |variant, i|
    variant.destroy if i > 0
end
```

Then reset the options:
```
@product.variants.each do |variant|
    variant.option1 = @product_hash['options'][0].blank? ? nil : @product_hash['options'][0]['name']
    variant.option2 = @product_hash['options'][1].blank? ? nil : @product_hash['options'][1]['name']
    variant.option3 = @product_hash['options'][2].blank? ? nil : @product_hash['options'][2]['name']
end
```

Then add all variants/options to the product:
```
variants = []

@product_hash['variants'].each_with_index do |variant, index|
    var = @product.variants[index] || ShopifyAPI::Variant.new

    variants << var

    atts = var.attributes
    atts['compare_at_price']     = variant['compare_at_price']
    atts['fulfillment_service']  = variant['fulfillment_service']
    atts['grams']                = variant['grams']
    atts['inventory_policy']     = variant['inventory_policy']
    atts['inventory_quantity']   = variant['inventory_quantity'].to_i
    atts['option1']              = variant['option1']
    atts['option2']              = variant['option2']
    atts['option3']              = variant['option3']
    atts['price']                = variant['price']
    atts['requires_shipping']    = variant['requires_shipping']
    atts['sku']                  = variant['sku']
    atts['taxable']              = variant['taxable']
end

@product.attributes['variants'] = variants
```

Then add product images:
```
images = []

@product_hash['images'].each do |img_src|
    img = ShopifyAPI::Image.new
    images << img
    img.attributes['src'] = img_src
end

@product.attributes['images'] = images
```

Then save the product:
`@product.save (this causes the timeout)`

After saving the product I make separate calls to add variant images, but I don't even get to that point because the product save fails.

This only happens on one particular product that has 55 variants, otherwise the call works fine.

**Comment by jamiemtdwyer** [comment]
Hey there,

Sorry, I misinterpreted the original question.

I would suspect that the timeout is occurring because you are trying to add so many images in a single call. I would suggest doing a `ShopifyAPI::Image.create` instead of `.new`, as this will perform an API call to create the image and return you the ID.

This will cause you to send a lot more API calls so you'll have to manage your call limit, but you shouldn't run into the timeout issue.

Hope this helps!

**Comment by JodiKB** [comment]
Something like this:

```
img = ShopifyAPI::Image.new
img.attributes['src'] = img_src
img.prefix_options['product_id'] = @product.id
img.save!
```

Seems to work. Do you see anything wrong with that?

**Comment by jamiemtdwyer** [comment]
LGTM 👍  – feel free to re-open this if you run into this issue again.
