### ISSUE TITLE
Product Count by Collection returns all Products

### ISSUE THREAD

**Issue by FLWallace** [Shopify/shopify_api#324]
When I try and get a count of products for a collect, I get a count of all products:

product_count = ShopifyAPI::Product.count(:params => { :collection_id => my_collect_id})
#returns all the products in a store

product_count = ShopifyAPI::Product.count(:params => { :funky_town => 'oh_yeah'})
#returns all the products in a store, instead of throwing error, obviously Product.count just ignores
#all parameters. If I could find where its defined I could fix it.

This is a major bug since many collections can have more than 250 products, and I will need to page through them, without wasting page API calls if there are less than 250, or I have already hit all the pages for products in a collection.

**Comment by jamiemtdwyer** [comment]
Hey FLWallace,

You can determine the number of products belonging to a particular collection with the following syntax:

`product_count = ShopifyAPI::Product.count(:collection_id => your_collect_id)`
