### ISSUE TITLE
Oauth error invalid_request: The Shopify API application does not support oauth 

### ISSUE THREAD

**Issue by amankumarglobussoft** [Shopify/shopify_api#326]
Hello,
I am getting this error 
`Oauth error invalid_request: The Shopify API application does not support oauth `
I have created the api in partner account still I am getting this error.

**Comment by jamiemtdwyer** [comment]
This is because you are using a private application generated from your shop. In order to authenticate with OAuth, you need to have a _public_ application client, generated from your Partner dashboard.
