### ISSUE TITLE
Not able to get draft_order privileges when scope is write_draft_orders, read_draft_orders

### ISSUE THREAD

**Issue by Trimakas** [Shopify/shopify_api#338]
I've included this in my `shopify_app.rb`
` config.scope = "read_orders, read_products, write_products, read_content, write_content, read_themes, write_themes, write_draft_orders, read_draft_orders"`

And installed the app in a test store, but when I go thru the Oauth process I'm not seeing any "draft order" info. Please see the attached screenshot.

And then when I try and create a draft order I get a `ActiveResource::ForbiddenAccess` error.

As a test I found a product with `ShopifyAPI::Product.find(10083980039)` and it worked fine. No issue.

Is something wrong?

![draft](https://cloud.githubusercontent.com/assets/11541268/24005518/9e53f61c-0a3f-11e7-995a-0a0cf79fb10f.jpg)

**Comment by simonoff** [comment]
@Trimakas hello! Can you remember how you fix it? Through private app?

**Comment by Shine18** [comment]
@Trimakas Can you tell us how you fixed it? 
I'm getting the same error.
