### ISSUE TITLE
Cart API missing throttle headers

### ISSUE THREAD

**Issue by orenmazor** [Shopify/shopify_api#342]
@maartenvg @kevinhughes27 hey guys, I know there's a new throttle being rolled out. I don't know what repo to put it in, so imma put it here:

the new cart api throttle looks like its primarily focused on `/cart/add.js`, but the response that comes back doesnt have any api throttling info on it. is it a leaky bucket sort? can there be a header that at least shows count? etc.

thanks

🦄

**Comment by maartenvg** [comment]
Better to ask this in the forums, I'm not 100% sure who's working on this right now, but you'll get more useful eyes on it in the forums.

**Comment by orenmazor** [comment]
tbh the forums are generally a dead end for technical problems but I'll move this there
