### ISSUE TITLE
Cannot create/save new variants

### ISSUE THREAD

**Issue by Eralph** [Shopify/shopify_api#351]
`variant = ShopifyAPI::Variant.new`
`variant.product_id = 1111`
`variant.price = 10`
`variant.sku = 'SKU111'`
`variant.save`

This code does not work and gives error.

`ActiveResource::ResourceNotFound: Failed.  Response code = 404.  Response message = Not Found.`

Is this the right way to create variants and I am just missing something out that's why it is giving me errors? What is the right way?

TIA

**Comment by jamiemtdwyer** [comment]
Does a product with that id exist on your shop?

**Comment by jamiemtdwyer** [comment]
I'm going ahead and closing this – if you still need a hand with this, feel free to re-open.

**Comment by adrianthedev** [comment]
Instead of doing `variant.product_id = 1111` you should do `variant.prefix_options = { product_id: 1111 }`.

I struggled a lot with the exceptionally poor documentation this gem and `shopify_app` gem have.
Thought that these kinds of issues shouldn't arise with companies like Shopify.

**Comment by benbonnet** [comment]
@adrianthedev does not work (anymore?). Same opinion, shopify looks fine from the outside, but in many places, makes things extremely painful
