### ISSUE TITLE
OAuth token scope checking

### ISSUE THREAD

**Issue by kingscott** [Shopify/shopify_api#353]
Just curious if there is a way, apart from the auth flow, where you can check the scopes of a given OAuth token?

I haven't been able to find anything in the API docs; only thing I was able to find was [this](https://help.shopify.com/api/getting-started/authentication/oauth#step-3-confirm-installation), which isn't really applicable anywhere else besides authentication.

**Comment by ShayneP** [comment]
Questions like this are generally best served by our [API Forums](https://ecommerce.shopify.com/c/shopify-apis-and-technology).

There's no way to see which scopes a given token has through Shopify, you'd need to keep track of them on your end.

**Comment by kingscott** [comment]
Good to know, thanks @ShayneP
