### ISSUE TITLE
Variant.all and variants from products do not match up

### ISSUE THREAD

**Issue by shekibobo** [Shopify/shopify_api#361]
I've been seeing a lot of errors, though inconsistent, when looking up a variant by ID. I have a form that sets a `variant_id` pulled from `ShopifyAPI::Product#variants`. However, in some (many?) cases, looking up that variant directly, i.e. `ShopifyAPI::Variant.find(variant_id)` ends up raising a 404 `ActiveResource::NotFound` error. Upon further investigation, I found that `ShopifyAPI::Variant.all` and `ShopifyAPI::Product.all.flat_map { |product| product.variants }` return completely different lists. In my particular case, `ShopifyAPI::Variant.all` shows 50 results, while mapping from the products shows 293 results, and only 26 of them overlap.

Inversely, `ShopifyAPI::Product.all.map(&:id)` and `ShopifyAPI::Variant.all.map(&:product_id).uniq` return different results as well, with the first returning 50 results and the second returning 12, and only 8 overlapping ids.

This is problematic for a number of reasons. I'm inclined to just `flat_map` and filter through products for everything since `Variant` seems to be broken. Any idea what might be causing this mismatch, and where these other products/ids are coming from?

**Comment by jamiemtdwyer** [comment]
By default, the response is limited to 50 resources. For almost every resource, you can specify up to 250 resources (I believe ProductListings support up to 1000) by adding the parameter `limit: 250`. In order to retrieve more than 250 results, you'll need to implement a paging strategy. (e.g. `page: 2`).

That explains why you're seeing a difference in `ShopifyAPI::Product.all.flat_map { |product| product.variants }` (all of the variants for the first 50 products returned) and ShopifyAPI::Variant.all (first 50 product variants). 

As for why `ShopifyAPI::Variant.find(variant_id)` would be failing, I'm not sure. Is it possible that you aren't passing in the correct variant ID or that the variant has been destroyed?

**Comment by shekibobo** [comment]
In my case, it's highly unlikely the variants were destroyed, but they don't seem to exist when I query the `Variant` API for them. The ids passed were pulled from variants listed under the `Product` API and submitted, then we create an order with some of those items, but after that, none of the variants can be found under either API. There is an open issue #337  that says variants get destroyed and recreated instead of updated. Is it possible that creating an order with a variant id would update it in such a way that it ends up with a new variant id?

**Comment by jamiemtdwyer** [comment]
That issue doesn't seem related – creating an order doesn't update a variant in any way except for the inventory quantity, the variant ID shouldn't be affected.

If you can provide a variant ID that was accessible through the Product API, but not through the Variant API, I can take a look a look to see if/when it has been destroyed.

**Comment by shekibobo** [comment]
Maybe I'm doing something wrong:

```ruby
ShopifyAPI::Session.temp(shop.domain, shop.token) { ShopifyAPI::Variant.all(limit: 250) }.count
# => 50
ShopifyAPI::Session.temp(shop.domain, shop.token) { ShopifyAPI::Variant.find(:all, limit: 250) }.count
# => 50
ShopifyAPI::Session.temp(shop.domain, shop.token) { ShopifyAPI::Product.all }.count
# => 50
ShopifyAPI::Session.temp(shop.domain, shop.token) { ShopifyAPI::Product.all(limit: 250) }.count
# => 50
ShopifyAPI::Session.temp(shop.domain, shop.token) { ShopifyAPI::Product.all(limit: 250).flat_map(&:variants) }.count
# => 293
ShopifyAPI::Session.temp(shop.domain, shop.token) { ShopifyAPI::Product.all(limit: 250).flat_map(&:variants).map(&:id) & ShopifyAPI::Variant.all(limit: 293).map(&:id) }.count
=> 26
```

If a variant had been destroyed, would I be able to successfully create an order purchasing that variant id? Because it seems that a some point between showing the variant id filtered through products and submitting it and creating an order, and then searching for that variant ID directly to update its inventory, all variant IDs submitted are no longer available through the `Variant` API while searching directly for those IDs. It doesn't happen every time, only on a few requests, though I'm not sure the proportion at this point.

**Comment by jamiemtdwyer** [comment]
> If a variant had been destroyed, would I be able to successfully create an order purchasing that variant id?

No, this shouldn't be possible – there is validation against variant ID when saving the order in Shopify. You can create a line item with a custom title, price, and quantity; or, a line item can be created with a variant ID and a quantity. If an invalid variant ID is passed here, the validation will fail.

To retrieve more records than the default limit of 50, the syntax is as follows:

```ruby
[15] pry(main)> ShopifyAPI::Variant.find(:all, params: { limit: 250}).count
=> 250
```

or

```ruby
[16] pry(main)> ShopifyAPI::Variant.all(params: {limit: 250 }).count
=> 250
```

To paginate, add the `page` param:

```ruby
ShopifyAPI::Variant.all(params: {limit: 250, page: 2 })
```

Hope this helps!

**Comment by shekibobo** [comment]
That does help, thank you. After doing a bit more debugging and experimenting, it seems that the users where we are seeing this issue have a lot of turnover in their product listing, so variants that previously existed no longer exist at the time of our processing. Thanks for helping debug! Closing the issue.
