### ISSUE TITLE
Getting a 302 from the API, crashing Rails/shopify_api gem

### ISSUE THREAD

**Issue by uschtwill** [Shopify/shopify_api#364]
Crossposted from: https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/getting-a-302-from-the-api-crashing-rails-shopify_api-gem-437558

I am not sure, if we can easily change something on or side to get a "normal" response from Shopify or if the gem needs to handle this better. But since we're pressed on time and we didn't get a response on the Shopify forums yet, I thought I'd ask here as well.

> Hello,
> 
> we are developing a Rails app that needs to pull orders from our Shopify store using the shopify_api gem. This worked like a charm up until recently, when the Shopify API started returning 302 status codes on those requests (~ Friday last week).
> 
> The weird thing is that on the same store, with the same api key and with the same code base, me and my colleague are getting different behaviours. I am getting the 302, while he is getting a 200. For him nothing changed, while for me Rails now returns a 500.
> 
> The only notable difference in his and my setup is that he is located in the Czech Repubic, whereas I am located in Germany. To make the matter more confusing, I used my cell phones hotspot to check from a different IP, but that doesn't change the behaviour at all.
> 
> Google and this forum's search function only turn up conversations and threads from 2013 and older regarding the 302 status code, and it is not listed here either.
> 
> Am I right here or should I file an issue on shopify_api's Github? Any pointers are greatly appreciated.
> 
> Cheers
> Will

**Comment by uschtwill** [comment]
So apparently there is not dedicated tech/API support at Shopify to answer questions like "Under which conditions does the API return a 302?". I wrote our partner manager, but she didn't get back to me yet.

Any ideas, anyone?

**Comment by jamiemtdwyer** [comment]
Can you provide an example request? If you can provide the X-Request-Id, it
will greatly assist in debugging this - failing that, the resource id you
are attempting to fetch would help.

Thanks!

**Comment by jamiemtdwyer** [comment]
If providing the latter, the API key would be helpful as well.

On May 26, 2017 17:20, wrote:

Can you provide an example request? If you can provide the X-Request-Id, it
will greatly assist in debugging this - failing that, the resource id you
are attempting to fetch would help.

Thanks!

On May 25, 2017 06:00, "Wilhelm Uschtrin" <notifications@github.com> wrote:

So apparently there is not dedicated tech/API support at Shopify to answer
questions like "Under which conditions does the API return a 302?". I wrote
our partner manager, but she didn't get back to me yet.

Any ideas, anyone?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Shopify/shopify_api/issues/364#issuecomment-304004273>,
or mute the thread

**Comment by uschtwill** [comment]
Hey Jamie, thanks for your reply. I am unsure on how to get `shopify_api` to log the X-Request-Id. 

And I am quite reluctant to share a whole request including it's response, as it's our live system, besides the fact that curl or Postman are returning 200s anyways. But the endpoint with url parameters we're getting the 302 from is `admin/orders.json?financial_status=paid&fulfillment_status=fulfilled&limit=250&page=1&status=any`. 

I added a new temporary key that has the same behaviour, which is `914f9a18fe0dcc7285175e2a88472c4a`.

I am beginning to suspect that I am monumentally missing something, Postman and curl getting 200s and the Rails app getting 302s (from the same machine), that just doesn't make any sense at all.

**Comment by uschtwill** [comment]
Any news, @jamiemtdwyer?

**Comment by cefigueiredo** [comment]
@jamiemtdwyer can you say if your app has a correct access token? Because 302 status is a status for redirection... and the only redirection I can think is when the app was not authorized yet, and the app is redirected to the shop page to authorize the app and receive the access_token.

**Comment by uschtwill** [comment]
Oh wow. Yes, it did have the correct token. 

But while re-checking that I noticed that I didn't have `storename.myhopify.com` but `shop.ourdomain.com` in the env vars of the app. While in Postman I have `storename.myshopify.com` and so probably does my colleague. I might very well have changed that 1.5 weeks ago, when I was changing out the keys and how the app processes env vars. Or I didn't, I really don't know.

Anyways, it is working now (and I am blushing - this is my blunder of the month). Thanks guys!

**Comment by jamiemtdwyer** [comment]
Hey @uschtwill, I'm digging through the logs but nothing is immediately obvious. It does seem that the credentials aren't getting passed along correct (I'm not seeing any authenticated requests for that key with a 302 response).

**Comment by jamiemtdwyer** [comment]
Just saw your latest response now – if that domain (`shop.ourdomain.com`) is the shop domain defined in Shopify, it should still work but using `shop.myshopify.com` is usually the safest bet.

**Comment by uschtwill** [comment]
I will keep that in mind ...forever. :)

Thanks again!
