### ISSUE TITLE
Web hooks support

### ISSUE THREAD

**Issue by krazedkrish** [Shopify/shopify_api#369]
Hi!

Can I add web hooks using shopify_api? Or will I have to use shopify_app?

**Comment by dgorodnichy** [comment]
For example:

      ShopifyAPI::Session.temp("example.myshopify.com", 'token......') do
        ShopifyAPI::Webhook.create( :topic => 'orders/create', :format  => 'json', :address => "lvh.me/shopify/webhooks/order")
      end

**Comment by krazedkrish** [comment]
Thanks
