### ISSUE TITLE
How to rename options ?

### ISSUE THREAD

**Issue by WaldenStew** [Shopify/shopify_api#371]
Hi, 

I'm trying to rename options for variants with API since a few days and i don't found the solution ...

A shopify employee ( Busfox 👍  ) gives me this code : 

With a PUT request

{
  "product": {
    "options":[
      {
        "name":"Color","position":1,"values":["Rose","Dark Red"]
      },
      {
        "name":"Device","position":1,"values":["iPhone 7","iPhone 7 Plus"]
      }]
  }
}

And  It works when you have an only one option, but if I have two or three options, le name is never changing.

The problem is the key, if i have an only one option and no key, the array is rewrited and it's updating the name, so it works.

But if i have more of one option, i must add a key to my call, like this :

$optionsArray[$key]= array( "name" => $value, "position" => 1, "values" => $optionsValues );
$data = array( 'product' => array( 'options' => $optionsArray));

Any idea to help me ? is it a bug?  or Is it me that has a bug ?

Thx !

**Comment by jamiemtdwyer** [comment]
The repository is intended for support for the Ruby client library gem. General support for the API is provided by the community at the [Shopify forums](https://ecommerce.shopify.com/c/shopify-apis-and-technology).

I would imagine that the issue is in your PHP code.

**Comment by WaldenStew** [comment]
Oh yes.. i'm sorry jamiemtdwyer. 👍
