### ISSUE TITLE
Unexpected behavior when trying to update RecurringApplicationCharge object.

### ISSUE THREAD

**Issue by amorimlucas** [Shopify/shopify_api#382]
I'm trying to update a RecurringApplicationCharge object like so:

```
@rac_def = ShopifyAPI::RecurringApplicationCharge.find(:all).sort_by(&:created_at).reverse.first
@rac_def.trial_days = "7" 
@rac_def.save 
```

But this code returns a 406 Not Acceptable error. What's the right way to update a RecurringApplicationCharge object?

**Comment by jamiemtdwyer** [comment]
It's not possible to update a charge. Creating a new charge automatically cancels the old charge. See the API docs here: https://help.shopify.com/api/reference/recurringapplicationcharge

**Comment by amorimlucas** [comment]
Hey @jamiemtdwyer In the tests it looks like there's a `customize` method:

https://github.com/Shopify/shopify_api/blob/master/test/recurring_application_charge_test.rb#L97

Has it been deprecated then?

**Comment by jamiemtdwyer** [comment]
The customize method only allows the capped_amount to be updated, which reflects the maximum amount of usage charges that can be created.
