### ISSUE TITLE
no implicit conversion of nil into String

### ISSUE THREAD

**Issue by dgorodnichy** [Shopify/shopify_api#383]
Hi, I get error: 
- Parameters: {"code"=>"2....b", "hmac"=>"3....b", "shop"=>"be...co.myshopify.com", "timestamp"=>"1502205649"}
- Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.0ms)
- TypeError (no implicit conversion of nil into String): app/controllers/accounts/shopify_controller.rb:12:in `finalize' config/environments/production.rb:14:in `call'

It happens in this code: 
`token = shopify_session.request_token(params)`

But this is not permanent. How to fix it?

full listing: https://pastebin.com/E3H6TBSk

**Comment by saqib1324** [comment]
I am also facing this issue. How did you resolve it?

**Comment by nwtn** [comment]
@saqib1324 could you provide a stack trace or any additional details?

**Comment by nwtn** [comment]
My best guess is that there’s an issue with what’s being passed into the `params` arg. `request_token` [does things](https://github.com/Shopify/shopify_api/blob/master/lib/shopify_api/session.rb#L100-L119) with these params that assumes they have a certain shape.

**Comment by jmitchtx** [comment]
Could be that your secret token isn't being passed in properly.  This was the case for me and how I found this ticket.  I had a mis-mapping between the .env key for SHOPIFY_API_SECRET_KEY=blah and then trying to use it as ENV[SECRET_KEY'] ... aka nil :D

**Comment by nwtn** [comment]
Closing assuming the above discussion solves this problem. Feel free to re-open if there’s still an issue
