### ISSUE TITLE
2 sign in's required for draft orders

### ISSUE THREAD

**Issue by Trimakas** [Shopify/shopify_api#384]
Is this how it's supposed to work?
This is the use case:

1. User logs in and adds an item to cart
2. User is forwarded to draft order on clicking checkout
3. User has to sign in AGAIN
4. Is then taken to draft order.

Also if I just forward a draft order to a user, and who's user info is already within the draft order, they still have to login to the store.

Thanks
Todd

**Comment by Schenng** [comment]
@Trimakas do you have a shop example for this?

**Comment by ShayneP** [comment]
This repo is reserved for issues with the `shopify_api` gem, this is a question that's probably better suited for support.
