### ISSUE TITLE
Unable to change asset through the API

### ISSUE THREAD

**Issue by amorimlucas** [Shopify/shopify_api#385]
I have an app that generates product images as part of its functionality. I've noticed that some themes have an [img_url](https://help.shopify.com/themes/liquid/filters/url-filters#size-parameters)  that is too small, and the generated image looks blurry. So I want my app to update the product image img_url tags (in the product.liquid file) so they are always "1000x1000".

I'm able to retrieve the asset as [shown here](https://github.com/Shopify/shopify_api/blob/master/test/asset_test.rb), but I haven't found a way to update the asset through the API. Is there a way? Also, is this the recommended way to accomplish what I'm trying to do? Thanks.

**Comment by jamiemtdwyer** [comment]
First you'll need to find the asset by key:

```ruby
asset = ShopifyAsset.find('templates/product.liquid', params: { theme_id: THEME_ID })
```

The `value` attribute of the asset is the contents of the asset file. We can make the substitutions in place and save the asset to the server.

```ruby
asset.value.gsub!("256x256", "1024x1024")
asset.save
# => true
```

Hope this helps.
