### ISSUE TITLE
Create PriceRule Discount

### ISSUE THREAD

**Issue by Talha5** [Shopify/shopify_api#390]
How can i create PriceRule discount?
1. `@last_price_rule = ShopifyAPI::PriceRule.find(4171860875)`
2. `@last_price_rule.discount_codes`
3. Shouldnt i be able to `@last_price_rile.discount_codes.discount_codes(
		  "discount_code": {
		    "code": "15OFFCOLLECTION"
		  }
		)` ?

**Comment by jamiemtdwyer** [comment]
See the following test for example usage:

https://github.com/Shopify/shopify_api/blob/master/test/discount_code_test.rb#L26-L34
