### ISSUE TITLE
topic: "fulfillments/create" not triggered when user manually fulfills multiple orders

### ISSUE THREAD

**Issue by Trimakas** [Shopify/shopify_api#392]
When a user selects multiple orders, and then under the "Bulk Action" button they manually fulfill multiple orders at once the topic: "fulfillments/create" is not being triggered.

Anyone take a look at this please?
here is a link to a screen shot from the users perspective
http://nimb.ws/qJ3eiZ

**Comment by Trimakas** [comment]
It actually happens if you select one or many orders to fulfill. If you fulfill them through the bulk actions this topic is definitely not getting hit.

**Comment by jamiemtdwyer** [comment]
Hey @Trimakas, if you're still experiencing this issue can you send an email to apps@shopify.com? The issues here are reserved for issues solely related to this gem. Thanks.
