### ISSUE TITLE
Order query?

### ISSUE THREAD

**Issue by gamut** [Shopify/shopify_api#393]
This isn't really an issue, per-se, but i've spend days trying to figure it out.  How do you query orders by number using this gem?  I have gotten `Order::all({created_at_min: some_date})` to work, but it appears as though arbitrary queries aren't possible.  Is that true?

The Shopify API docs are of absolutely no help.

**Comment by Yu-coding** [comment]
Hi @mostlydev 
About orders, I want to order by order_number.

```
options = { 
            status: 'any',
            limit: 50,
            page: 1,
            order: "order_number ASC",
            fields: "id,order_number,created_at,email,financial_status,fulfillment_status,total_price,customer"
        }

ShopifyAPI::Order.find :all, params: options

```

But this seems not working.
Could you please help me to fix?

Thank you.

**Comment by mostlydev** [comment]
This isn't originally my code, but I suggest you look at the Shopify API docs to see what parameters they allow.  This gem is just a wrapper for that API, and the parameters for this kind of request are passed on verbatim.

**Comment by Yu-coding** [comment]
Thank you.
