### ISSUE TITLE
How can I delete customers from the Rails App 

### ISSUE THREAD

**Issue by leonperez1870** [Shopify/shopify_api#394]
Hi,

I'm trying to delete customers from a Rails app using the API gem. The idea is to get the customer's id by searching their email. Then I would proceed to delete that person from the Rails app as well as the Shopify store.

```
shop_url = "https://my.shopify.api.keys.com"
ShopifyAPI::Base.site = shop_url
shop = ShopifyAPI::Shop.current
customer_data = ShopifyAPI::Customer.find(:all).to_json
customers = ActiveSupport::JSON.decode(customer_data)
```
the only way I can get that data is explicitly writing
```
customers[0]['id']['email']
```
is there any way to automate this by searching the email, getting the id and delete the customer with that id?

**Comment by jamiemtdwyer** [comment]
Here's an example of how to accomplish this:

```
results = ShopifyAPI::Customer.find(:all, from: :search, params: { :query => 'email:paul.norman@example.com' } )

results.first.destroy
```

Note that you will receive a `422` error from the API if this customer has a non-zero amount of orders. This is intentional.

The `Customer.search` method isn't working correctly right now – I'll try to fix that and close this when that work is completed.

**Comment by jamiemtdwyer** [comment]
Sorry, the `Customer.search` method appears to be working fine.

Here's how you would perform the requested action using `Customer.search`:

```ruby
results = ShopifyAPI::Customer.search({ query: 'email:paul.norman@example.com' })
results.first.destroy
```
