### ISSUE TITLE
POST /admin/themes.json limited to 20MB!?

### ISSUE THREAD

**Issue by guillelopez** [Shopify/shopify_api#395]
Is there any reason why: POST /admin/themes.json is limited to 20MB when through the /admin the limit is 50MB?

![image](https://user-images.githubusercontent.com/428680/32438190-df2137e6-c2e9-11e7-954b-bdbd8288b2ea.png)

When uploading a 28MB zip is returning a status code of `422` and saying that the limit is 20MB: `Src may not be used to fetch a file bigger than 20MB`

**Comment by 0ptimusrhyme** [comment]
Being handled in a developer support ticket, closing.

**Comment by guillelopez** [comment]
This issue hasn't been fixed yet.

**Comment by 0ptimusrhyme** [comment]
Hey @guillelopez, we decided against increasing the limit for API requests. You can read the thread here: https://github.com/Shopify/shopify/pull/140021

Sorry for not posting that here earlier!

**Comment by guillelopez** [comment]
That's a problem for us as we get themes uploaded through the /admin and export those through the API to other stores. Now and then we are finding that the process can't be run because the file size limit difference. I hope you guys reconsider this position in the future. Thanks.
