### ISSUE TITLE
POST /admin/orders.json sends a notification email moreover having send_receipt = false

### ISSUE THREAD

**Issue by guillelopez** [Shopify/shopify_api#396]
Following the documentation at https://help.shopify.com/api/reference/order#create, it's clear that a new order created through the API should not send a notification email to the order's customer.

But I found that if the private app created for providing access to the API has the `Allow this app to access your storefront data using the Storefront API` checkbox activated, then that email is being sent no matter what:

<img width="684" alt="screen shot 2017-11-15 at 12 12 03 am" src="https://user-images.githubusercontent.com/428680/32810125-e885ae32-c999-11e7-8465-b1a39c61c6b2.png">

**Comment by 0ptimusrhyme** [comment]
Being handled in a developer support ticket, closing.
