### ISSUE TITLE
List individual tax rates when refunding shipping charges

### ISSUE THREAD

**Issue by jbtwo** [Shopify/shopify_api#397]
------

[This](https://app.shopify.com/services/internal/shops/11530428) plus merchant reached out with a feature request/feedback about the API. The request they're making seems reasonable enough (with my basic understanding of the API), so I'm passing it along. Please let me know if there's something the merchant hasn't considered or if there's a reason this request isn't reasonable, and I will pass that back.

### Problem

When refunding charges for shipping through the API, the response currently shows the `total_tax` amount that was refunded. The merchant would like to be able to see the individual tax rates that make up this `total_tax` amount

### Examples

Using [this](https://shop-v3-live-usd.myshopify.com/admin/orders/6197544071) order as an example:

Under `shipping_lines`, you're able to see the individual taxes that were charged on shipping. In this case `New York State Tax` and `New York County Tax`:

![https://screenshot.click/23-01-ycgqt-j6x1l.jpg](https://screenshot.click/23-01-ycgqt-j6x1l.jpg)

When refunding a shipping charge however, these individual rates aren't available. The merchant pointed out they can only see the total tax refunded on shipping under `order_adjustments`, but this doesn't include the individual tax rates that were refunded:

[![alt](https://screenshot.click/23-03-q3wdn-2yrwz.jpg)](https://screenshot.click/23-03-q3wdn-2yrwz.jpg)

### More Information

[Zendesk Ticket here](https://shopify.zendesk.com/agent/tickets/7375986)

**Comment by jamiemtdwyer** [comment]
Hey Justin, please open this in the core Shopify repository and tag the Shipping team.

**Comment by clement911** [comment]
@jamiemtdwyer where is the core repo located?

**Comment by jamiemtdwyer** [comment]
Hey Clement, Shopify itself isn't open source :)

**Comment by clement911** [comment]
Thought so. Didnt realize the op was a shopifier..
