### ISSUE TITLE
Product resource not found error handling

### ISSUE THREAD

**Issue by ButsAndCats** [Shopify/shopify_api#398]
I have created a proxy to return product json that uses.
`product = shopify.Product.find(product_id)` however one of the products was deleted and now my app returns a 500 error when searching for this product.

What is the best way to handle this response?

**Comment by jamiemtdwyer** [comment]
If a resource is not found, a 404 error should be returned by the API. A 500 error should only be returned in exceptional cases. Your app should implement exception handling for that specific exception (`ActiveResource::ResourceNotFound`). 

If anyone is able to replicate this, can they please re-open and provide a log from Shopify?
