### ISSUE TITLE
Scope to provide access to the Scripts resource?

### ISSUE THREAD

**Issue by lastobelus** [Shopify/shopify_api#402]
Is there a way that I can access the Cart Scripts resource for a Shopify Plus client?

We're doing some interesting stuff with cart scripts for which we want to build out some UI in a custom app.

I can see the resource in a browser when logged in to the admin, with `https://mysite.myshopify.com/admin/scripts.json`.

I've tried `read_scripts`, `write_scripts`, `read_cart_scripts`, `write_cart_scripts` for scopes but none worked.

The script editor app seems to work through the scopes mechanism, does it have a magic pass?

**Comment by jamiemtdwyer** [comment]
Shopify Scripts are not accessible to API clients. If they are ever made API accessible, they will be added this this gem as a supported resource.
