### ISSUE TITLE
How to check for new orders and change in payment status?

### ISSUE THREAD

**Issue by lowercase00** [Shopify/shopify_api#404]
Would it be possible for you guys to provide a sample of getting new orders and checking changes in payment status for existing orders?
Thanks!

**Comment by jamiemtdwyer** [comment]
> checking changes in payment status for existing orders?

This action is not supported through the [API](https://help.shopify.com/api/reference).

> getting new orders

You can retrieve orders that were created after a particular date and time using the `created_at_min` query parameter when querying for Orders.

`ShopifyAPI::Order.find(:all, params: {created_at_min: "2017-01-24T16:15:47-04:00"})`

**Comment by benbonnet** [comment]
approximately getting it working with the following :
`(Time.zone.now - 20.minutes).strftime('%FT%T%:z')``

is there a cleaner way to format the date to apply on `created_at_min` or `updated_at_min` ?
