### ISSUE TITLE
SocketError: Failed to open TCP connection to .myshopify.com:443

### ISSUE THREAD

**Issue by laddhadhiraj** [Shopify/shopify_api#405]
This gem working well from last two days before but suddenly it starts giving an error to me at Heroku server and still working well on my local system.

I am getting error 

> SocketError: Failed to open TCP connection to .myshopify.com:443 (getaddrinfo: Name or service not known)

I am trying to run code in heroku run rails c  in this below flow but getting above error

 

> shop_url = "https://#{ENV['SHOPIFY_API_KEY']}:#{ENV['SHOPIFY_PASSWORD']}@#{ENV['SHOPIFY_SHOP_NAME']}.myshopify.com/admin"
ShopifyAPI::Base.site = shop_url
ShopifyAPI::Shop.current

**Comment by jamiemtdwyer** [comment]
Sounds like your environment variables aren't set up correctly. Can you
check to make sure that they are all set?

**Comment by laddhadhiraj** [comment]
We have setup environment variable also it print well url
> ShopifyAPI::Base.site 
When I do puts but just give issue when calling function.

**Comment by laddhadhiraj** [comment]
I am also sharing my terminal log to you so it will easy to debug issue 

`
dhirajladdha$ heroku run rails c
Running rails c on ⬢ xxxx-xxx... up, run.1251 (Hobby)
[Scout] [12/29/17 05:44:57 +0000 run.1251 (4)] WARN : Agent attempting to load in interactive mode. Not starting agent
Loading production environment (Rails 5.1.4)
irb(main):001:0> ShopifyAPI::Base.site
=> #<URI::HTTPS https://xxxx:xxxx@.myshopify.com/admin>
irb(main):002:0> ShopifyAPI::Shop.current
SocketError: Failed to open TCP connection to .myshopify.com:443 (getaddrinfo: Name or service not known)
	from (irb):2
irb(main):003:0> 
irb(main):004:0* 
`

**Comment by laddhadhiraj** [comment]
Also I just see it's giving build error  https://travis-ci.org/Shopify/shopify_api

**Comment by jamiemtdwyer** [comment]
It seems pretty clear to me from your log that ENV['SHOPIFY_SHOP_NAME'] is
returning nil.

Are you using the wrong environment variable here perhaps?

**Comment by laddhadhiraj** [comment]
It worked sorry ... It was a mistake  by my side. Thanks for looking into it.
