### ISSUE TITLE
Not able to access discount resource

### ISSUE THREAD

**Issue by rinkudas** [Shopify/shopify_api#406]
I can access discount/discount_code APIs using my own call but using the GEM I am not able to access it. Discount code is no more under shopify plus. What am I missing here?

**Comment by jamiemtdwyer** [comment]
Have you tried looking at the tests?

https://github.com/Shopify/shopify_api/blob/master/test/discount_test.rb
https://github.com/Shopify/shopify_api/blob/master/test/discount_code_test.rb

Can you share the exact error you're receiving so that we can help you troubleshoot further?

**Comment by rinkudas** [comment]
Thanks :). It is resolved.
