### ISSUE TITLE
CollectionListing API returns nil even there are lots of collections

### ISSUE THREAD

**Issue by bstarr322** [Shopify/shopify_api#421]
Hi,
I'm using `ShopifyAPI::CollectionListing` but I cannot get the result(e.g: products_ids)

`ShopifyAPI::CollectionListing.find(:all)` returns `nil`
But `ShopifyAPI::Collect.find(:all).count` returns `50`

Did I miss anything?

**Comment by ShayneP** [comment]
The `CollectionListing` resource is available to Sales Channel SDK applications only. If you're looking for product ID's in a specific collection you should be hitting the `Collect` endpoint, and using the specific collection ID as a parameter in the request.
