### ISSUE TITLE
location.inventory_levels

### ISSUE THREAD

**Issue by tomlober** [Shopify/shopify_api#424]
Hello,

Firstly, thanks for you work ;)

We have a problem when retrieve location and get inventory_levels foreach location.
ActiveResource::ForbiddenAccess (Failed.  Response code = 403.  Response message = Forbidden.)

gems/shopify_api-4.11.0/lib/shopify_api/resources/location.rb:5:in `inventory_levels'

Our scope config :
config.scope = "read_orders, read_products, read_fulfillments, write_fulfillments"

Have you got the same problem ? How can we fix it 

All the best,

ToM

**Comment by jamiemtdwyer** [comment]
Hey Tom,

I believe you'll need to add the OAuth scope for read_inventory.

At some point in the future, I believe that all apps with read_products will inherit that scope but I'm not sure if that work has been completed yet.

This feature is only intended to be used as a beta as of right now.

Cheers.

**Comment by tomlober** [comment]
Hello,

Thanks for your reply.
With read_inventory scope it works fine 👍 

We implement this because we read inventory_quantity in productVariant Deprecated on this link -->  https://help.shopify.com/api/reference/product_variant

So we must get inventory_quantity by inventory_level API.

What do you think about this.

All the best,

ToM

**Comment by jamiemtdwyer** [comment]
Hey Tom,

You're right – `inventory_quantity` will be removed from the Variant model and going forward, you must determine inventory quantity using the InventoryLevel API.

Hope this helps.
