### ISSUE TITLE
New location_id requirement

### ISSUE THREAD

**Issue by amorimlucas** [Shopify/shopify_api#427]
Is there a way to just leave this field null when creating a fulfillment? What if your app doesn't have any locations?

**Comment by jtgrenz** [comment]
No, it must be included. All fulfillment services automatically have a "location" associated with them.  If a store has 2 locations, "Downtown" and "Warehouse" and they install a fulfillment service, "Shipco", they will now have 3 locations , "Downtown", "Warehouse" and "Shipco". 

Inventory managed by the merchant can now be stocked in multiple locations, but any inventory controlled by a fulfillment service can _only_ be stocked at the fulfillment service "location". 

Checkout the api docs for a better explanation https://help.shopify.com/api/reference/inventory/inventorylevel
