### ISSUE TITLE
ShopifyAPI::InventoryLevel 403 error

### ISSUE THREAD

**Issue by CodeBrotha** [Shopify/shopify_api#428]
I'm trying to get inventory levels for a specific `inventory_item_id` but nothing seems to be working.

I have updated the gem to 4.1.1 and added the scope `read_inventory` to my app's scopes.

So far I have tried the following in my attempt to get the InventoryLevel item:

`params = { inventory_item_ids: [the_id]`

`ShopifyAPI::InventoryLevel.find(:all, params: params)`

I also tried `ShopifyAPI::InventoryLevel.find(inventory_item_id: the_id)`

And just to see if it would work I also tried `ShopifyAPI::InventoryLevel.find(the_id)`

What am I doing wrong here?

**Comment by raecoo** [comment]
`params = {inventory_item_ids: [the-id].join(","), location_ids: [the-location-id].join(",")}
ShopifyAPI::InventoryLevel.find(:all, params: params)`
works good. @CodeBrotha

**Comment by joesasson** [comment]
@raecoo saved me hours, Thanks!

**Comment by jonathanahern** [comment]
@raecoo This doesn't seem to work anymore because it appears Shopify is limiting responses to 50? So if I search for an ID outside of the initial 50 it returns an empty array. If I search for an item within the first 50 you get a proper response. Is this correct and how do I fix this?

**Comment by raecoo** [comment]
the default `limit` is 50, you can change it to 250, or apply the pagination for your query to get the right response.

**Comment by raecoo** [comment]
> @raecoo This doesn't seem to work anymore because it appears Shopify is limiting responses to 50? So if I search for an ID outside of the initial 50 it returns an empty array. If I search for an item within the first 50 you get a proper response. Is this correct and how do I fix this?

the default limit is 50, you can change it to 250, or apply the pagination for your query to get the right response.
