### ISSUE TITLE
ShopifyAPI::Collect.where does not accept Arrays

### ISSUE THREAD

**Issue by saadasif** [Shopify/shopify_api#429]
ActiveResource is supposed to mirror Active record. If I make a call like `Collect.where(product_id: [1,2,3])`, this works. But when I make the call `ShopifyAPI::Collect.where(product_id: [1,2,3])`, this does not work. I get back `ActiveResource::BadRequest: Failed.  Response code = 400.  Response message = Bad Request`. When I prod into the error I see that the request returns: `{\"errors\":{\"collection_id\":\"expected Array to be a id\"}}`.

It seems like array handling to make queries like `x IN (1, 2, 3)` is not handled correctly. Can someone take a look?

**Comment by jamiemtdwyer** [comment]
The Shopify API doesn't support this, so this is not a bug with the client library but rather a feature gap in the API itself.
