### ISSUE TITLE
Error while doing ShopifyAPI::RecurringApplicationCharge.create()

### ISSUE THREAD

**Issue by Ranjithkumar** [Shopify/shopify_api#43]
Hi

I am getting this error while creating recurring payment and while calling `ShopifyAPI::RecurringApplicationCharge.current`

`undefined method 'path' for nil:NilClass`

Awaiting for your reply

Thanks
Ranjith

**Comment by prasanthrubyist** [comment]
Hi all, I'm new to shopify I build an Shopify rails 4  App, I've no idea how to configure **ShopifyAPI::RecurringApplicationCharge** in my public app please help me

**Comment by jamiemtdwyer** [comment]
Prasanth,

Can you please create a new issue with more detail? Please include the a description of the problem, any error messages you are encountering as well as steps to replicate the issue.

**Comment by benhoxie** [comment]
I am also receiving this error today! In my case it was because the session wasn't activated (thanks @maartenvg ).  Ensuring this was run fixed it:
```
@session = ShopifyAPI::Session.new(@store_name, @token)
 ShopifyAPI::Base.activate_session(@session)
```
