### ISSUE TITLE
find product/collection by tags

### ISSUE THREAD

**Issue by farooqch11** [Shopify/shopify_api#432]
ShopifyAPI::Product.find(:all, params: { tags: "mytag" })
ShopifyAPI::Product.find(:all, params: { tag: "mytag" })
not working, it return me first page instead of products with only this tag.

although its working if you are logged in as admin into store

admin/products/search.json?query=tag:dafault

**Comment by jtgrenz** [comment]
@farooqch11 by default the shopify api will only return 50 records at a time. Most resources will have a limit param you can pass allowing up to 250 per call. 

`ShopifyAPI::Product.find(:all, params:{ tags: 'mytag', limit: 250})` will yield the first 250 records tagged with 'mytag'.  If you have over 250 record matching that, you will need to make a second call. 

`ShopifyAPI::Product.find(:all, params:{ tags: 'mytag', limit: 250, page: 2})` will give you the _second_ 250 records. if you have more than 500, you will need to go to page 3 and so on. 

I'm closing this issue as there doesn't seem to be anything to be an issue with the library itself.

**Comment by farooqch11** [comment]
the issue i found out that tags params doesn’t exist in shopify api,  it return all products instead of only with tags.

**Comment by Yu-coding** [comment]
@farooqch11, you are right.
But you can find products by tag using GraphQL.
