### ISSUE TITLE
ApplicationCharge return_url being called with OPTIONS method instead of GET method

### ISSUE THREAD

**Issue by guillelopez** [Shopify/shopify_api#433]
Hi, I am finding this weird issue:

[My app](https://apps.shopify.com/duplicate-store) is running without any issues, charging merchants perfectly, but now and then I get some customers who can't complete the payment. I've been researching and what I found is that in some cases the app is getting calls to the `ApplicationCharge` `return_url` with the method `OPTIONS` instead of a normal `GET`:

```
2018-05-18T14:52:14.663415+00:00 app[web.1]: I, [2018-05-18T14:52:14.663287 #4]  INFO -- : [6f8fd5ce-a8fe-4cfa-8148-b4f4ff0b5b57] Started OPTIONS "/charged?charge_id=323747920" for 158.106.220.226 at 2018-05-18 14:52:14 +0000
2018-05-18T14:52:14.668782+00:00 app[web.1]: F, [2018-05-18T14:52:14.668707 #4] FATAL -- : [6f8fd5ce-a8fe-4cfa-8148-b4f4ff0b5b57] ActionController::RoutingError (No route matches [OPTIONS] "/charged"):
```

**Comment by guillelopez** [comment]
I am finding this same behavior in another app. Here when clicking on "Decline charge".

````
HTTP Requests
-------------

OPTIONS /charges/collected                     422 Unprocessable Entity
POST    /batches                               200 OK
````

**Comment by LukaszWiktor** [comment]
This gem may help: https://github.com/cyu/rack-cors

**Comment by jtgrenz** [comment]
Sounds like a cors error to me and rack-cors should help. Closing as I don't believe this is a shopify_api issue.

**Comment by guillelopez** [comment]
It was not a cors error, it was Shopify not making the proper callback (I guess after all the React refactoring in the /admin). Now it seems to be fixed.

Shopify should provide a better way to app developers to notify about this kind of issues.
