### ISSUE TITLE
undefined method 'path' for nil:NilClass

### ISSUE THREAD

**Issue by jegacs** [Shopify/shopify_api#434]
Hi, I'm a Shopify App newbie and I am kinda getting used to the environment, 
I'm getting an error I cannot solve. 
When Im trying to list my webhooks in the console I get this message: 

`irb(main):009:0> ShopifyAPI::Webhook.all]`

`Traceback (most recent call last):
        1: from (irb):9
NoMethodError (undefined method `path' for nil:NilClass)` 

I have this set up in my shopify_app.rb 

`  config.webhooks = [
    {topic: 'products/update', address: 'https://d4546faf.ngrok.io/webhooks/products_update', format: 'json'},
  ]`
 
Any ideas on how I could fix this problem?

**Comment by jtgrenz** [comment]
@jegacs shopify_app and shopify_api are related, but not connected tools. Calling `ShopifyAPI::Webhook.all` should return an array of all the webhooks on a store, even those not associated with your app. The response should be the same as [https://yourstore.myshopify.com/admin/webhooks.json](https://shopify.com/admin/webhooks.json)

If you opened up irb and required `shopify_api` but didn't establish a connection first, then `ShopifyAPI::Webhooks.all` would give you an undefined method 'path' error as you described. 


If you wanna play with the api in the commandline but don't want to fuss with reconencting everytime, try saving a config file with https://github.com/Shopify/shopify_cli and using `shopify-cli console <storename>`

**Comment by alexmamonchik** [comment]
I had the same issue but solution is `activate_session ` step before api call. https://community.shopify.com/c/Shopify-APIs-SDKs/How-do-I-get-the-current-shop-in-my-app/m-p/408021
