### ISSUE TITLE
Orders with refunds containg discounts starting with integers throws "wrong constant name" exception

### ISSUE THREAD

**Issue by hengwoon** [Shopify/shopify_api#436]
When an order has a refund that includes a discount code starting with an integer, any attempts to retrieve that error will throw the 'wrong constant name' exception.

Here's a sample refunds hash returned for an order (with some fields removed)

```
{
  "refunds": [
          {
                "id": 20714848300,
                "transactions": [
                    {
                        "receipt": {
                            "card_transaction": {
                                "status": "paid",
                                "amount": "98.87",
                                "currency": "NZD"
                            },
                            "card_details": {
                                "type": "Visa"
                            },
                            "discount_details": {
                                "2FOR99": {
                                    "code": "2FOR99",
                                    "amount": "32.00"
                                }
                            }
                        },
                    }
                ]
          }
      ]
}
```

Activeresource will try and find_or_create the resource for "2FOR99", which is not a valid constant and an exception is thrown.

Stack trace:
```
NameError: wrong constant name 2FOR99
  from active_resource/base.rb:1571:in `const_defined?'
  from active_resource/base.rb:1571:in `find_or_create_resource_for'
  from active_resource/base.rb:1415:in `block in load'
  from active_resource/base.rb:1401:in `each'
  from active_resource/base.rb:1401:in `load'
  from active_resource/base.rb:1135:in `initialize'
  from active_resource/base.rb:1416:in `new'
  from active_resource/base.rb:1416:in `block in load'
  from active_resource/base.rb:1401:in `each'
  from active_resource/base.rb:1401:in `load'
  from active_resource/base.rb:1135:in `initialize'
  from active_resource/base.rb:1416:in `new'
  from active_resource/base.rb:1416:in `block in load'
  from active_resource/base.rb:1401:in `each'
  from active_resource/base.rb:1401:in `load'
  from active_resource/base.rb:1135:in `initialize'
  from active_resource/base.rb:1409:in `new'
  from active_resource/base.rb:1409:in `block (2 levels) in load'
  from active_resource/base.rb:1406:in `map'
  from active_resource/base.rb:1406:in `block in load'
  from active_resource/base.rb:1401:in `each'
  from active_resource/base.rb:1401:in `load'
  from active_resource/base.rb:1135:in `initialize'
  from active_resource/base.rb:1062:in `new'
  from active_resource/base.rb:1062:in `instantiate_record'
  from active_resource/base.rb:1058:in `block in instantiate_collection'
  from active_resource/collection.rb:68:in `block in collect!'
  from active_resource/collection.rb:8:in `each'
  from active_resource/collection.rb:8:in `each'
  from active_resource/collection.rb:68:in `collect!'
  from active_resource/base.rb:1058:in `instantiate_collection'
  from active_resource/base.rb:1027:in `find_every'
  from active_resource/base.rb:934:in `find'
```

**Comment by jtgrenz** [comment]
@hengwoon Im not able to replicate this issue. Could you share what your code looks like that caused this error? Based on the title history of the issue I'm assuming `ShopifyAPI::Order.find {order_id}` is returning an error if the order has a discount code of `2for99`, but when I do that I get back a normal resource object.

**Comment by hengwoon** [comment]
@jtgrenz The issue happens when there is a Refund for the order, and that refund includes a discount code.

The JSON I posted is part of an order, and the refunds hash contains a transaction with the receipt that has "discount_details" which is a hash keyed by the discount code. When Activeresource tries to convert that hash into a resource, it fails when it tries to check for the constant '2FOR99', which isn't a valid constant.

**Comment by jtgrenz** [comment]
What gateway are you testing with? The contents of the receipt object varies depending on the gateway used.

**Comment by hengwoon** [comment]
This is happening for some users (store owners) of our app. Our app searches for orders and displays them to the user. 

I can take this offline and send you the exact details of the store and the ID of the order. I truncated the order details since it's a real order and for privacy reasons.

In any case, returning a dynamic key of a hash breaks activeresource. I don't think there are any other places where the API response contains keys that are dynamic and could begin with  an integer. I pasted the stack trace above, and we're using Rails 5, so the corresponding line that's breaking is : https://github.com/rails/activeresource/blob/rails-5-1/lib/active_resource/base.rb#L1567

**Comment by hengwoon** [comment]
Any update on this?

**Comment by jtgrenz** [comment]
Because the receipt object is the data returned from the gateway or was generated by the orders create api, we can't really be certain what will come back. We could just remove entries with bad keys or prepend them with a valid character, but I didn't think either of those solutions was a good idea. The issue here lies with how active resource handles response data so I decided to fix it there. I'm just waiting on final review from the Rails core team. The review seems to have stalled for a week so I bumped it yesterday to get some movement on it. 

Once that merges (🤞), ActiveResource will generate a class of `UnnamedResource` for any key that is invalid, but all the data will still be intact. Every other key would be created the same as always. 

So for the above example the key of "2FOR99" would be `Refunds::Transactions::Receipt::DiscountDetails::UnnamedResource` should you need to access it. And if you don't it doesn't matter because everything else will be business as usual and you won't get a NameError.

I'll update this issue once its fixed.

**Comment by jtgrenz** [comment]
@hengwoon the rails core team just merged this into master. A new version release should be coming soon which will require no update to the gem (the gemspec looks for any version of ActiveResource >= 3.0.0). 

If you want to take advantage of the update right away, you should be able to add `gem 'activeresource', :git => 'https://github.com/rails/activeresource.git'` to your gem file, just keep in mind thats going to get you all the newest pre-release additions to ActiveResource.

**Comment by hengwoon** [comment]
Hey Jon,

I saw the PR, and thank you for getting that in. There are a lot of others out there that would appreciate this fix, and our Shopify merchants will definitely be pleased.

We're probably going to wait till ActiveResource releases a new version instead of pointing to master.

Thanks again for your help in this.

**Comment by ClearMarble** [comment]
Sorry to jump on and bump this older issue, but I just started getting this exact error too...except with regular orders coming in via the orders/create webhook. Everything was fine until someone generated a discount code starting with an integer...but when it's used this error occurs and stops my whole order_create job from running.

Could you give some more detail on the recommended solution here? Is it still to add the line above to my gemfile to get pre-release additions to ActiveResource? 

Apologies if it's obvious, I'm still a bit of a Rails and Shopify App noob.

**Comment by jtgrenz** [comment]
@ClearMarble until there a version bump on the ActiveResource gem point to master or forking the repo is your best bet. I know some developers have temporarily forked active_resource at version 5.0.0 and just applied that one commit or have forked master as it is currently and are using that as a locked in version 

Pointing to master is not a super great idea since its always bleeding edge, but a fork of it will let you lock AR to a state you're comfortable with.  I really thought there would have been a minor bump by now to be honest. I'll see if I can maybe pester one of the maintainers to see if we can get a minor bump.

**Comment by jtgrenz** [comment]
@ClearMarble @hengwoon ActiveResource version 5.1.0 has been released. https://github.com/rails/activeresource/releases/tag/v5.1.0 so you can bump to the latest version of the ActiveResoruce gem. 

@jamiemtdwyer Should we bump the gemspec from `s.add_runtime_dependency("activeresource", ">= 3.0.0")` to `s.add_runtime_dependency("activeresource", ">= 5.1.0")`? Allowing older versions of AR will still cause developers to run into this issue. I don't think its common, but it does obviously happen. Any reason we shouldn't bump that you can think of?

**Comment by jamiemtdwyer** [comment]
To be honest, I'm not sure why we are supporting so many versions of AR, but I think it might be to ensure that the gem plays nicely in apps with older versions of Rails. Is it possible/feasible to upgrade to AR 5 in a Rails 4 app?

**Comment by edavis10** [comment]
Ran into this bug today with a store with a customer using a discount code starting with `1ES[...]`

Upgraded `activeresource` from 5.0.0 to 5.1.0 fixed it.
