### ISSUE TITLE
Uninstall app from a shop using the API

### ISSUE THREAD

**Issue by mksm** [Shopify/shopify_api#438]
https://help.shopify.com/api/getting-started/authentication/oauth/uninstalling-applications

Could this be supported?

**Comment by jamiemtdwyer** [comment]
Hey @mksm, I just added this in the linked PR.

If you use bundler, you can follow [this guide](https://bundler.io/guides/git.html) to pull the changes into your application. Otherwise, you'll need to wait for the next stable release.
