### ISSUE TITLE
Can't interact with webhooks

### ISSUE THREAD

**Issue by mbajur** [Shopify/shopify_api#453]
Hello!

I'm trying t use `shopify_api` gem to manipulate webhooks used by my shop. I verified if my setup works fine and i can confirm that i can, for example, list all my products or orders.

However, for some reason, i can't do anything with webhooks. Let's say i want to list all my webhooks (which are set in the shop admin so i should get some results):

```
ShopifyAPI::Webhook.all
 => nil
```

Also, when i want to create a new webhook:

```
ShopifyAPI::Webhook.create(topic: 'orders/create', address: 'https://public-address-of-my-endpoint', format: :json)
```

it throws:

> ActiveResource::ResourceNotFound: Failed.  Response code = 404.  Response message = Not Found.

Am i doing something wrong in here? Thanks in advance for any clues.

**Comment by 0ptimusrhyme** [comment]
Webhooks are scoped to the API clients that created them, and that doesn't exclude those created in the admin. You will have to have created that resource to see it.

**Comment by mbajur** [comment]
@0ptimusrhyme can i extract that header somehow from the `ShopifyAPI::Webhook.create` ?

**Comment by mbajur** [comment]
Ok, i forgot to add the `/admin` suffix at the end of my shop url. Sorry for confusion.
