### ISSUE TITLE
variant depreciations violated if calling update_attribute or update_attributes on a product or variant 

### ISSUE THREAD

**Issue by meshane** [Shopify/shopify_api#454]
It appears that calling update_attribute or update_attributes on a product or variant will send the whole body of the resource or nested resource in the api call. (See http://api.rubyonrails.org/v3.2.6/classes/ActiveResource/Base.html#method-i-update_attribute and verified looking at the resulting api calls.) This means that inventory_quantity and old_inventory_quantity are included on the variant in the api call. If I understand Jordan's recent announcement post https://ecommerce.shopify.com/c/api-announcements/t/updated-deadline-breaking-changes-to-product-variant-fulfillment-and-refund-apis-527356, this would cause apps to get pulled from the app store on August 1.

**Comment by mhulet** [comment]
This may be related to an issue I'm currently dealing with. I can't simply `save` a product anymore. Here is the response body:

_Write requests to inventory_quantity and inventory_quantity_adjustment are no longer supported. Please use the Inventory Levels API._

```
> p = ShopifyAPI::Product.find(1315545120831)
> p.save
ActiveResource::BadRequest: Failed.  Response code = 400.  Response message = Bad Request.
	from (irb):10
```

I have updated to gem version 4.12.0 but error remains.

**Comment by piyushghevariya** [comment]
update_attribute or update_attributesare no more working for Product and Variant. This is because of  inventory_quantity is deprecated. from 1st August this issue will be affected in apps which contains update call. let us provide the proper solution for this issue.

  `shopifyVariant = ShopifyAPI::Variant.find(12359561117730)
   shopifyVariant.update_attribute(price: 111)`

This will give 400 Bad Request Error: https://prnt.sc/k5koad

**Comment by meshane** [comment]
I can't explain why you guys are getting 400 errors. I'm not seeing that yet. Maybe down the road. Someone from Shopify told me they are hoping to allow these fields as long as they don't attempt to mutate the value. In the mean time I wrote this monkeypatch for my own branch that I'm using to avoid this issue. I'm not planning on submitting this as a pull request because I think the right solution is for Shopify to allow those fields for now rather than force unsuspecting apps to suddenly update their gem. But anyway, here's the monkey patch in case anyone finds it useful.

`module ShopifyAPI
  class Variant
    before_update :clear_inventory_updates

    private
    def clear_inventory_updates
      self.attributes.except!(:inventory_quantity, :old_inventory_quantity)
    end
  end

  class Product
    before_update :clear_inventory_updates

    private
    def clear_inventory_updates
      self.variants.each do |api_variant|
        api_variant.send(:clear_inventory_updates)
      end
    end
  end
end`

**Comment by jamiemtdwyer** [comment]
The reason that some folks are seeing a 4** error and others are not is because the deprecation is currently only applied to API clients created after a certain date (~ July 1st).

We're aware of this issue and are currently working on a solution – thanks for bearing with us.
