### ISSUE TITLE
ActiveResource::BadRequest: Failed.  Response code = 400. when updating records

### ISSUE THREAD

**Issue by joelim01** [Shopify/shopify_api#456]
I have a brand new store where I have created a private app and given it full access via the API permissions. I am able to generate new products via the example code in the readme:
```
# Create a new product
new_product = ShopifyAPI::Product.new
new_product.title = "Burton Custom Freestlye 151"
new_product.product_type = "Snowboard"
new_product.vendor = "Burton"
new_product.save
```
When I attempt to update a product, however, I receive the following error:
```
[16] pry(main)> p = Product.first
=> #<ShopifyAPI::Product:0x000055b9d5a96bb0
 @attributes=
  {"id"=>1814108962934,
   "title"=>"\"Banjo on the Mountain: Wade Mainer’s First 100 Years”  by Dick Spottswood",
... etc etc
[17] pry(main)> p.save
ActiveResource::BadRequest: Failed.  Response code = 400.  Response message = Bad Request.
from /home/ubuntu/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activeresource-5.0.0/lib/active_resource/connection.rb:148:in `handle_response'
[18] pry(main)>
```
I have replicated the issue on a different computer and with a different store. Postman requests to the same store for the same edits are working fine.

Can someone please confirm a working combination of Ruby, Rails, shopify_api and ActiveResource so that I can confirm this isn't caused by a version conflict? I am currently running Ruby 2.4.2, ActiveResource 5.0.0, Rails 5.2.0, and shopify_api 4.12.0. I have tried dropping back to Ruby 2.2.2 with ActiveResource 4.1 and shopify_api 4.11.0 but I have had the same issue.

Given the path for the CURL request (/admin/variants/16508087992438.json), I found the following odd:
```
[9] pry(main)> Variant.collection_path(id: 16508087992438)
=> "/admin/variants.json?id=16508087992438"
```
Can someone please confirm that this is correct?

Thanks!

**Comment by mhulet** [comment]
This may be the same as issue https://github.com/Shopify/shopify_api/issues/454.
