### ISSUE TITLE
Abadoned Checkouts never receive returned rates from Shopify.

### ISSUE THREAD

**Issue by YourWishes** [Shopify/shopify_api#457]
Having an issue with a custom carrier's rates not managing to return back to Shopify when using an abandoned checkout link. I've tried asking a few places to get a response and was pointed here, for further reading you can have a look at the forum post here; https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/carrier-service-and-abandoned-checkout-stuck-forever-528036

To reiterate, the issue starts when a customer loads an abandoned checkout link, it will go to the shipping page and send a request to Shopify to fetch the shipping rates, and then as normal Shopify sends the request to our custom app to get the rates.

Our app does its thing and then returns the rates as normal back to Shopify, and at this point we're having some issues. One in every 25 or so abandoned checkouts never receive the rates back from Shopify, and the client browser gets stuck in the fetching rates page indefinitely.

It's pretty random as to when this happens, so it's difficult to replicate, although I managed to get all the data from the last time this happened so I'll share it now to try and help

Here's our apps logs showing the received request, as well as the data, and what it returned. For privacy's sake I've had to use ##'s to replace certain bits of text, but as far as I know these don't make a difference.
https://pastebin.com/MxkJn1rM

Screenshot (from left to right) Showing the network traffic, the view the clients browser would see, and the server console, showing the rate was returned. Many details have been blurred for privacy and security reasons.
![image](https://user-images.githubusercontent.com/14732069/42795215-7921e8e2-89c6-11e8-8bcb-9c13a0e2cd93.png)

Another one, different products, different address and different rate returned:
![image](https://user-images.githubusercontent.com/14732069/42795309-e80c865e-89c6-11e8-8048-9e7d5e749f3e.png)

After a while the client's browser will 403 for sending too many requests:
![image](https://user-images.githubusercontent.com/14732069/42795377-4b1e853a-89c7-11e8-8634-cea20cc99d91.png)

Directly loading the exact url that is being constantly fetched via ajax will return a completely empty page, no body contents at all.

Any further information I can provide feel free to contact me.
Thanks in advance,
Dominic

**Comment by YourWishes** [comment]
Update, I have been requested by Shopify Support to provide some more information as this still hasn't been resolved, I am weary of doing so since this is real customer data, but I'm at the end of the chain and need to get this resolved.

**Additional Information**
API Key: 58b7eed22e4fcea126d7e826ac3525cf


I have attached 
[html_dump.zip](https://github.com/Shopify/shopify_api/files/2395561/html_dump.zip)
of a complete browser savepage of the checkout during the checkout of the issue abadoned checkout for this test (post apps loading etc). It is a custom checkout.liquid but should not affect shipping.

See this screenshot for a view of an abandoned checkout issue happening, I have attached some of the logs below. These infinite requests will continue until the browser starts to receive 403's from Shopify due to too many requests (which should never happen, since the shipping requests shouldn't last more than a few seconds?)
![image](https://user-images.githubusercontent.com/14732069/45732845-781e6280-bc21-11e8-8954-8a41af4f2163.png)

Here's the 
[Browser Requests.har](https://github.com/Shopify/shopify_api/files/2395567/Initial.Request.txt) file straight out of Firefox. Note of interest is the response content showing a generic Shopify "Page temporarily unavailable" page.

After the initial requests the client will start receiving constant 403's due to pinging Shopify too much.

It will continue this process forever going back between 403s and 202's.

**Comment by YourWishes** [comment]
To clarify (again since requested by Shopify support) the normal / expected flow is the following:

1. Client loads abandoned checkout link
2. During page load (HTML) Shopify will send a correctly formatted request to the carrier callbacks
3. If client has Javascript enabled, the browser will continuously submit an ajax fetch to shopify, requesting the rates. If they have Javascript disabled the browser will do an automatic refresh after a few seconds (using the older redirect headers)
4. In this time while Shopify waits for a response from the carrier apps, it will respond with 202 responses until either a valid request is received, which will get appended to the native shipping options, or if no response is received before the timeout (around 10 seconds from my testing) 
5. After a valid request has been received from the carrier app, it will cache the response against the checkout
6. it will return the response, formatted, back to the client browser to display as options
7. User selects shipping option and checkout continues as normal.

The behavior we're getting is the following;

1. Client loads abandoned checkout link
2. Page (HTML) Begins loading and submits a request to the carrier app.
3. The browser starts to continuously submits an ajax fetch to Shopify... requesting the rates.
4. The carrier app receives the request, nothing different from a regular request and responds normally.
5. At this point, Shopify SHOULD return the rates to the client, however it never does. Also at this point the client's browser SHOULD realise it hasn't received a rate and show a timeout error, but it never does. Shopify just responds with 202 codes until the cache has been cleared (somewhere within 15 minutes from testing) or the user changes something to force a refresh (e.g. Address 2, company name etc)

Definitely seems the issue is somewhere when attempting to read from Shopify's internal cache, causing it to send a 202.

**Comment by Busfox** [comment]
Hey Dom,

Since your issue is not related to the Shopify_API gem specifically, I've closed this issue. My colleague Annette should have an open dialogue with you via our support tools. She has re-opened your issue in the appropriate internal repository and will keep you in the loop on any updates.

Cheers,
