### ISSUE TITLE
Any way to easily get json?

### ISSUE THREAD

**Issue by softwaregravy** [Shopify/shopify_api#459]
This might be a quirk of ActiveResource, but I'd like to get at the JSON of a response. `as_json` doesn't produce "real" json because it keeps the ActiveResource objects.

e.g. if you have an order response from the API, it looks something like this:
```
#<ShopifyAPI::Order:0x00007ffc6aa12c28 @attributes={"id"=>5528967XXX, ..., 
"line_items"=>[#<ShopifyAPI::LineItem:0x00007ffc6aa10478 @attributes={"id"=>13725533XXXXX, ...}]}
```

calling `as_json` will clean up the top level, but leave the nested classes. You'll get something like this:
```
{"id"=>5528967XXX, ..., "line_items"=>[#<ShopifyAPI::LineItem:0x00007ffc6aa10478 
@attributes={"id"=>13725533XXXXX, ...}]}
```
In this case, I've now serialized the class object complete with object id. Definitely not what I wanted.
I'd really like the `as_json` to be applied recursively, which would produce something like this:
```
{"id"=>5528967XXX, ..., "line_items"=>[{"id"=>13725533XXXXX, ...}]}
```

I've managed to get this in a pretty ugly way -- serialize and re-deserialize the request
```
order = ShopifyAPI::Order.first
JSON.parse(ActiveResource::Formats::JsonFormat.encode(order))
```
Is there a better alternative? Hopefully I'm missing something simple.

**Comment by gavinballard** [comment]
@softwaregravy `JSON.parse(order.to_json)` still requires the dump/parse flow but at least it's more concise.
