### ISSUE TITLE
Redact Requests Still not available?

### ISSUE THREAD

**Issue by itsnasir** [Shopify/shopify_api#461]
Hi there, 

I have an existing app and was trying to integrate redact requests introduced in [GDPR requirements](https://help.shopify.com/en/api/guides/gdpr-resources). As per the documentation, they should be available by August 25, 2018, but when I try to fetch all webhooks, redact topics are not returned.

```
irb(main):038:0> ShopifyAPI::Webhook.all.index_by(&:topic).keys
=> ["app/uninstalled", "carts/update", "collections/create", "collections/delete", "collections/update", "orders/create", "products/create", "products/delete", "products/update"]
```

Any thoughts?

**Comment by 0ptimusrhyme** [comment]
Webhooks are scoped to the API client that created them and I don't believe you're creating these webhook subscriptions with API requests. These are set up by and handled via your partner dashboard.
