### ISSUE TITLE
create_permission_url does not accept state parameter

### ISSUE THREAD

**Issue by drewish** [Shopify/shopify_api#466]
The readme mentions that we should be providing and checking the `state` parameter:

>   * ``state`` – Optional – A randomly selected value provided by your application, which is unique for each authorization request. During the OAuth callback phase, your application must check that this value matches the one you provided during authorization. [This mechanism is important for the security of your application](https://tools.ietf.org/html/rfc6819#section-3.6).

>    * Ensure the provided ``state`` is the same one that your application provided to Shopify during Step 3.

But surprisingly the `create_permission_url` method does not accept a state parameter.

**Comment by juliantrueflynn** [comment]
Following up on this, it would be really nice to add for security reasons.

**Comment by drewish** [comment]
I’m no longer using the gem so someone else would need to take over any changes.
