### ISSUE TITLE
Version 5.0.0 breaking changes notice

### ISSUE THREAD

**Issue by jamiemtdwyer** [Shopify/shopify_api#471]
# Breaking change notice for version 5.0.0
Version 5.0.0 will release this week, which will introduce a backwards incompatible change for the `ShopifyAPI::Checkout` resource. Continue reading for more details.

## Summary
Previously, the `ShopifyAPI::Checkout` resource mapped to the [Abandoned Checkouts](https://help.shopify.com/en/api/reference/orders/abandoned_checkouts) resource in the Shopify Admin API.

As of version 5.0.0, the `ShopifyAPI::Checkout` resource will map to the [Checkout API](https://help.shopify.com/en/api/reference/sales_channels/checkout), which can be used by sales channel applications to create new checkouts.

A new resource, `ShopifyAPI::AbandonedCheckout` will map to the [Abandoned Checkouts API](https://help.shopify.com/en/api/reference/orders/abandoned_checkouts).

## Upgrade instructions
If you are currently using the old `ShopifyAPI::Checkout` resource to access the Abandoned Checkout API and wish to upgrade from 4.x.x (or earlier), you'll need to replace all instances of `ShopifyAPI::Checkout` with `ShopifyAPI::AbandonedCheckout` to continue accessing the Abandoned Checkout API.

## Reference for version 5.0.0
| `shopify_api`                  | Shopify API reference                                                |
|--------------------------------|----------------------------------------------------------------------|
| `ShopifyAPI::Checkout`         | https://help.shopify.com/en/api/reference/sales_channels/checkout   |
| `ShopifyAPI::AbandonedCheckout` | https://help.shopify.com/en/api/reference/orders/abandoned_checkouts |

**Comment by lulessa** [comment]
> `ShopifyAPI::Checkout`	https://help.shopify.com/en/api/reference/sales_channels/checkouts

Correct link: https://help.shopify.com/en/api/reference/sales_channels/checkout

Change to note within the resource: `checkout_url` attribute is now `abandoned_checkout_url`

**Comment by jamiemtdwyer** [comment]
Hey @lulessa, thanks for catching that. I'll update the OP.

What do you mean by this?

> Change to note within the resource: checkout_url attribute is now abandoned_checkout_url

If you are accessing the AbandonedCheckouts API, the attribute was always `abandoned_checkout_url`, as indicated in the documentation. Similarly, if you intend to access the [Checkout API](https://help.shopify.com/en/api/reference/sales_channels/checkout) the attribute is `checkout_url`, as it has always been.
