### ISSUE TITLE
ShopifyAPI::Customer.search returns different search results compared to Shopify custom search via admin

### ISSUE THREAD

**Issue by Jay-Plumb** [Shopify/shopify_api#484]
Hi everyone, 

I am experiencing unexpected results when using the `ShopifyAPI::Customer.search` endpoint to perform search queries within my ruby application. If we perform a search filter query on the Shopify admin page to find all customers that have the same prefix, e.g. `https://store.myshopify.com/admin/customers?query=a-b-c` this returns all matching customers that include the tag `a-b-c:`

My goal was to mimic this behavior within my ruby on rails application. To help others replicate this issue, I will provide steps to follow along.

> Supply the tag `a-b-c:d:e` on two or more Shopify customers for testing purposes. Also, be sure to have an authenticated session before running the following in the rails console (I have provided code snippets below)

First validate that the Shopify admin page returns expected results. For the given Shop that your app runs on, provide the search query for `a-b-c:` e.g. `shop.myshopify.com/admin/customers?query=a-b-c`. This should list the two customers that we setup earlier. 

Now, supply the following on your `Shop` model to have an authenticated session (or use existing code to create a valid session with Shopify):

## Authentication

```ruby
  def new_shopify_session
    ShopifyAPI::Session.new(shopify_domain, shopify_token)
  end
```

```ruby
  def activate_shopify_session
    ShopifyAPI::Base.activate_session(new_shopify_session)
  end
```

Finally, run the following within the rails console:

## Rails console

```ruby
  shop = Shop.first # or whichever shop you are using for you given app
  shop.activate_shopify_session
  query = 'a-b-c:'
  page = 1
  ShopifyAPI::Customer.search(query: query, page: 1, limit: 250).collect(&:id)
```

> If you have more than 250 customers then you will have to also alter the value for `page`

In the above example, no matching results will be found. However, if you modify the query to `a-b` or `a-b-` you will return the ids of the two customers that we setup above.

Given this inconcistency, I am lead to believe that there is an issue with this gem rather than on Shopify. If anyone could shed light on the situation described above I would be very greatful. Equally if anyone believes they have found mistakes in my code examples do call them out. 

Thanks!

> N.B I am using the shopify_api version  `4.11.0` and all later releases (currently on `5.1.0`) do not reference this issue

**Comment by 0ptimusrhyme** [comment]
Closing this for now as it does not directly concern the gem. Again, please feel free to create a support ticket so this can be investigated further on the _Shopify platform_ level.
