### ISSUE TITLE
Product.find failing as of this morning

### ISSUE THREAD

**Issue by jchen123** [Shopify/shopify_api#485]
Has anyone seen this pattern of failure

> ShopifyAPI::Product.find(:all)
NoMethodError: undefined method `path' for nil:NilClass

	from /app/vendor/bundle/ruby/2.2.0/gems/activeresource-3.2.22/lib/active_resource/base.rb:587:in `prefix'
	from /app/vendor/bundle/ruby/2.2.0/gems/activeresource-3.2.22/lib/active_resource/base.rb:597:in `prefix_source'
	from /app/vendor/bundle/ruby/2.2.0/gems/activeresource-3.2.22/lib/active_resource/base.rb:951:in `prefix_parameters'
	from /app/vendor/bundle/ruby/2.2.0/gems/activeresource-3.2.22/lib/active_resource/base.rb:966:in `block in split_options'
	from /app/vendor/bundle/ruby/2.2.0/gems/activeresource-3.2.22/lib/active_resource/base.rb:964:in `each'
	from /app/vendor/bundle/ruby/2.2.0/gems/activeresource-3.2.22/lib/active_resource/base.rb:964:in `split_options'
	from /app/vendor/bundle/ruby/2.2.0/gems/activeresource-3.2.22/lib/active_resource/base.rb:1453:in `split_options'
	from /app/vendor/bundle/ruby/2.2.0/gems/activeresource-3.2.22/lib/active_resource/base.rb:1256:in `load'
	from /app/vendor/bundle/ruby/2.2.0/gems/activeresource-3.2.22/lib/active_resource/base.rb:1006:in `initialize'
	from /app/vendor/bundle/ruby/2.2.0/gems/activeresource-3.2.22/lib/active_resource/base.rb:1272:in `new'
	from /app/vendor/bundle/ruby/2.2.0/gems/activeresource-3.2.22/lib/active_resource/base.rb:1272:in `block (2 levels) in load'
	from /app/vendor/bundle/ruby/2.2.0/gems/activeresource-3.2.22/lib/active_resource/base.rb:1269:in `map'
	from /app/vendor/bundle/ruby/2.2.0/gems/activeresource-3.2.22/lib/active_resource/base.rb:1269:in `block in load'
	from /app/vendor/bundle/ruby/2.2.0/gems/activeresource-3.2.22/lib/active_resource/base.rb:1264:in `each'
	from /app/vendor/bundle/ruby/2.2.0/gems/activeresource-3.2.22/lib/active_resource/base.rb:1264:in `load'
	from /app/vendor/bundle/ruby/2.2.0/gems/activeresource-3.2.22/lib/active_resource/base.rb:1006:in `initialize'
It seems to have started failing today.

**Comment by sebastyuiop** [comment]
I am seeing the exact same issue, just started happening. Please let me know if you figure out what the cause of the problem is. I'm also looking into it so will report back.

**Comment by sebastyuiop** [comment]
@jchen123 we've managed to figure out the issue. We are using an older version of the gem. Updating the code based on the following commit fixed it for us: https://github.com/Shopify/shopify_api/commit/bf30a216d0e95455dc62ca6f6ee5b909d8665110#diff-a10d97818183c1ece6a29c9702b22e62

**Comment by woods** [comment]
It looks like this breaks any apps that are still running on shopify_app 6.x, since that major version locks shopify_api to ~> 4.0.2:

https://github.com/Shopify/shopify_app/blob/91779932f3bbb1d755bbf1f23b31c3e3de3e6d5e/shopify_app.gemspec

@sebastyuiop how did you work around this? It sounds like you were able to somehow incorporate that change without doing a major upgrade of your shopify app/api gems. Is that correct?

**Comment by woods** [comment]
Hmm. For anyone still running on shopify_app 6.x, they're probably still on Rails 4. Unfortunately, shopify_app 7.x [dropped support for Rails 4](https://github.com/Shopify/shopify_app/pull/417) and requires Rails 5.

I'm all in favor of deprecation and planned obsolescence. But this morning's update causes quite a cascading series of forced upgrades for apps that worked yesterday!

**Comment by jchen123** [comment]
@woods same boat as you. i'm confused as to what exactly broke today though. they didn't announce any API changes, but it must be something about the API response that breaks the older gems.

**Comment by sebastyuiop** [comment]
@woods we just added that line of code to our old version of the gem. No issues so far with it. 

It does sound to me like something had to have changed at Shopify’s end. We haven’t updated the Shopify App or Shopify API gem.

**Comment by woods** [comment]
Great to know, thank you @sebastyuiop! We'll fork the gem and make a similar quick fix.

**Comment by sebastyuiop** [comment]
No worries @woods. We actually spent half the day removing the Shopify API gem from our app then figured it was just this line of code. Fun!

**Comment by jchen123** [comment]
thanks @sebastyuiop @woods confirmed that fork and patch resolves the issue for now. hopefully others can contribute here if anything changes on shopify's end

**Comment by eapache** [comment]
Hey folks, we didn't intend to pull the old version out from under people like this - we thought it would keep working through the recent changes. We're also investigating on our end, but If anybody can pinpoint what in the response is causing this issue (and why) that would be very helpful.

**Comment by jchen123** [comment]
From what I can piece together so far the issue occurs when simply calling a .find call which is based off activerecord (I used Product.find(:all) as the example ).  Since the patch that @sebastyuiop pointed out is the breaking change, that must mean that check_prefix_options was being called with null options somehow within the new API response, whereas before it somehow was not.  I'm not super familiar with the inner workings of activerecord but perhaps it has to do with the removal of an endpoint that previously existed and its disappearance created the nil options?

**Comment by sebastyuiop** [comment]
Looking at the API gem code I couldn't really figure it out. Something about the response has to be different but without seeing the before and after response side by side it is hard to tell.

For us Product.find and Variant.find were both throwing errors, however Order.find worked as normal. 

Reverting to manually calling the API worked fine so it must be a combination of the API response being different and the gem not being able to parse the changes correctly.

**Comment by eapache** [comment]
We have a working hypothesis and are rolling back a specific change right now. If the issue goes away in ~20 minutes then we were right.

**Comment by sebastyuiop** [comment]
Just tried with the pre-patched code and it appears to be working correctly again :-)

**Comment by woods** [comment]
Thank you, @eapache for determining the root cause and rolling it back! We really appreciate Shopify's support for the legacy major versions -- it'd be a major headache for us to upgrade. Thanks again.
