### ISSUE TITLE
Should I make a PR for Gift card adjustment?

### ISSUE THREAD

**Issue by joallard** [Shopify/shopify_api#503]
I found myself needing a resource for Gift card adjustments and so I fashioned the following:

```ruby
module ShopifyAPI
  class GiftCardAdjustment < Base
    include Metafields
    include DisablePrefixCheck

    conditional_prefix :gift_card

    def self.element_name
      "adjustment"
    end

    def self.create(**params)
      raise ArgumentError, "No :gift_card_id provided." unless params[:gift_card_id]
      super
    end
  end
end
```

Would it be useful for me to comb this into a PR?

**Comment by joallard** [comment]
That sounds right to me. Thanks!

**Comment by sachingevariya** [comment]
Hello @joallard 
I am trying to implement GiftCardAdjustment API. Is it worked for you? Have you done any PR for the same?

Thanks

**Comment by joallard** [comment]
@sachingevariya I have not made a PR, but the above workaround worked fine if I recall correctly

**Comment by sachingevariya** [comment]
Ok, thanks. Let me try.

**Comment by sachingevariya** [comment]
Yes. It helped me. Thanks to @joallard
