### ISSUE TITLE
ShopifyAPI::Fulfillment.find is returning 404 errors at random

### ISSUE THREAD

**Issue by Trimakas** [Shopify/shopify_api#508]
I have a set of order_ids and fulfillment ids that if I run automatically it fails, if I run them manually it works fine. 

I'm getting these errors when running automatically.

!ruby/exception:ActiveResource::ResourceNotFound
response: !ruby/object:Net::HTTPNotFound
  http_version: '1.1'
  code: '404'
  message: Not Found
  header:
    server:
    - nginx
    date:
    - Thu, 08 Nov 2018 20:29:45 GMT

These ids are consistently failing:
order_id 666093125722 and fulfillment_id 646399623258
order_id 634662387787 and fulfillment_id 613720424523
order_id 650217291837 and fulfillment_id 623466971197
order_id 632075747410 and fulfillment_id 606951899218
order_id 650693541949 and fulfillment_id 623960031293
order_id 650693541949 and fulfillment_id 623960031293
order_id 650727456829 and fulfillment_id 623983362109
order_id 634662387787 and fulfillment_id 613720424523
order_id 666093125722 and fulfillment_id 646399623258
order_id 632075747410 and fulfillment_id 606951899218
order_id 634662387787 and fulfillment_id 613720424523
order_id 634662387787 and fulfillment_id 613720424523
order_id 650693541949 and fulfillment_id 623960031293
order_id 650693541949 and fulfillment_id 623960031293

**Comment by 0ptimusrhyme** [comment]
None of these orders exist on the shop you're making these requests against. They were either deleted or belong to another shop. This is not a concern specific to the shopify_api gem, closing.

**Comment by Trimakas** [comment]
No that's not true. You did not read the post. If I `find` these fulfillments manually the gem works fine. Its when they are run in a chain that it fails. and it fails consistently.

**Comment by 0ptimusrhyme** [comment]
Are you certain calling find manually is hitting the same shop? Because again, these orders do not appear to exist on these shops when I look at them myself with these order IDs. Is this replicable on other shops? Can you write a script demonstrating this issue if so? I'll re-open if we can determine this is for sure a shopify_api issue.
