### ISSUE TITLE
GraphQL Client is very slow to instantiate

### ISSUE THREAD

**Issue by flavio-b** [Shopify/shopify_api#510]
Hello there!
I started adding GraphQL to a Rails application, but I noticed that instantiating the client is taking 15 to 20 seconds, just to do:

`client = ShopifyAPI::GraphQL.new`

The regular REST API has been working fine. Is there any reason for this delay and do you know any workaround? Is this client object supposed to be cached somewhere? I'm using `shopify_app@8.3.2` and `shopify_api@5.2.0`, the latest versions.

**Comment by patricklindsay** [comment]
I'm having the same issue... Does the client have to be instantiated for every request or just server boot? I'm going with instantiating after first request then reusing same client.

**Comment by flavio-b** [comment]
@patricklindsay, I guess it depends. 
My understanding is the client is instantiated with the credentials of the shop that made the request, so it can query the data for _that_ shop. But, if you have a single global client object in memory, and it's being shared by multiple threads/requests that can change the credentials, it can cause issues. 

Other than the time, has this been working fine for you?

I've not been using the default GraphQL client since last year, due to it using too much memory. I couldn't really figure out a way to work well with it.
