### ISSUE TITLE
Cannot get secure_compare to return true with hmac and digest

### ISSUE THREAD

**Issue by JamesDullaghan** [Shopify/shopify_api#522]
Issue has been resolved!

**Comment by JamesDullaghan** [comment]
So I should have read deeper into the source, but it looks as though the readme is out of date or is incorrect.

There is a snippet in the readme which states...

```
POST https://SHOP_NAME.myshopify.com/admin/oauth/access_token
with the following parameters:

client_id – Required – The API key for your app
client_secret – Required – The shared secret for your app
code – Required – The token you received in step 3
```

These params aren't the required params according to the source

```
        params = params.except(:signature, :hmac, :action, :controller)
        params.map{|k,v| "#{URI.escape(k.to_s, '&=%')}=#{URI.escape(v.to_s, '&%')}"}.sort.join('&')
```

From initial look, it seems as though we can pass in the request params and the `shopify_api` gem will do what it needs to do 👍

**Comment by andresespinosapc** [comment]
How did you solve it? @JamesDullaghan
