### ISSUE TITLE
Unable to create checkout

### ISSUE THREAD

**Issue by Hamza-Irfan** [Shopify/shopify_api#524]
checkout = ShopifyAPI::Checkout.new(
  :checkout =>{
    :email => "john.smith@example.com",
    :line_items => [{
      :variant_id => '7750876037162',
      :quantity => 1
    }],
    :shipping_address => {
      :first_name => "John",
      :last_name => "Smith",
      :address1 => "126 York St.",
      :city => "Ottawa",
      :province_code => "ON",
      :country_code => "CA",
      :phone => "(123)456-7890",
      :zip => "K1N 5T5"
    }
  }
)
Doing this and in omniauth,
provider :shopify, ENV["shopify_store_api_key"], ENV["shopify_store_api_secret_key"], scope: 'read_products, write_products, read_orders, read_fulfillments, write_fulfillments, read_shipping, write_shipping, write_orders, read_inventory, write_inventory, read_checkouts, write_checkouts'
But not able to create checkout.

**Comment by 0ptimusrhyme** [comment]
We'd need more information to better understand the issue. What response are you getting? Is your app a sales channel? The admin checkout API is reserved for sales channel integrations.

https://help.shopify.com/en/api/reference/sales-channels/checkout

**Comment by Hamza-Irfan** [comment]
Yes my application is a sales channel.
I am getting this response when I try to save above checkout payload
**ActiveResource::ForbiddenAccess: Failed.  Response code = 403.  Response message = Forbidden.**

Can you help me here?
I want to create checkout but unable to do so because of the above error.

**Comment by nwtn** [comment]
Hi @Hamza-Irfan. Did you get this figured out? Usually a 403 error is the result of a missing scope (see https://help.shopify.com/en/api/getting-started/response-status-codes and https://help.shopify.com/en/api/getting-started/authentication/oauth).
