### ISSUE TITLE
Having the variant id's, is it possible to get the variants as an array in one API call?

### ISSUE THREAD

**Issue by rhazegh** [Shopify/shopify_api#526]
I have the id of a couple of `variants` and need to get details for them in one API call. I need to do this to speed up the code to avoid a time-out limit imposed by a third party.

Is is possible to pass an array of the variant id's to the API and get the result as a list of variants?

**Comment by jamiemtdwyer** [comment]
There's no support for this in the REST APIs, but it should be possible in GraphQL using [QueryRoot.nodes](https://help.shopify.com/en/api/graphql-admin-api/reference/queryroot#nodes).

Something like:

```
{
  nodes(ids: ["Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzM5NjYwMDM1ODc=", "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzM5NjYxMzAzMDc="]) {
    ... on Product {
      id
      handle
      availableForSale
    }
  }
}
```

returns:

```
{
  "data": {
    "nodes": [
      {
        "id": "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzM5NjYwMDM1ODc=",
        "handle": "short-sleeve-t-shirt",
        "availableForSale": false
      },
      {
        "id": "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzM5NjYxMzAzMDc=",
        "handle": "zipper-hoodie",
        "availableForSale": false
      }
    ]
  }
}
```

This library uses [graphql-client](https://github.com/github/graphql-client) under the hood to perform GraphQL queries, so you'd need to take a look at the documentation in that repo.

**Comment by rhazegh** [comment]
Thanks for the hint @jamiemtdwyer. Much appreciated. I have the product and variant ids returned from a shopify webhook and they are numbers (e.g. `1980563357766`) and when I use them in a query like this:

```
{
  nodes(ids: ["1980563357766"]) {
    ... on Product {
      id
      handle
    }
  }
}
```

I get an error:

```
{
  "errors": [
    {
      "message": "Invalid global id '1980563357766'",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "fields": [
        "query",
        "nodes",
        "ids"
      ]
    }
  ]
}
```

Not sure what a global id is. Where do I get the **global id**?

**Comment by rhazegh** [comment]
Ah, got it. The following worked:

```
{
  nodes(ids: ["gid://shopify/ProductVariant/20029433870768", "gid://shopify/ProductVariant/20024533866790"]) {
    ... on ProductVariant {
      id
      displayName
      harmonizedSystemCode
    }
  }
}
```
