### ISSUE TITLE
500 Internal Server Error at ShopifyAPI::Shop.current

### ISSUE THREAD

**Issue by appsbysimple** [Shopify/shopify_api#527]
Hi,
I have a Shopify app on Heroku and a point the app stops and throws an 500 Internal Server Error at this line shop = ShopifyAPI::Shop.current
```
def set_shop
    puts "AuthenticatedC set_shop start"
    shop = ShopifyAPI::Shop.current
    puts shop.to_json
    @shop = Shop.find_by(domain: shop.myshopify_domain)
    puts @shop.to_json
    puts "AuthenticatedC set_shop end"
end
```
I found only this on Heroku's logs

```
Started GET "/?hmac=0abf20cfb15a0959366421b5b4f10ce3f750bd4ac17e351a73d20cbb6adf20ec&shop=testingenvir7.myshopify.com&timestamp=1549638130" for 67.215.159.203 at 2019-02-08 15:02:10 +0000
--
Processing by DashboardController#index as HTML
Parameters: {"hmac"=>"0abf20cfb15a0959366421b5b4f10ce3f750bd4ac17e351a73d20cbb6adf20ec", "shop"=>"testingenvir7.myshopify.com", "timestamp"=>"1549638130"}
ApplicationC add_allow_credentials_headers
AuthenticatedC login_again_if_different_shop start
session:{"session_id":"eff2a7f315004283d1a7f748ac6bde13","return_to":"/?hmac=c64611c79a94c317d520f7ffc8a64f166287575f8ccc6520a740fb22510e315c\u0026shop=testingenvir7.myshopify.com\u0026timestamp=1548427908","_csrf_token":"qzo/YzH2Tcuy1a+ylp38iPbby08097EJY7i+sdYxhpk=","shopify":294,"shopify_domain":"testingenvir7.myshopify.com"}
AuthenticatedC shop_session start
AuthenticatedC shop_session no return
[1m[36mShop Load (1.0ms)[0m  [1mSELECT  "shops".* FROM "shops" WHERE "shops"."id" = $1  ORDER BY "shops"."id" ASC LIMIT 1[0m  [["id", 294]]
AuthenticatedC shop_session start
AuthenticatedC shop_session no return
AuthenticatedC login_again_if_different_shop end
AuthenticatedC shop_session start
AuthenticatedC shop_session no return
AuthenticatedC shopify_session is_shop_session
AuthenticatedC shop_session start
AuthenticatedC shop_session no return
AuthenticatedC set_shop start
Completed 500 Internal Server Error in 125ms (ActiveRecord: 1.0ms)
NoMethodError (undefined method `strip' for nil:NilClass):
app/controllers/authenticated_controller.rb:8:in `set_shop'
app/controllers/authenticated_controller.rb:50:in `shopify_session'
```
The interesting thing is, that this doesn't occurs every time. I didn't get it while I was working on the app, I got this error from Shopify's feedback after I submitted the app for listing. 
The strange thing is that I use the "strip" function only at a Service, and I'm sure it didn't entered there. ( there will be rows like "SnippetService *SOMETHING*" after "AuthenticatedC set_shop start"  )

Can you please help me with this? I'm new with Rails and with Shopify and I don't have an idea what sould I do.
Thanks

**UPDATE:**
The problem was that in here `ShopifyAPI::Base.activate_session(shop_session)`
`shop_session.token` was `nil` and that's why I got this error `NoMethodError (undefined method `strip' for nil:NilClass):` .
Logging out (or redirecting to logout) is solving the problem.
My personal solution is if shop_session.token is nil then I do this:
`` fullpage_redirect_to "#{main_app.root_url}/login?shop=#{params[:shop]}" ``

**Comment by Busfox** [comment]
Hey @appsbysimple,

Are you activating the session with `ShopifyAPI::Base.activate_session(session)`? I don't see it in the code you shared. 

I'd recommend giving the readme another read through and posting back if you continue having issues. Our [developer forums](https://community.shopify.com/c/Shopify-APIs-SDKs/bd-p/shopify-apis-and-technology) are a good place to get help from Shopify staff and the Shopify partner community as well. Just remember to accept the correct solution, if given, so that others can gain from the post as well!

**Comment by appsbysimple** [comment]
Hey @Busfox , 
I paste here my AuthenticatedController 
```
class AuthenticatedController < ApplicationController
  before_action :login_again_if_different_shop
  around_filter :shopify_session
  layout 'embedded_app'

  def set_shop
    puts "AuthenticatedC set_shop start"
    shop = ShopifyAPI::Shop.current
    puts shop.to_json
    @shop = Shop.find_by(domain: shop.myshopify_domain)
    puts @shop.to_json
    puts "AuthenticatedC set_shop end"
  end

  def check_billing
    puts "AuthenticatedC check_billing start"
    redirect_to charge_path unless @shop.charge_id?
    puts "AuthenticatedC check_billing end"
  end

  def shop_session
    puts "AuthenticatedC shop_session start"
    return unless session[:shopify]
    puts "AuthenticatedC shop_session no return"
    @shop_session = @shop_session || ShopifyApp::SessionRepository.retrieve(session[:shopify])
  end

  protected

  def login_again_if_different_shop
    puts "AuthenticatedC login_again_if_different_shop start"
    puts "session:" + session.to_json
    if shop_session && params[:shop] && params[:shop].is_a?(String) && shop_session.url != params[:shop]
      session[:shopify] = nil
      session[:shopify_domain] = nil
      fullpage_redirect_to "#{main_app.root_url}/login?shop=#{params[:shop]}"
    end
    puts "AuthenticatedC login_again_if_different_shop end"
  end

  def shopify_session
    if shop_session
      puts "AuthenticatedC shopify_session is_shop_session"
      begin
        ShopifyAPI::Base.activate_session(shop_session)
        yield
      ensure
        ShopifyAPI::Base.clear_session
      end
    else
      puts "AuthenticatedC shopify_session is_not_shop_session"
      if params[:shop] && params[:shop].is_a?(String)
        fullpage_redirect_to "#{main_app.root_url}/login?shop=#{params[:shop]}"
      else
        redirect_to "#{main_app.root_url}"
      end
    end
  end

end
```
I'm activating session with `ShopifyAPI::Base.activate_session(session)` it in shopify_session method and as we can see in the logs it enters there. (I inserted some `puts ""` into the code, so I could understand better how it works).

My question would be that can this Internal Server Error come from calling `ShopifyAPI::Shop.current` or there must be something in my application somewhere what causes this error?

**Comment by Busfox** [comment]
The only place I can see `strip` being called in this gem is here: https://github.com/Shopify/shopify_api/blob/93e9b80456b6f63b13b077da318e8748155a83c9/lib/shopify_api/session.rb#L39.

Are you sure you're instantiating the session properly? I would add a break point before instantiating the session to see if the parameters you are passing are correct. I know the undefined method error you're seeing on `strip` often means you are trying to strip something other than a string.
