### ISSUE TITLE
Getting HTTP 401 after creating token

### ISSUE THREAD

**Issue by yjaspar** [Shopify/shopify_api#528]
Hey guys,

I'm having some problems with the session token generated.
My implementation is simple, when a user setup his account, I generate the session token

```ruby
ShopifyAPI::Session.setup(api_key: ENV['SHOPIFY_API_KEY'], secret: ENV['SHOPIFY_API_SECRET'])
session = ShopifyAPI::Session.new(shopify_params[:shop])
session.request_token(shopify_params)
```

I then store the token in record in my DB.
Right after, I'm instantiating a background worker for treatment (Using this record and so this token). For some reason, these workers are getting 401 from the Shopify API.
I had to put majors `sleep` in my code to get it to work.

Before that, when they crashed and I retried them right away, they were getting processed correctly:
Is there a delay between the time a session token is provided and the session token is useable?

**Comment by Busfox** [comment]
Hi @yjaspar,

Can you confirm that `session.request_token(shopify_params)` is returning an access token and that you're using the token that corresponds with the activate shop session? A 401 means you are using an incorrect access token, or the access token is missing from the request. If you have a request-id you can share, I can take a look in our logs for any info on the specific issue, but I may only see that there was an error. I'd recommend adding a breakpoint or logging in your app right before the request to Shopify to ensure the proper params are being sent in the request. There shouldn't be a delay between session activation and being able to use the session token.

**Comment by yjaspar** [comment]
Hi @Busfox thank you for your information and time.

It appears that my token is generated correctly but my model does not generate the session properly and the issue is coming from my end.

Thank you very much for your clarification, I'll re-open if something does not work properly or I am stuck again.

Cheers
