### ISSUE TITLE
Assigning Images to Variants is Counterintuitive

### ISSUE THREAD

**Issue by bpluhar** [Shopify/shopify_api#530]
Based on the Products & Product Variant API Documentation, in order to assign images to a product's variations you need to upload all the images with the initial product creation, and use the returned image and variant product id's in order to assign the images to the variants.

None of this would be an issue if image assignment was possible via product creation. If you can support metafields on a per-variant basis via the API, I don't understand why it's not possible to support an `"images"` array within the `"variants"` array that contains the URLs of the images we would like to assign to that variant.

It would be less of an issue than it is now if we could simply pass the image URLs to the Products endpoint with just the variant product id's attached to each URL, rather than needing to upload all images initially and store the image id's separately.

I understand splitting up these functions is done for principal sake, but adding support for passing image URLs to update variants via their id's at the least would be extremely beneficial to many.

**Comment by nwtn** [comment]
Just so I understand correctly, this is an issue with the actual API, not this gem; is that correct? If so, I suggest posting this feedback in our [community forums](https://community.shopify.com/c/Shopify-APIs-SDKs/bd-p/shopify-apis-and-technology) so it can get routed to the correct team.
