### ISSUE TITLE
status is not changin for carrier  API

### ISSUE THREAD

**Issue by manishngp** [Shopify/shopify_api#533]
@carrier_services = ShopifyAPI::CarrierService.find(20846608465)
       @carrier_services[:active] = false
       @carrier_services.save

status is not changing of carrier API

**Comment by 0ptimusrhyme** [comment]
Are you meaning to use the carrier service object's getter method?

```rb
@carrier_service = ShopifyAPI::CarrierService.find(20846608465)
@carrier_service.active = false # diff here
@carrier_service.save
```

I was able to have success that way.

**Comment by nwtn** [comment]
closing assuming @0ptimusrhyme’s solution solves this
