### ISSUE TITLE
ShopifyAPI::Report.create returns Forbidden error

### ISSUE THREAD

**Issue by mottalrd** [Shopify/shopify_api#540]
Hello, thank you for this gem

I have created a private app on my shopify test store as a new shopify partner
I have attempted to make this call to try Shopify QL

```ruby
irb(main):016:0> report = ShopifyAPI::Report.create(
irb(main):017:1*       name: 'Custom App Report',
irb(main):018:1*       shopify_ql: 'SHOW quantity_count, total_sales BY product_type, vendor, product_title FROM products SINCE -1m UNTIL -0m ORDER BY total_sales DESC'
irb(main):019:1> )
ActiveResource::ForbiddenAccess (Failed.  Response code = 403.  Response message = Forbidden.)
```

I think I have the full permissions for this app.
The authentication I used is the simple one with username and password as follows
```ruby
shop_url = "https://#{API_KEY}:#{PASSWORD}@#{SHOP_NAME}.myshopify.com/admin"
ShopifyAPI::Base.site = shop_url

```

I think I might need to switch to the OAuth authorisation, could you please confirm?
https://help.shopify.com/en/api/reference/analytics/report#setting-reports-publishing-permissions

Thank you for your help

**Comment by Busfox** [comment]
Hi @mottalrd,

Based on the screenshot you shared initially and the `403` error, I don't think you have the proper permissions to access the reporting API. You'll need to ensure your app has `read_reports` and `write_reports`. Here's what you're looking for when it comes to private apps.

![](https://screenshot.click/2019-03-20_09-56-34.png)

Also, keep in mind the shop you are accessing needs to have the advanced reporting feature (Advanced or Plus plan). 

Feel free to re-open if you need to. Cheers
