### ISSUE TITLE
sku field is empty after saving SKUID from products page.

### ISSUE THREAD

**Issue by Rohit-shopasky** [Shopify/shopify_api#546]
I have created a product ex "Sweet and Sour Lemon relish"  i have given its SKUID "HJ012" But when i call 
`GET /admin/orders.json?fields=created_at,id,name,total-price` 
it shows following JSON 
`{
    "orders": [
        {
            "id": 1015022518350,
            "name": "#1012",
            "line_items": [
                {
                    "id": 2280018280526,
                    "variant_id": 21419445190734,
                    "title": "Chunky Spiced Apple Jam",
                    "quantity": 1,
                    "price": "210.00",
                    "sku": "HJ0002",
                    "variant_title": "",
                    "vendor": "HungryJars",
                    "fulfillment_service": "manual",
                    "product_id": 2405785632846,
                    "requires_shipping": true,
                    "taxable": false,
                    "gift_card": false,
                    "name": "Chunky Spiced Apple Jam",
                    "variant_inventory_management": "shopify",
                    "properties": [],
                    "product_exists": true,
                    "fulfillable_quantity": 1,
                    "grams": 400,
                    "total_discount": "0.00",
                    "fulfillment_status": null,
                    "price_set": {
                        "shop_money": {
                            "amount": "210.00",
                            "currency_code": "INR"
                        },
                        "presentment_money": {
                            "amount": "210.00",
                            "currency_code": "INR"
                        }
                    },
                    "total_discount_set": {
                        "shop_money": {
                            "amount": "0.00",
                            "currency_code": "INR"
                        },
                        "presentment_money": {
                            "amount": "0.00",
                            "currency_code": "INR"
                        }
                    },
                    "discount_allocations": [],
                    "admin_graphql_api_id": "gid://shopify/LineItem/2280018280526",
                    "tax_lines": [
                        {
                            "title": "IGST",
                            "price": "0.00",
                            "rate": 0.12,
                            "price_set": {
                                "shop_money": {
                                    "amount": "0.00",
                                    "currency_code": "INR"
                                },
                                "presentment_money": {
                                    "amount": "0.00",
                                    "currency_code": "INR"
                                }
                            }
                        }
                    ],
                    "origin_location": {
                        "id": 871181615182,
                        "country_code": "IN",
                        "province_code": "DL",
                        "name": "Hungry Jars",
                        "address1": "122, 4th floor,",
                        "address2": "Shahpur Jat",
                        "city": "New Delhi",
                        "zip": "110049"
                    }
                },
                {
                    "id": 2280018313294,
                    "variant_id": 21419537858638,
                    "title": "Mixed Herb Butter",
                    "quantity": 1,
                    "price": "275.00",
                    "sku": "HJ0014",
                    "variant_title": "",
                    "vendor": "HungryJars",
                    "fulfillment_service": "manual",
                    "product_id": 2405810438222,
                    "requires_shipping": true,
                    "taxable": false,
                    "gift_card": false,
                    "name": "Mixed Herb Butter",
                    "variant_inventory_management": "shopify",
                    "properties": [],
                    "product_exists": true,
                    "fulfillable_quantity": 1,
                    "grams": 400,
                    "total_discount": "0.00",
                    "fulfillment_status": null,
                    "price_set": {
                        "shop_money": {
                            "amount": "275.00",
                            "currency_code": "INR"
                        },
                        "presentment_money": {
                            "amount": "275.00",
                            "currency_code": "INR"
                        }
                    },
                    "total_discount_set": {
                        "shop_money": {
                            "amount": "0.00",
                            "currency_code": "INR"
                        },
                        "presentment_money": {
                            "amount": "0.00",
                            "currency_code": "INR"
                        }
                    },
                    "discount_allocations": [],
                    "admin_graphql_api_id": "gid://shopify/LineItem/2280018313294",
                    "tax_lines": [
                        {
                            "title": "IGST",
                            "price": "0.00",
                            "rate": 0.12,
                            "price_set": {
                                "shop_money": {
                                    "amount": "0.00",
                                    "currency_code": "INR"
                                },
                                "presentment_money": {
                                    "amount": "0.00",
                                    "currency_code": "INR"
                                }
                            }
                        }
                    ],
                    "origin_location": {
                        "id": 871181615182,
                        "country_code": "IN",
                        "province_code": "DL",
                        "name": "Hungry Jars",
                        "address1": "122, 4th floor,",
                        "address2": "Shahpur Jat",
                        "city": "New Delhi",
                        "zip": "110049"
                    }
                },
                {
                    "id": 2280018346062,
                    "variant_id": 21419510792270,
                    "title": "Classic Coffee Mix Original",
                    "quantity": 1,
                    "price": "240.00",
                    "sku": "HJ0052",
                    "variant_title": "",
                    "vendor": "HungryJars",
                    "fulfillment_service": "manual",
                    "product_id": 2405796380750,
                    "requires_shipping": true,
                    "taxable": false,
                    "gift_card": false,
                    "name": "Classic Coffee Mix Original",
                    "variant_inventory_management": "shopify",
                    "properties": [],
                    "product_exists": true,
                    "fulfillable_quantity": 1,
                    "grams": 400,
                    "total_discount": "0.00",
                    "fulfillment_status": null,
                    "price_set": {
                        "shop_money": {
                            "amount": "240.00",
                            "currency_code": "INR"
                        },
                        "presentment_money": {
                            "amount": "240.00",
                            "currency_code": "INR"
                        }
                    },
                    "total_discount_set": {
                        "shop_money": {
                            "amount": "0.00",
                            "currency_code": "INR"
                        },
                        "presentment_money": {
                            "amount": "0.00",
                            "currency_code": "INR"
                        }
                    },
                    "discount_allocations": [],
                    "admin_graphql_api_id": "gid://shopify/LineItem/2280018346062",
                    "tax_lines": [
                        {
                            "title": "IGST",
                            "price": "0.00",
                            "rate": 0.12,
                            "price_set": {
                                "shop_money": {
                                    "amount": "0.00",
                                    "currency_code": "INR"
                                },
                                "presentment_money": {
                                    "amount": "0.00",
                                    "currency_code": "INR"
                                }
                            }
                        }
                    ],
                    "origin_location": {
                        "id": 871181615182,
                        "country_code": "IN",
                        "province_code": "DL",
                        "name": "Hungry Jars",
                        "address1": "122, 4th floor,",
                        "address2": "Shahpur Jat",
                        "city": "New Delhi",
                        "zip": "110049"
                    }
                },
                {
                    "id": 2280018378830,
                    "variant_id": 21419523440718,
                    "title": "Hot Chocolate Mix",
                    "quantity": 1,
                    "price": "210.00",
                    "sku": "HJ0026",
                    "variant_title": "",
                    "vendor": "HungryJars",
                    "fulfillment_service": "manual",
                    "product_id": 2405802901582,
                    "requires_shipping": true,
                    "taxable": false,
                    "gift_card": false,
                    "name": "Hot Chocolate Mix",
                    "variant_inventory_management": "shopify",
                    "properties": [],
                    "product_exists": true,
                    "fulfillable_quantity": 1,
                    "grams": 400,
                    "total_discount": "0.00",
                    "fulfillment_status": null,
                    "price_set": {
                        "shop_money": {
                            "amount": "210.00",
                            "currency_code": "INR"
                        },
                        "presentment_money": {
                            "amount": "210.00",
                            "currency_code": "INR"
                        }
                    },
                    "total_discount_set": {
                        "shop_money": {
                            "amount": "0.00",
                            "currency_code": "INR"
                        },
                        "presentment_money": {
                            "amount": "0.00",
                            "currency_code": "INR"
                        }
                    },
                    "discount_allocations": [],
                    "admin_graphql_api_id": "gid://shopify/LineItem/2280018378830",
                    "tax_lines": [
                        {
                            "title": "IGST",
                            "price": "0.00",
                            "rate": 0.12,
                            "price_set": {
                                "shop_money": {
                                    "amount": "0.00",
                                    "currency_code": "INR"
                                },
                                "presentment_money": {
                                    "amount": "0.00",
                                    "currency_code": "INR"
                                }
                            }
                        }
                    ],
                    "origin_location": {
                        "id": 871181615182,
                        "country_code": "IN",
                        "province_code": "DL",
                        "name": "Hungry Jars",
                        "address1": "122, 4th floor,",
                        "address2": "Shahpur Jat",
                        "city": "New Delhi",
                        "zip": "110049"
                    }
                }
            ]
        },
        {
            "id": 1014513565774,
            "name": "#1011",
            "line_items": [
                {
                    "id": 2279011221582,
                    "variant_id": 21555590627406,
                    "title": "Sweet & Sour Lemon Relish",
                    "quantity": 1,
                    "price": "200.00",
                    "sku": "HJ0012",
                    "variant_title": "",
                    "vendor": "Hungry Jars",
                    "fulfillment_service": "manual",
                    "product_id": 2422819913806,
                    "requires_shipping": true,
                    "taxable": false,
                    "gift_card": false,
                    "name": "Sweet & Sour Lemon Relish",
                    "variant_inventory_management": "shopify",
                    "properties": [],
                    "product_exists": true,
                    "fulfillable_quantity": 1,
                    "grams": 400,
                    "total_discount": "0.00",
                    "fulfillment_status": null,
                    "price_set": {
                        "shop_money": {
                            "amount": "200.00",
                            "currency_code": "INR"
                        },
                        "presentment_money": {
                            "amount": "200.00",
                            "currency_code": "INR"
                        }
                    },
                    "total_discount_set": {
                        "shop_money": {
                            "amount": "0.00",
                            "currency_code": "INR"
                        },
                        "presentment_money": {
                            "amount": "0.00",
                            "currency_code": "INR"
                        }
                    },
                    "discount_allocations": [],
                    "admin_graphql_api_id": "gid://shopify/LineItem/2279011221582",
                    "tax_lines": [
                        {
                            "title": "IGST",
                            "price": "0.00",
                            "rate": 0.12,
                            "price_set": {
                                "shop_money": {
                                    "amount": "0.00",
                                    "currency_code": "INR"
                                },
                                "presentment_money": {
                                    "amount": "0.00",
                                    "currency_code": "INR"
                                }
                            }
                        }
                    ],
                    "origin_location": {
                        "id": 871181615182,
                        "country_code": "IN",
                        "province_code": "DL",
                        "name": "Hungry Jars",
                        "address1": "122, 4th floor,",
                        "address2": "Shahpur Jat",
                        "city": "New Delhi",
                        "zip": "110049"
                    }
                }
            ]
        },
        {
            "id": 1009070211150,
            "name": "#1007",
            "line_items": [
                {
                    "id": 2268456157262,
                    "variant_id": 21555590627406,
                    "title": "Sweet & Sour Lemon Relish",
                    "quantity": 2,
                    "price": "200.00",
                    "sku": "",
                    "variant_title": "",
                    "vendor": "Hungry Jars",
                    "fulfillment_service": "manual",
                    "product_id": 2422819913806,
                    "requires_shipping": true,
                    "taxable": false,
                    "gift_card": false,
                    "name": "Sweet & Sour Lemon Relish",
                    "variant_inventory_management": "shopify",
                    "properties": [],
                    "product_exists": true,
                    "fulfillable_quantity": 2,
                    "grams": 400,
                    "total_discount": "0.00",
                    "fulfillment_status": null,
                    "price_set": {
                        "shop_money": {
                            "amount": "200.00",
                            "currency_code": "INR"
                        },
                        "presentment_money": {
                            "amount": "200.00",
                            "currency_code": "INR"
                        }
                    },
                    "total_discount_set": {
                        "shop_money": {
                            "amount": "0.00",
                            "currency_code": "INR"
                        },
                        "presentment_money": {
                            "amount": "0.00",
                            "currency_code": "INR"
                        }
                    },
                    "discount_allocations": [],
                    "admin_graphql_api_id": "gid://shopify/LineItem/2268456157262",
                    "tax_lines": [
                        {
                            "title": "IGST",
                            "price": "0.00",
                            "rate": 0.12,
                            "price_set": {
                                "shop_money": {
                                    "amount": "0.00",
                                    "currency_code": "INR"
                                },
                                "presentment_money": {
                                    "amount": "0.00",
                                    "currency_code": "INR"
                                }
                            }
                        }
                    ],
                    "origin_location": {
                        "id": 871181615182,
                        "country_code": "IN",
                        "province_code": "DL",
                        "name": "Hungry Jars",
                        "address1": "122, 4th floor,",
                        "address2": "Shahpur Jat",
                        "city": "New Delhi",
                        "zip": "110049"
                    },
                    "destination_location": {
                        "id": 882038472782,
                        "country_code": "IN",
                        "province_code": "HR",
                        "name": "Sujata Jain",
                        "address1": "101 / 28 . Silver oaks apartments . DLF city phase 1",
                        "address2": "",
                        "city": "Gurgaon",
                        "zip": "122002"
                    }
                }
            ]
        }
    ]
}`

Check in last order and second last order line items are same. But in last order SKU field is missing

**Comment by nwtn** [comment]
Is this a problem with this gem, or with the API itself? Do you see the same results if you query the API with e.g. Postman?

**Comment by Rohit-shopasky** [comment]
It is the problem with the API. The above JSON result is the output from Postman.

**Comment by nwtn** [comment]
Ok, in that case I’ll close this issue, as this repo is specifically for the shopify_api gem, not the API itself.

Can you instead post about this in the [APIs & SDKs Community forum](https://community.shopify.com/c/Shopify-APIs-SDKs/bd-p/shopify-apis-and-technology)? Folks there should be able to route the issue to the appropriate team.
