### ISSUE TITLE
Dockerize development version

### ISSUE THREAD

**Issue by alaxalves** [Shopify/shopify_api#565]
I'd like to work on a Docker/Docker-compose script to make faster and easier to contribute with  Shopify API.

**Comment by tylerball** [comment]
Hey Álax, we would gladly accept a PR for a Dockerfile if you'd like to write one. We would probably need to use a [ruby-node](https://github.com/Starefossen/docker-ruby-node) image or similar since we're running JS tests in this repo now due to ITP.

**Comment by alaxalves** [comment]
Great @tylerball, I'll work on it!!!
