### ISSUE TITLE
How do I get dispute information

### ISSUE THREAD

**Issue by SaimonL** [Shopify/shopify_api#573]
Using the API how can I get dispute information?

https://help.shopify.com/en/api/reference/shopify_payments/dispute

**Comment by Busfox** [comment]
Hi @SaimonL,

Looking in the codebase of this gem, it doesn't look like the Disputes API is included. We always welcome PRs if you want to add it! In the meantime, I'd recommend using a gem like httparty or rest-client to fetch disputes in your ruby app.

Cheers,
