### ISSUE TITLE
I can't get billing address and shipping address.

### ISSUE THREAD

**Issue by Yu-coding** [Shopify/shopify_api#575]
Hi

I am getting orders using Shopify API.

```
@orders = ShopifyAPI::Order.find(:all, :params => {
                :status => 'any', 
                :limit => 3,
                :created_at_min => @created_at_min,
                :order => "created_at DESC",
})

```
But I can't get billing address and shipping address.
How can I get?

Thanks.

**Comment by Busfox** [comment]
Hi @Yu-coding,

Your code gives me a bad request error when I attempt it. Looking at an order by id returns the billing address and shipping address no problem.

`order = ShopifyAPI::Order.find(#{id})`

Can you give any additional details to help us help you? What is the response you are getting with that call?

**Comment by Yu-coding** [comment]
Hi @Busfox 
Thanks for your reply.

With my code, I could get the order details except for billing address and shipping address.
While I check this order in the store, there was no billing address and shipping address.
Sorry, this was resolved. 

Thanks again.
