### ISSUE TITLE
API to search with multiple filter option.

### ISSUE THREAD

**Issue by eebasadre20** [Shopify/shopify_api#585]
I'm planning to create a custom search bar with filter options that include search by collections, title, product type, vendor, inventory and etc. I'm not sure if there's a search filter API or do I need to call each of the API for those filters?

I have checked also the Graphql API, not sure if this one will work for this?
I'm not planning to use a third-party app. I want to make it flexible of what I need, that's why I'm asking if there's an API for this or a way on how I can implement it.

Any help/idea is much appreciated.

Thanks!

**Comment by Busfox** [comment]
Hi @eebasadre20,

This repo isn't a support channel for general Shopify development questions. I'd recommend asking your question in our [API forums](https://community.shopify.com/c/Shopify-APIs-SDKs/bd-p/shopify-apis-and-technology) or create a ticket through your [partner dashboard.](https://partners.shopify.com/current/support/form)

The product API does not currently have a search endpoint, so you would need to be doing the filtering on your app's side of things or using the index endpoint's filter fields.

https://help.shopify.com/en/api/reference/products/product#index

GraphQL will be quicker if you are trying to render something on the storefront that you pulled from a backend app.
