### ISSUE TITLE
Shopify API not showing all the orders

### ISSUE THREAD

**Issue by ayazahmadtarar-pikessoft** [Shopify/shopify_api#596]
My customer gave me list of orders that were created on shopify store.but when i try to fetch orders using  **ShopifyAPI::Order.find(:all)** its showing only one order.  My system keep track of all the orders that Shopify sent us via webhook on fetching this order via **ShopifyAPI::Order.find(822852649017)** it show error `ActiveResource::ResourceNotFound (Failed.  Response code = 404.  Response message = Not Found.)`

**Comment by Busfox** [comment]
Hey @ayazahmadtarar-pikessoft,

Does your app have `read_all_orders` scope? Without this scope you would be limited to viewing only the past 60 days worth of orders. Orders outside 60 days would return a 404, like with this order. Read about the change here: https://www.shopify.ca/partners/blog/shopify-order-api.

Feel free to reopen this issue if you continue having trouble.

**Comment by illia108** [comment]
Hey @Busfox ,
thank you!
