### ISSUE TITLE
Can't update article template_suffix

### ISSUE THREAD

**Issue by yu-coder** [Shopify/shopify_api#607]
Hi
I can't update **article.template_suffix**
Is it impossible to update?

**Comment by liamgriffin** [comment]
> Hi
> I can't update **article.template_suffix**
> Is it impossible to update?

Hi there @Yu-coding Are you seeing any validation errors when you try to update?

**Comment by Yu-coding** [comment]
There wasn't any error. But I couldn't update **template_suffix** of any **article**.

**Comment by liamgriffin** [comment]
> There wasn't any error. But I couldn't update **template_suffix** of any **article**.

Hi @Yu-coding  I've looked into this a bit closer and currently the *article.template_suffix* cannot be updated, I've flagged this with our team however. But right now, this is expected behaviour.

**Comment by Yu-coding** [comment]
Thanks @liamgriffin 
I appreciate your help.
I will wait for your answers from your team.

**Comment by yu-coder** [comment]
Hi @liamgriffin 
Has your team got the answer?
I saw the template_suffix is not **READ-ONLY** field so I think we can update this field.

**Comment by yu-coder** [comment]
Weird, sometimes I can update **template_suffix** and not.
