### ISSUE TITLE
Cannot use ShopifyAPI::Session with multiple private apps / API keys

### ISSUE THREAD

**Issue by key88sf** [Shopify/shopify_api#612]
We have 3 private apps (NOT partner apps), and a Rails application using the shopify_api gem which needs to make API calls using all 3 of these private apps.

There does not seem to be an easy way to use the `ShopifyAPI::Session.temp() do` syntax with  regular private apps that have API keys + passwords.

What we'd like to do is something like this:
```
ShopifyAPI::Session.temp(shop_url: "https://app1_api_key:app1_password@ourshop.myshopify.com") do
  # some api calls using app1's credentials
end

ShopifyAPI::Session.temp(shop_url: "https://app2_api_key:app2_password@ourshop.myshopify.com") do
  # other api calls using app2's credentials
end
```

Is this possible at all?

**Comment by tylerball** [comment]
Hi, we currently don't support using multiple app credentials with a single app. We would prefer that the app use a single set.

**Comment by zhyhun-ivan** [comment]
Hi, is there any changes on this question, or it's still impossible?

**Comment by key88sf** [comment]
@tanema Any idea if this is possible now? We have real use cases for this -- we have an application which needs to pull data from multiple shopify stores of our clients. Each store has a private app, so we need to be able to use the API against different stores' private apps. Setting a single `ShopifyAPI::Base.site` won't work here.
