### ISSUE TITLE
Relative cursor based pagination across page loads

### ISSUE THREAD

**Issue by dnswus** [Shopify/shopify_api#624]
The old **Page based pagination** will be deprecated in the `2019-10` API version in favor of the **Relative cursor based pagination**. I'm writing a Rails app with this library and have problem navigating products in multiple pages using **Relative cursor based pagination**. The example given using the `fetch_next_page` call only works in the same page load. What is the best way to navigate different pages across multiple page loads?

**Comment by ziaulrehman40** [comment]
How are we supposed to request say 10th page from the API? I am sorry, didn't quiet get how to use this new cursor approach.

**Comment by ziaulrehman40** [comment]
I digged a little more, now i understand we can retrieve next_page_info(which seems like a hash of some sort) and previous_page_info, how are we supposed to use these hashes to query that specific page when lets say user clicks next page button.

Also my first comment stands that if we can query nth page on new api version?

Thanks.

**Comment by ziaulrehman40** [comment]
Please close this, i was able to make it work to fetch next and previous page using `page_info` param. Only issue was i was including other filter params as well while providing the `page_info`, using `httplog` to inspect responses actually displayed error and i was able to fix it by removing those additional param, as they can be provided only on first request.

Though getting nth page is still a mystery. I don't think with latest pagination scheme, that would be possible. But i can think of some usecases where that would help reduce API calls.

**Comment by patricklindsay** [comment]
For anyone coming here looking for a basic example of how to accomplish this;

View:
```
%nav
  %ul.menu.align-center
    %li
      - if @resource_collection.previous_page?
        = link_to "Previous Page", page_info: @resource_collection.previous_page_info
      - else
        %button.button.disabled.clear Previous Page
    %li
      - if @resource_collection.next_page?
        = link_to "Next Page", page_info: @resource_collection.next_page_info
      - else
        %button.button.disabled.clear Next Page
```

Controller:
```
@resource_collection = ShopifyAPI::Product.find(:all, {page_info: params[:page_info]})
```

**Comment by asecondwill** [comment]
This does not seem to work.  On hitting next page, i get same page.  Any clues?

```
  <% if @products.previous_page? %>
        <li class='page-item'>
        <%= link_to "Previous Page", page_info: @products.previous_page_info, class: ' page-link' %>
        </li>
      <% else  %>
        <li class='page-item disabled'>
          <a class="page-link  ">Previous Page</a>
        </li>
      <% end %>

      <% if @products.next_page? %>
        <li class='page-item'>
         <%=  link_to "Next Page", {page_info: @products.next_page_info}, class: ' page-link' %>
         </li>
      <%  else %>
        <li class='page-item disabled'>
          <a class="page-item  ">Next Page</a>
        </li>
      <% end %>
```

**Comment by rezonant** [comment]
Yes it seems this field is being ignored with shopify_api v9.4.0 and api 2020-10 for me as well :-\

**Comment by ziaulrehman40** [comment]
For anyone coming here later on during upgrades etc and wondering where did this param go? And why am i getting `undefined method next_page_info` may refer to [this section](https://github.com/Shopify/shopify-api-ruby/blob/main/docs/usage/rest.md#rest-resource) for updated docs
