### ISSUE TITLE
Create Fulfillment errors with status 406

### ISSUE THREAD

**Issue by abishekrsrikaanth** [Shopify/shopify_api#626]
I am trying to create Fulfillment for my order and the error on the response is status 406. Here is the request I am sending to Shopify 

```
POST /admin/api/2019-07/orders/1706992140348/fulfillments.json
{
  "fulfillment": {
    "location_id": 1551256911932,
    "tracking_number": null,
    "notify_customer": true,
    "line_items": [
      {
        "id": 3792674029628
      }
    ]
  }
}
```

The response back from Shopify is as follows:

```
{
  "response": [    
  ],
  "errors": {
    "status": 406,
    "body": null,
    "exception": [      
    ]
  },
  "body": "",
  "timestamps": [
    null,
    1569968734.468354
  ]
}
```

Here is the request id information for the above request throwing an error

 ```
"X-Request-ID": [
    "f3a93e96-4fec-4e04-9426-a8815a552df1"
  ]
```

Appreciate if someone could suggest what may be the issue with this API call

**Comment by gs-jdudulski** [comment]
@abishekrsrikaanth did you solve that issue?
