### ISSUE TITLE
Cannot update any product/variant attribute on latest API version

### ISSUE THREAD

**Issue by jeffblake** [Shopify/shopify_api#632]
For a simple update like this:

        api_variant = ShopifyAPI::Variant.find(shopify_variant.identifier)
        api_variant.price = correct_price
        api_variant.save!

I receive error:

`Failed. Response code = 400. Response message = Bad Request.: {"error":"Write requests to inventory_quantity and inventory_quantity_adjustment are no longer supported. Please use the Inventory Levels API."}`

On API version `2019-10`

**Comment by tanema** [comment]
Same issue as https://github.com/Shopify/shopify_python_api/issues/347 both have the same issue.  This will hopefully be fixed soon

**Comment by dav** [comment]
FYI, to get around this in ruby:
```
variant.attributes.delete(:inventory_quantity)
variant.attributes.delete(:old_inventory_quantity)
```
See https://community.shopify.com/c/Shopify-APIs-SDKs/400-BadRequest-on-variant-save/m-p/602230/highlight/true#M40797

**Comment by EmmaB** [comment]
We also did a [workaround](https://github.com/Shopify/shopify_api/issues/702#issuecomment-600484260).

**Comment by spadae22** [comment]
I just changed the call to use 2019-07, all works for now. 2019-10, 2020-01 does not, the world is closed so we need the site working..... and 2019-07 ends April 1st
