### ISSUE TITLE
Update address

### ISSUE THREAD

**Issue by illia108** [Shopify/shopify_api#638]
How can I update customer's default address?
I try this:

```
customer = ShopifyAPI::Customer.find(params[:shopifyCustomerId])
    
    if customer
      customer.addresses.each do |address|
        if address.default
          address.first_name = params[:firstName]
          address.save
       end
   end
```

and get - `ActiveResource::ClientError: Failed. Response code = 406. Response message = Not Acceptable.`

**Comment by vixdug** [comment]
Answered in forum: https://community.shopify.com/c/Shopify-APIs-SDKs/ShopifyAPI-gem-Update-address/m-p/603598/highlight/false#M40967
