### ISSUE TITLE
Relative cursor based pagination not working

### ISSUE THREAD

**Issue by mrbme** [Shopify/shopify_api#643]
Hi,

I'm trying to use the following boilerplate code to extract all my shop's products

```
products = ShopifyAPI::Product.find(:all, params: { limit: 50 })
process_products(products)
while products.next_page?
  products = products.fetch_next_page
  process_products(products)
end
```

But when I use it, I get a NoMethodError for "process_products".

I'm using the most recent gem 'shopify_api', '~> 8.0'

Any insight?

**Comment by ShayneP** [comment]
The `process_products` method is just a placeholder for whatever you need to do with your products. This isn't explained at all in the readme, so I don't blame you for running into this. We'll have to update the docs.

In the boilerplate example you lined, you're processing them in batches with some undefined method called `process_products`. If you just want to do something like return every products on the store instead, this is what it would look like :

```
products = ShopifyAPI::Product.find(:all, params: { limit: 50 })
product_list = []
while products.next_page?
  products = products.fetch_next_page
  product_list << products
end
product_list
```

**Comment by mrbme** [comment]
Thanks for the insight @ShayneP ! I'll try it out.

**Comment by priyankadabawala** [comment]
Hey,@ShayneP 

I have implemented the same in my app but it is giving me an error in the **next_page?** and **fetch_next_page** like https://prnt.sc/q95sjp

My Shopify API gem version is "shopify_api (8.0.0)"  
api_version =  '2019-10'
'rails', '~> 5.2.3'
'shopify_app' , '>= 10.0.0'

Any insight?
