### ISSUE TITLE
Order count and order data is wrong

### ISSUE THREAD

**Issue by shekhar098** [Shopify/shopify_api#644]
I am counting order from Monday to  today and below is my sample code. My shopify order count is 2449 and this gives me 2305.

order_count = ShopifyAPI::Order.count({:created_at_min => Time.zone.now.at_beginning_of_week.iso8601, :created_at_max => Time.zone.now.to_date.iso8601, :status => "any"})

**Comment by shekhar098** [comment]
Any update?

**Comment by ShayneP** [comment]
The forums are probably a better place for a question like this, we'll have to look at your specific store and API client. If you go ahead and post the question there and reference this issue, we should be able to sort you out.
