### ISSUE TITLE
Rails 6 Support

### ISSUE THREAD

**Issue by dav** [Shopify/shopify_api#645]
It [appears that Shopify 8.0.0 gem is not compatible with Rails 6.x](https://github.com/Shopify/shopify_api/blame/24d2640c04fead8871097f23f5c1dadd4a9c298f/shopify_api.gemspec#L28).

Is there any plan for when this will be supported?

```
    shopify_api (>= 8.0) was resolved to 8.0.0, which depends on
      activeresource (>= 4.1.0, < 6.0.0) was resolved to 5.1.0, which depends on
        ....
```

**Comment by janklimo** [comment]
I just ran a clean installation and can confirm that you use this with Rails 6 just fine. `activeresource` will resolve to 5.1.0 which is the [latest version](https://rubygems.org/gems/activeresource/versions).
