### ISSUE TITLE
Payouts Query Issue

### ISSUE THREAD

**Issue by fullstackdb** [Shopify/shopify_api#646]
Issue not about this package only, but API in general.

When fetching payouts data getting `access denied` Error. (Either via REST or GraphQL api)

Details:
Store type - development store.
Access scopes - 
App has been granted `read_shopify_payments_payouts` and `read_shopify_payments_disputes`.

In doc mentioned, that for being able to fetch payouts data, your app/token need to be granted `read_shopify_payments` [link](https://help.shopify.com/en/api/graphql-admin-api/reference/object/shopifypaymentsaccount?api[version]=2019-10), but looks like its a typo, as we don’t have such scope [link to the access scopes list](https://help.shopify.com/en/api/getting-started/authentication/oauth/scopes) also when we try to use this scope name in auth process we getting an error,  I assume it means `read_shopify_payments_payouts` scope.

Query:

```
shopifyPaymentsAccount {
      payouts(first: 10) {
        pageInfo {
          hasNextPage
          hasPreviousPage
        }
        edges {
          cursor
          node {
            id
            status
          }
        }
      }
    }
  }
```

Also tried to fetch this data from `shop.shopifyPaymentsAccount`,- facing  the same error.

P.S. Successfully fetching data related to other granted scopes (orders, customers, products)

Will be glad to get help or any ideas ab. this issue.

**Comment by ShayneP** [comment]
This endpoint isn't exposed in GraphQL yet, it's mistakenly exposed in documentation. Thanks for flagging this, we'll have to update the docs.
