### ISSUE TITLE
Variant image assignment issue

### ISSUE THREAD

**Issue by marschattha** [Shopify/shopify_api#649]
Trying to save a variant while only changing the image_id is giving 400 bad request error. The image and variant are of the same product. As you can see in the screenshot below the product id is the same for both image and variant. Can't assign images to variants. This issue persists for 4 days. Is coming up randomly for some products. Any idea of the cause of issue or how to work around it or any help or pointers would be appreciated. No other value is changed, nothing else is touched. Other API calls are working properly.

```
> product = ShopifyAPI::Product.find(4374031728707) => gives correct product

> image = product.images.find{|i| i.id == 13579689558083}
 => #<ShopifyAPI::Image:0x000055ac8bdaf4e8 @attributes={"id"=>13579689558083, "position"=>18, "created_at"=>"2019-12-08T05:57:39-05:00", "updated_at"=>"2019-12-08T05:57:39-05:00", "alt"=>nil, "width"=>1500, "height"=>1500, "src"=>"https://cdn.shopify.com/s/files/1/0064/3422/6243/products/81YMzVfoy5L._SL1500_4734ed82-055a-4316-97e5-1b1a2ca50b38.jpg?v=1575802659", "variant_ids"=>[], "admin_graphql_api_id"=>"gid://shopify/ProductImage/13579689558083"}, @prefix_options={:product_id=>4374031728707}, @persisted=true>

> variant = product.variants.find {|v| v.id == 31267120185411}
 => #<ShopifyAPI::Variant:0x000055ac8bd1f078 @attributes={"id"=>31267120185411, "title"=>"Large-Grey", "price"=>"14.770", "sku"=>"B07P9RZVXF", "position"=>1, "inventory_policy"=>"deny", "compare_at_price"=>nil, "fulfillment_service"=>"manual", "inventory_management"=>"shopify", "option1"=>"Large-Grey", "option2"=>nil, "option3"=>nil, "created_at"=>"2019-12-08T05:57:40-05:00", "updated_at"=>"2019-12-08T05:57:40-05:00", "taxable"=>true, "barcode"=>nil, "grams"=>122, "image_id"=>13579689558083, "weight"=>0.2688, "weight_unit"=>"lb", "inventory_item_id"=>32828621029443, "inventory_quantity"=>3, "old_inventory_quantity"=>3, "requires_shipping"=>true, "admin_graphql_api_id"=>"gid://shopify/ProductVariant/31267120185411"}, @prefix_options={:product_id=>4374031728707}, @persisted=true, @remote_errors=nil, @validation_context=nil, @errors=#<ActiveResource::Errors:0x000055ac8c2eeb98 @base=#<ShopifyAPI::Variant:0x000055ac8bd1f078 ...>, @messages={}, @details={}>> 

> variant.image_id
 => nil 

> variant.image_id = image.id
 => 13579689558083 

> variant.image_id
 => 13579689558083 

> variant.save
Traceback (most recent call last):
        1: from (irb):441
ActiveResource::BadRequest (Failed.  Response code = 400.  Response message = Bad Request.)

> variant.errors.messages
 => {} 
```

![Screenshot from 2019-12-08 16-10-30](https://user-images.githubusercontent.com/49312804/70516953-a6a39880-1b59-11ea-99c9-38671e389315.png)

**Comment by tanema** [comment]
We will have an update to release today possibly that will add more information to 400 errors so hopefully, that will enlighten us what is happening here. Does this only happen intermittently? Does it succeed with the same information on subsequent requests?

**Comment by marschattha** [comment]
No, its pretty much constant, for example I tried a number of times for this same variant and Image combo a number of times during the last few days. Regardless of how many times I tried it it fails. Even my code redoes the failed requests a up to 3 times, they also all fail.

But I did find a work around
```
#given the same variant and image
> new_variant = ShopifyAPI::Variant.new(id: variant.id, image_id: image.id)
> new_variant.save 
 => true
```
And that works. Which is honestly strange. The only thing I can think of is there are additional validations on update that are failing on some of the other attributes, validations which only trigger on update and not create.
