### ISSUE TITLE
Relative cursor based pagination not working 

### ISSUE THREAD

**Issue by priyankadabawala** [Shopify/shopify_api#651]
Hello,

I have implemented a Relative cursor based in my app but it is giving me an error in the next_page? and fetch_next_page like https://prnt.sc/q95sjp

My Shopify API gem version is "shopify_api (8.0.0)"
api_version = '2019-10'
'rails', '~> 5.2.3'
'shopify_app' , '>= 10.0.0'

Any insight?

**Comment by tylerball** [comment]
@garethson @DrewMartin any insight here?

**Comment by DrewMartin** [comment]
When I look at the class of the products in my tests, I see it's an instance of `ShopifyAPI::PaginatedCollection` but yours is an instance of `Shopify::Kaminari::Collection`. It looks like that's another pagination library. Without seeing all your code and poking through it, it looks like it's causing problems when used with the Shopify API

**Comment by priyankadabawala** [comment]
Hey @DrewMartin

Thanks for your insight :)

Yes, 'kaminari','shopify-kaminari' gem is creating an issue. I removed those two gems and rerun the query it's working fine.

But is there any solution that we can use both of them as we are making pagination using those two gems.

It is really helpful if you can.

**Comment by DrewMartin** [comment]
I think that would be something that would have to be done in the `shopify-kaminari` gem as it's built on top of the `shopify-api` gem and is not something built or maintained by us. Just at a glance it seems that it's adding functionality for making paging using `page` param/offset easier, but that's exactly what we've removed. Is there anything else it's adding?

**Comment by priyankadabawala** [comment]
Ok thanks @DrewMartin. I'll contact to shopify-kaminari gem support.
