### ISSUE TITLE
How to add items to cart

### ISSUE THREAD

**Issue by SylarRuby** [Shopify/shopify_api#663]
```ruby
cart = ShopifyAPI::Cart.new
    cart.line_items = [
      {
        quantity: 2,
        variant_id: 31564150800428
      }
 ]

# OR:
cart.quantity = 2
cart.variant_id = 31564150800428

cart.save
```

I got back:

> #<ActiveResource::ClientError: Failed.  Response code = 406.  Response message = Not Acceptable.>

EDIT:

So it turns out I needed a `checkout_id`. Ok, fair enough. Next:

```ruby
checkout = ShopifyAPI::Checkout.create
```

> ActiveResource::ForbiddenAccess: Failed.  Response code = 403.  Response message = Forbidden

I am lost here.

**Comment by marschattha** [comment]
You probably don't have access scopes required. Read this:
https://help.shopify.com/en/api/getting-started/authentication/oauth/scopes

**Comment by SylarRuby** [comment]
Ahh! Thanks.

**Comment by Vagab** [comment]
Running `session[:cart].line_items` gives. I am using API 2020-04. Is there any way to access items of the cart?
`NoMethodError (undefined method `line_items' for #<ShopifyAPI::Cart:0x00007f893e2504a8>)`
