### ISSUE TITLE
Still unsure how to use the new GraphQL client when app uses multiple shops

### ISSUE THREAD

**Issue by tolgap** [Shopify/shopify_api#679]
The new 9.0.0 GraphQL client setup still has me grasping for straws on how to use it when your app has multiple stores.

I think it still assumes that there is a session available at load time. But I can have hundreds of sessions given the number of Shops that I have in my app. These sessions are only activated when the ProxyAPI is being used, so this is determined in runtime.

How would I go about defining my queries, if I have no ShopifyAPI::Base setup at load time?

**Comment by swalkinshaw** [comment]
Hey @tolgap, the new GraphQL client was designed to work in the exact same way with multiple stores as the REST client does. I assume you're already using a process similar to the one detailed in https://github.com/Shopify/shopify_api#getting-started for using shop specific sessions?

If so, that all still applies and`ShopifyAPI::GraphQL.client` uses the current active session.

You mentioned runtime vs load time so maybe you're referring to the initialization process of the client? That's only for creating a client from the local schema file which is not shop specific. So at load time nothing shop specific applies or is needed.

Does this clarify things for you?

**Comment by tolgap** [comment]
@swalkinshaw Thanks for the response.

I went through the PR that introduced the new setup multiple times and I think I figured it out. The `ShopifyAPI::GraphQL.client` call accepts an optional argument for `api_version`:

https://github.com/Shopify/shopify_api/pull/672/files#diff-49a342381a8e9c693123cb5d3ad9fea1R15

If you do not specify this argument, it will look through `ShopifyAPI::Base`, which assumes that there's an activated session.

So If I do this:

```ruby
    FindDraftOrder = ShopifyAPI::GraphQL.client(ShopifyApp.configuration.api_version).parse <<-'GRAPHQL'
      query($id: ID!) {
        draftOrder(id: $id) {
          id
        }
      }
    GRAPHQL
```

it works without having to set a session at load time.

It might be worth explaining this in the docs perhaps?

**Comment by swalkinshaw** [comment]
🤦‍♂ of course that makes more sense now that you're defining queries as constants (which you should according to graphql-client).

I was confused myself at first because `ShopifyAPI::GraphQL.client` uses `ShopifyAPI::Base.headers` when it actually makes the HTTP call but that's all at run time when executing queries.

I'll have to think about this a bit more since that's a valid problem you've brought up. Thanks 👍

**Comment by tolgap** [comment]
If you use my example, everything works fine. So I'm closing this. If you run into this issue, you'll most likely see my example through search results.

**Comment by swalkinshaw** [comment]
@tolgap I was looking into this again to try and come up with a solution but I failed to actually into an issue.

Back to your original questions:

> How would I go about defining my queries, if I have no ShopifyAPI::Base setup at load time?
> If you do not specify this argument, it will look through ShopifyAPI::Base, which assumes that there's an activated session.

I just assumed this was the case as well until I refreshed my memory that `ShopifyAPI::Base` itself isn't tied to a session. Here's an example just running this in a new console without any session:

```ruby
bundle exec pry --gem
[1] pry(main)> ShopifyAPI::Base.api_version.handle
ShopifyAPI::ApiVersion::ApiVersionNotSetError: You must set ShopifyAPI::Base.api_version before making a request.
from /Users/scottwalkinshaw/dev/shopify_api/lib/shopify_api/api_version.rb:187:in `raise_not_set_error'
[2] pry(main)> ShopifyAPI::Base.api_version = '2020-01'
=> "2020-01'"
[3] pry(main)> ShopifyAPI::Base.api_version.handle
=> "2020-01'"
```

`ShopifyAPI::Base.api_version` can always be statically set independent of a session.

It seems a higher-level issue is that `Session` *requires* an `api_version` to be passed in. It might make sense for that to be optional and use `ShopifyAPI::Base.api_version` if not explicitly passed in?

Our instructions for private apps skips the `Session` part and recommend setting `ShopifyAPI::Base.api_version` while the ones for public apps don't. Might be an improvement to just make those consistent and simplify them.

**Comment by tolgap** [comment]
@swalkinshaw 

You're right, I should be able to set `ShopifyAPI::Base.api_version` to the same value as `ShopifyApp.configuration.api_version`. That's what I'm assuming in my code anyway.

So I just appended this line to my `shopify_app.rb` initializer:
```ruby
ShopifyAPI::Base.api_version = ShopifyApp.configuration.api_version
```

and now I can define my queries as constants easily.
