### ISSUE TITLE
ShopifyAPI::ApiVersion::ApiVersionNotSetError

### ISSUE THREAD

**Issue by oliwoodsuk** [Shopify/shopify_api#682]
Hi,

I'm receiving this error: 
`ShopifyAPI::ApiVersion::ApiVersionNotSetError: You must set ShopifyAPI::Base.api_version before making a request` when running an action via a rails runner.
Which seems pretty self-explanatory, but I am setting the API version. I've even checked in the console and it returns:
`#<ShopifyAPI::ApiVersion:0x0000563cfee9bbc8 @handle="2020-01", @display_name="2020-01", @supported=false, @latest_supported=false, @verified=false>`

I've got `config.api_version = '2020-01'` In my shopify_app.rb as well as `ShopifyAPI::Base.api_version = '2020-01'`.
I've got the following in my shop model:
` def api_version
      ShopifyApp.configuration.api_version
  end`

...and then in my controller, I have the following before any API calls:
`             session = ShopifyAPI::Session.new(
                  domain: @shop.shopify_domain,
                  token: @shop.shopify_token,
                  api_version: '2020-01'
                )             
            ShopifyAPI::Base.activate_session(session)   `

I've tried downgrading my shopify app and api gem version, but I get the same error. The funny thing is, I didn't have this error yesterday morning and I can't see anything in my subsequent changes that would be related.

Any tips/hints would be much appreciated!

**Comment by oliwoodsuk** [comment]
However, if I call the controller method on page-load from within the app it works fine...
So, I only get the `ShopifyAPI::ApiVersion::ApiVersionNotSetError` when I use a runner or rake task (I need this to work as a cron job).

**Comment by oliwoodsuk** [comment]
My mistake, I forgot I had an if/else statement with two areas of code that needed a session initialising.

**Comment by ajsharp** [comment]
I've run into this same issue. This library should raise a more appropriate exception here -- something like `ShopSessionNotSetException`.

**Comment by tommasocaporuscio** [comment]
I have the same problem as you solved?
