### ISSUE TITLE
Searching ShopifyAPI::Product and pagination with shopify-kaminari

### ISSUE THREAD

**Issue by aldrienht** [Shopify/shopify_api#684]
I posted this in community.shopify.com and one shopify staff told me to post this as an issue.

Issue:
  When requesting WITH filter for **title** result doesn't include total_count.
  Thus pagination(used shopify-kaminari) doesn't worked, doesn't show in view.

Gem info:
- omniauth-shopify-oauth2 (1.2.0)
- shopify-kaminari (1.1.0)
- shopify_api (4.3.2)
- shopify_app (7.4.0)

Query:
  `parameters = {fields: 'id,title,url,handle', page: params[:page] || 1, limit: 5}`
  `parameters = parameters.merge(title: params[:title]) if params[:title].present?`
  `@products = ShopifyAPI::Product.find(:all, params: parameters)`

**Comment by tanema** [comment]
I have spoke to our pagination team and unfortunately both total count and total page count are not supported and will not be supported because of performance issues

**Comment by ShayneP** [comment]
Since the `page` param has been deprecated, gems based on `kaminari` are no longer compatible.

Paging should now be done with relative cursors, which are described [here](https://shopify.dev/tutorials/make-paginated-requests-to-rest-admin-api#make-a-paginated-request-and-iterate-through-the-pages)
