### ISSUE TITLE
GraphQL query works but mutation not works

### ISSUE THREAD

**Issue by yu-coder** [Shopify/shopify_api#690]
```
query = ShopifyAPI::GraphQL.client.parse <<~GRAPHQL
          mutation($fulfillment: FulfillmentV2Input!) {
            fulfillmentCreateV2(fulfillment: $fulfillment) {
              fulfillment {
                id
              }
              userErrors {
                field
                message
              }
            }
          }
        GRAPHQL

fulfillment_v2_input = {
          lineItemsByFulfillmentOrder: [
            {
              fulfillmentOrderId: "gid://shopify/Order/2104425589592",
              fulfillmentOrderLineItems: [
                {
                  id: "gid://shopify/LineItem/4567148053162",
                  quantity: 1
                }
              ]
            }
          ]
        }

result = ShopifyAPI::GraphQL.client.query(query, variables: { fulfillment: fulfillment_v2_input }).data
puts result
```

But the **result** is 
`{}`

**Comment by yu-coder** [comment]
I have noticed that there are errors in my query.

`
{"errors"=>[{"message"=>"Variable fulfillment of type FulfillmentV2Input! was provided invalid value", "locations"=>[{"line"=>1, "column"=>62}], "extensions"=>{"value"=>{"lineItemsByFulfillmentOrder"=>[{"fulfillmentOrderId"=>"gid://shopify/Order/2104425589592", "fulfillmentOrderLineItems"=>[{"id"=>"gid://shopify/LineItem/4567148053162", "quantity"=>1}]}], "trackingInfo"=>{"company"=>nil, "number"=>nil}}, "problems"=>[{"path"=>[], "explanation"=>"invalid id"}]}}]}`

It looks like there is an issue in `"id"=>"gid://shopify/LineItem/4567148053162"`
But I have checked LineItem Id so it is correct.

**Comment by tanema** [comment]
Do you have an example of what the input is that you are passing?

**Comment by yu-coder** [comment]
Hi @tanema I am using this input.
f```
ulfillment_v2_input = {
          lineItemsByFulfillmentOrder: [
            {
              fulfillmentOrderId: "gid://shopify/Order/2104425589592",
              fulfillmentOrderLineItems: [
                {
                  id: "gid://shopify/LineItem/4567148053162",
                  quantity: 1
                }
              ]
            }
          ]
        }
```

**Comment by tanema** [comment]
It seems like that gid should be `gid://shopify/FulfillmentOrder/2104425589592` and the other gid should be `gid://shopify/FulfillmentOrderLineItem/4567148053162`


See https://shopify.dev/tutorials/manage-fulfillments-with-fulfillment-and-fulfillmentorder-resources#create_fulfillment

**Comment by yu-coder** [comment]
Thank you @tanema 
It looks like that issue is gone.

But sorry I am having a new issue. (Not sure I have to open the new issue but I am writing here)
`FulfillmentCreateV2 access denied`

This is my App scopes.
`config.scope = "read_customers, read_products, write_products, read_orders, read_all_orders, write_orders, read_inventory, write_inventory, read_locations, read_fulfillments, write_fulfillments"`

Could you please help me fix this new issue?
Is there any other `scope` I have to add?
Thank you!

**Comment by yu-coder** [comment]
I have fixed by adding new scopes. Thank you!

**Comment by lthomasvl** [comment]
Hi @yu-coder 
Could you tell me which scope you added to fix this? I am facing the same error.
