### ISSUE TITLE
Readme file issues

### ISSUE THREAD

**Issue by RoohBear** [Shopify/shopify_api#699]
Step 3 in your readme.md file doesn't mention that you need to add
require 'shopify_api' 
as the first line.

Also, you say we have to set ShopifyAPI::Base.site to the base URL but the readme file implies that it doesn't need to be in quotes.  Should it be in quotes?

**Comment by ShayneP** [comment]
> Step 3 in your readme.md file doesn't mention that you need to add
require 'shopify_api'
as the first line.

This has never been a part of the instructions, it's assumed that people who are using the gem know that it needs to be added with `require` — but I can see how it might be confusing for people who are getting started with Ruby. Will add a note.

> Also, you say we have to set ShopifyAPI::Base.site to the base URL but the readme file implies that it doesn't need to be in quotes. Should it be in quotes?

I'm not sure that I see where the readme is implying that this doesn't need to be in quotes. The only place that the `ShopifyAPI::Base.site` is explicitly referenced is in step 2A, but the `shop_url` is set in the line above to a string.
