### ISSUE TITLE
Find Fulfillments undefined method `next_page?'

### ISSUE THREAD

**Issue by jpriollaud** [Shopify/shopify_api#703]
API_VERSION = '2020-01'

    shopify_api (9.0.2)
      activeresource (>= 4.1.0, < 6.0.0)
      graphql-client
      rack

`ShopifyAPI::Order.find(2060135891079).transactions.next_page?`
false

`ShopifyAPI::Blog.find(57420644487).articles.next_page?`
true

`ShopifyAPI::Order.find(2060135891079).fulfillments`
[#<ShopifyAPI::Fulfillment:0x0000557700d444b0 ........

`ShopifyAPI::Order.find(2060135891079).fulfillments.next_page?`
*** NoMethodError Exception: undefined method `next_page?' for #<Array:0x0000557702c13a30>

I noticed in the Shopify API docs Fulfillment is listed twice.
https://shopify.dev/docs/admin-api/rest/reference/shipping-and-fulfillment

Fulfillment
Fulfillment

https://shopify.dev/docs/admin-api/rest/reference/shipping-and-fulfillment/fulfillmentunstable
https://shopify.dev/docs/admin-api/rest/reference/shipping-and-fulfillment/fulfillment

It looks like 2020-01 should support cursor pagination in Fulfillments.  

I assume I'm doing something wrong or the docs need some kind of update.  Apologies in advance.

**Comment by tanema** [comment]
It just seems like we have not actually implemented on Order. You can find the fulfillments by using ShopifyApi::Fulfillment which will give you cursor pagination. I will contact someone about Order#fulfillments not working

**Comment by tanema** [comment]
Okay I asked and the reason for this is because `ShopifyApi::Fulfillment` is a legacy API and `ShopifyApi::FulfillmentV2` is the new API. So this was left un-implemented so that you will choose which API to use.
