### ISSUE TITLE
not doing anything with inventory_quantity and getting "inventory_quantity no longer supported"

### ISSUE THREAD

**Issue by colinbrogan** [Shopify/shopify_api#704]
I understand how to use InventoryLevel's API, and how to avoid the "inventory_quantity no longer supported" error. However, I have some code which is doing absolutely nothing with inventory, and started generating that error a few days ago.

Using  gem v9.0.1. In my configuration, I am interacting with the 2020-01 API version

```
begin
     logger.debug "PhotosController begin"
     p = ShopifyAPI::Product.find( inventory_report_row.product_id )
     logger.debug "Product found"
     f = File.read( params[:photos].path )
     logger.debug "File read"
     i = ShopifyAPI::Image.new(:product_id => p.id)
     logger.debug "Image ActiveResource object created"
     if (p.images.length + 1) == 4
          # Set to Store Light
          logger.debug "Image length now shows 4"
          p.tags = p.tags + ", Store_light_photos"
          logger.debug "Tags added"
          p.save
          logger.debug "Product saved"
       end
       i.attach_image(f) # <-- attach_image is a method, not an attribute
       logger.debug "Image attached"
       image_save_result = i.save
       logger.debug "image_save_result"
       logger.debug image_save_result
rescue => e
       logger.debug e.message
       logger.debug e.backtrace[0..9]
end
```

See the logged result of running that code:

```
PhotosController begin
Product found
File read
Image ActiveResource object created
Image length now shows 4
Tags added
Failed.Response code = 400.Response message = Bad Request (Write requests to inventory_quantity and inventory_quantity_adjustment are no longer supported. Please use the Inventory Levels API.).
```
The p.save line is generating that error. Is this gem doing something in the backend, trying to submit inventory_level's in it's save request?

I have no idea how to solve this problem. Is this a bug with the gem?

**Comment by tanema** [comment]
This all works off of active resource. This is the lifecycle of your code.
- `p = ShopifyAPI::Product.find( inventory_report_row.product_id )` loads all of the attributes of that product, including the inventory attributes.
- You make changes to the product attributes
- `p.save` sends all of the attributes loaded in the first step, back to shopify including the inventory fields.

This is the exact same issue as the other open issue that is being worked on. To work around this, you will still need to use the workaround proposed in the other issue before calling p.save.

**Comment by colinbrogan** [comment]
Thanks tanema,
I found that issue right after posting this one.
I am trying this as a workaround:

`p = ShopifyAPI::Product.find( inventory_report_row.product_id, params { :fields => "id, tags, images" } )`

Testing now, hopefully this will solve the problem
