### ISSUE TITLE
Structure rake tasks so they can make GraphQL API calls

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_api#709]
Using latest Shopify API shopify_api (9.0.2)

I created a rake task in library that in turn requires a module with GraphQL queries. 

The problem with this pattern is, calling the Shopify GraphQL client bombs as it has no notion of the API version or where to find the schema. So how do you properly initialize these without having to open a session first, and inlining the GraphQL inside a session?

    module MyModule
          GetCollectionByHandle = ShopifyAPI::GraphQL.client.parse <<-'GRAPHQL'

In this simple setup, the call to client() fails as soon as my rake task requires the file with the module. What kind of pattern are people using so that their rake tasks can make GraphQL calls without the initialization errors like:

     ShopifyAPI::GraphQL::InvalidClient: Client for API version 2020-01 does not exist because no schema file exists at `shopify_graphql_schemas/2020-01.json`.

or

     ShopifyAPI::ApiVersion::ApiVersionNotSetError: You must set ShopifyAPI::Base.api_version before making a request.

**Comment by tanema** [comment]
I understand that you want to parse the queries and store them as constants however the parsing needs a client and API version to initialize so it knows what it is parsing is valid against the versioned schema. I would recommend that you store your query in a string constant, and then memoize access to the parsed query .

```
def query
    @query ||= ShopifyAPI::GraphQL.client.parse(GetCollectionByHandle)
end
```

**Comment by resistorsoftware** [comment]
Ok Thanks! 

I appreciate the advice!

**Comment by resistorsoftware** [comment]
Just curious though, all I see here is more confusion. 

A string constant exhibits the problem... executing a client call before the API is ready:

    `SHOP_NAME_QUERY = ShopifyAPI::GraphQL.client.parse <<-'GRAPHQL'
  {
    shop {
      name
    }
  }
GRAPHQL`

So in reality, I don't get this suggestion at all...

**Comment by tanema** [comment]
```ruby
module MyModule
  class GraphQLIntegration
      GetCollectionByHandle = <<~GRAPHQL
        query{
         shop { 
           name
         }
       }
       GRAPHQL

       def self.call
         integration = new
         parsed_query =integration.query
       end

       def query
         @query ||= ShopifyAPI::GraphQL.client.parse(GetCollectionByHandle)
      end
  end
end
```

**Comment by resistorsoftware** [comment]
Leaving out the fact that query just gets a shop without any params... 

So my module has a class like GraphQLIntegration for each GraphQL call I want to make. So I just have calls like:

GraphQLIntegration.query(handle: 'fizzbuzz") whenever I need data, and since the incoming params differ, the query executes and returns me new data for each call.

**Comment by resistorsoftware** [comment]
So you're saying with that, I could do something like:

So in my class I would include MyModule and then call classes as needed? 

I have not used that pattern of self.call. What's an example of calling that with parameters? Seems neat.

**Comment by tanema** [comment]
If I were to make a large module with all my queries like this then I would do something like

```
module Queries
  class QueryWrap
    def initialize(query)
      @query_str
    end
    
    def query
       @query ||= ShopifyAPI::GraphQL.client.parse(@query_str)
    end
  end

  GetCollectionByHandle = QueryWrap(<<~GRAPHQL
    query{
     shop { 
       name
     }
   }
   GRAPHQL)

  GetShopName = QueryWrap(<<~GRAPHQL
    query{
     shop { 
       name
     }
   }
   GRAPHQL)
end

Queries::GetShopName.query
Queries::GetCollectionByHandle.query(handle: 'handle')

```

Re: `self.call` It is a common pattern that we use at Shopify. A lot of times you will have a service object/class that only has one entrypoint into so there is no sense in making another developer call `Klass.new().entrypoint()` it can just be shortend to `Klass.entrypoint()` It simplifies it's usage and it makes it easier to change.

**Comment by resistorsoftware** [comment]
Ok... now I get it.. I will have to practice this pattern with parameters too.

**Comment by resistorsoftware** [comment]
I am not understanding your query with data... I get it that QueryWrap takes that string of GraphQL code and makes it available for use, so the first part of a call to the ShopifyAPI::GraphQL::Client.query call gets something to use. I slightly altered your example so that the call was to QueryWrap.new() and also set the initializer of @query_str to be the actual query. 

Now when I have a query and I call ShopifyAPI::GraphQL::Client.query with the results of that and some actual data, the call fails with the provided data. So a quick example:

query = Queries::GetCollectionByHandle.query
ShopifyAPI::GraphQL::Client.query(query, handle: "coca-cola")

errors out saying handle is an unknown keyword? But that is the call signature of the GraphQL client as far as I can tell... what am I doing wrong with parameters.

**Comment by resistorsoftware** [comment]
Never mind... it does work fine.. I forgot that the client needs to see the keyword **variables:**

**Comment by resistorsoftware** [comment]
@tanema Tim! 👍👍💪💪🔥🔥🍺🍺

I love how this code all comes together. Managed to write a 500 line module that strictly builds up and tears down products based on an Excel file of really crap data. It requires a single module of queries, and that is exactly what I was looking for. 

Super appreciate you taking the time to chime in with your wisdom. I cannot stop marveling at how cool this whole thing is, taking full advantage of the Shopify Media handling facilities using GraphQL. 

About the only thing I am left scratching my head on is replaced the command line system process calls to curl with proper Ruby. No amount of fiddling with that has successfully beat curl, so for now, that stays.

**Comment by SANDHUER** [comment]
can someone help me my boss has given me a task to migrate from rest to graphQL api in ruby.also i am new to ruby and dont where you guys are writing this code and this query runs..it works fine for me when i run graphQL queryies in shopify graphQL app.but it doesnt work for me here....Please please guide me through this I will be very helpfull to you guys..
