### ISSUE TITLE
fulfillmentCreate gql endpoint not working as expected

### ISSUE THREAD

**Issue by TheVedhaGuy** [Shopify/shopify_api#719]
I noticed that using the fulfillmentCreate GraphQL endpoint (the deprecated one) from the Shopify API was creating and fulfilling orders in core when used from SFN. 

From what I understand, this should just create the fulfillment in core and return the fulfillment object back to me so that I can do w/e with that object. 

Here is an order where I saw that happen on my test store https://vedhastore1.myshopify.com/admin/orders/2273031880775. Note that we were using the REST API before, this was an attempt to switch over to GraphQL. Can provide the request/response if needed

@MalazAlamir  was helping me debug this and found that we are missing a param in the mutation. 
We’re setting `create_pending_fulfillment` to true, but its actually `create_as_open` that we want to set as true

**Comment by tanema** [comment]
Is this an API issue then? Should the API be fixed in core then?

**Comment by TheVedhaGuy** [comment]
Yes sorry, ill open this up in core
