### ISSUE TITLE
Basic auth can't be used together with ShopifyAPI::Session.temp

### ISSUE THREAD

**Issue by aglundahl** [Shopify/shopify_api#744]
If you've set up basic auth for a private app with `ShopifyAPI::Base.site = ...`, you can't use `ShopifyAPI::Session.temp`, since `user` and `password` aren't cleared and restored on `ShopifyAPI::Base` in `ShopifyAPI::Session.with_session`.

I'm not sure what other implications it would have, but one solution might be to add `user` and `password` to `ShopifyAPI::Session`, and making sure they're cleared and restored accordingly.

Here's a monkey patch for anyone else running into this:

```ruby
module ShopifyAPI
  class Session
    class << self
      def with_session(session, &_block)
        original_session = extract_current_session
        original_user = ShopifyAPI::Base.user
        original_password = ShopifyAPI::Base.password

        begin
          ShopifyAPI::Base.clear_session
          ShopifyAPI::Base.activate_session(session)
          yield
        ensure
          ShopifyAPI::Base.activate_session(original_session)
          ShopifyAPI::Base.user = original_user
          ShopifyAPI::Base.password = original_password
        end
      end
    end
  end
end
```

**Comment by jamiemtdwyer** [comment]
FYI, the password for a private app can be treated as an access token.

So, rather than setting `Base.user` and `Base.password` to accomplish private authentication, you can use:

```ruby
ShopifyAPI::Session.temp(domain: example.myshopify.com, token: YOUR_PRIVATE_APP_PASSWORD, api_version: "2020-04") do
  do_some_private_app_stuff
end
```

This might help you until this issue is addressed by the maintainers.

**Comment by aglundahl** [comment]
Didn't know that, @jamiemtdwyer. Thanks!
