### ISSUE TITLE
Ruby GraphQL Mutation Returning Error

### ISSUE THREAD

**Issue by mrbme** [Shopify/shopify_api#749]
I'm trying to run a productUpdate mutation, but i'm getting the following error:

`TypeError: expected definition to be a GraphQL::Client::OperationDefinition but was GraphQL::Language::Nodes::Document`

Here's my code:

```
 product_id = the_graph_id
   product_description = "some description" 
 PRODUCT_UPDATE = client.parse <<-'GRAPHQL'
    mutation ProductUpdate($input: ProductInput!) {
      productUpdate(input: $input) {
        product {
          id
          bodyHtml
        }
        userErrors {
          field
          message
        }
      }
    }
    GRAPHQL
    variables = {id: product_id, bodyHtml: product_description }
    response = client.query(PRODUCT_UPDATE, variables: variables )
```
Any help is appreciated!

**Comment by tanema** [comment]
It seems like this may be an issue with named mutations https://github.com/github/graphql-client/issues/171

**Comment by awd** [comment]
Can confirm this bug as @tanema linked above - instead of `mutation ProductUpdate(...)` it would be `mutation(...)`.

Tested locally and that removed the error.

**Comment by mrbme** [comment]
Such an easy fix! 😂 

Thanks!
