### ISSUE TITLE
How to get a paginated collection object of Customers?

### ISSUE THREAD

**Issue by num46664** [Shopify/shopify_api#752]
The following code is based on the pagination example in the readme, the main difference being that this is attempting to find customers rather than products.

In the `list_next` function i get:  ``NoMethodError (undefined method `next_page?' for #<Array:0x00007fb956aafef8>):``

`bundle info` gives `shopify_api (9.1.0)`, `shopify_app (13.2.0)`, `rails (6.0.3.1)`

in my `config/initializers/shopify_app.rb`, `config.api_version = "2020-04"`

```ruby
class Api::CustomersController < AuthenticatedController
    def list
        @customers = ShopifyAPI::Customer.find(:all, params: { limit: 10 })
        session[:customers] = @customers
        render json: @customers 
    end
    def list_next
        @customers = session[:customers]
        if @customers.next_page?
            @customers = @customers.fetch_next_page
        else
            @customers = []
        end
        render json: @customers
    end
end
```

**Comment by kartikluke** [comment]
Store `customers.next_page_info` in session and pass that to the `.find` API.

**Comment by paulomarg** [comment]
Closing this as it doesn't look to be an actual issue with the API code, and the `next_page_info` suggestion would be the right call, as per the example in README:

```
  first_batch_products = ShopifyAPI::Product.find(:all, params: { limit: 50 })
  second_batch_products = ShopifyAPI::Product.find(:all, params: { limit: 50, page_info: first_batch_products.next_page_info })
```
