### ISSUE TITLE
ShopifyAPI::GraphQL::InvalidClient Error

### ISSUE THREAD

**Issue by gregarican** [Shopify/shopify_api#764]
Trying a small test Ruby script I am consistently hitting this error regardless of which API version I specify. And specifying an API version is required. I'll paste my small test script belong, along with the specific error. Any feedback or insight would be appreciated!

 `require 'shopify_api'

API_KEY = "{my_api_key}"
PASSWORD = "{my_api_password}"
SHOP_NAME = "{my_shop_name}"
API_VERSION = "2020-07"
shop_url = "https://#{API_KEY}:#{PASSWORD}@#{SHOP_NAME}.myshopify.com"
ShopifyAPI::Base.site = shop_url
ShopifyAPI::Base.api_version = API_VERSION # find the latest stable api_version here: https://shopify.dev/concepts/about-apis/versioning

shopify_session = ShopifyAPI::Session.new(domain: "#{SHOP_NAME}.myshopify.com", token: PASSWORD, api_version: API_VERSION, extra: nil)
ShopifyAPI::Base.activate_session(shopify_session)

client = ShopifyAPI::GraphQL.client
SHOP_NAME_QUERY = client.parse <<-'GRAPHQL'
  {
    shop {
      name
    }
  }
GRAPHQL

result = client.query(SHOP_NAME_QUERY)
puts result.data.shop.name`

And here is the error, regardless of which API version I define.

** from ./test-gql.rb:13:in `<main>'
/home/vm-admin/.rvm/gems/ruby-2.5.7/gems/shopify_api-9.2.0/lib/shopify_api/graphql.rb:27:in `client': Client for API version 2020-07 does not exist because no schema file exists at `shopify_graphql_schemas/2020-07.json`. (ShopifyAPI::GraphQL::InvalidClient)**

**Comment by andyw8** [comment]
Hi @gregarican 

I think this because you need to first dump the schema as described here:

https://github.com/Shopify/shopify_api/blob/master/docs/graphql.md#dump-the-schema

Hope that helps.

**Comment by gregarican** [comment]
Thanks for the quick reply! I installed this as a gem, and when I run the rake command I get an error that the Rakefile is not found. Do I need to run this command from where the gem installed shopify_api to?

**Comment by gregarican** [comment]
Here is the specific error. I tried pulling this via git clone, went to the project directory and got the same outcome as going to the root of the project's gem directory. Here is the specific error returned by the latter below.

Seems rather tedious to get started?

**Don't know how to build task 'shopify_api:graphql:dump' (See the list of available tasks with `rake --tasks`)
/home/vm-admin/.rvm/gems/ruby-2.5.7/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/home/vm-admin/.rvm/gems/ruby-2.5.7/bin/ruby_executable_hooks:24:in `eval'
/home/vm-admin/.rvm/gems/ruby-2.5.7/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)**

**Comment by andyw8** [comment]
Hi @gregarican 

There shouldn't be any need to clone the repo, but looking into this some more I found that the Rake task is only available if the gem is used with a Rails app:

https://github.com/Shopify/shopify_api/blob/master/lib/shopify_api/graphql/railtie.rb

So if you generate a barebones Rails app you should be able to generate it via that.

I realize that's not ideal, and I've created #765 to look at improving this.

**Comment by gregarican** [comment]
Thanks for the suggestion! Actually I just pulled down the shopify_app project and ran that command just fine. Now where do I place the JSON file that got dumped out? I tried placing it in the shopify_api gem's /db/shopify_graphql_schemas directory I created but it's still not being found. Sorry for the hassle!

**Comment by andyw8** [comment]
@gregarican Happy to hear you've got it working!
