### ISSUE TITLE
Making REST calls for the Page

### ISSUE THREAD

**Issue by jonathanahern** [Shopify/shopify_api#769]
I would like to make REST calls to add and update Pages since it seems Graphql doesn't support it yet, but I can't find any documentation that it's possible with a REST call using the shopify_api gem either. Is this the case?

Shopify outlines the different requests here...https://shopify.dev/docs/admin-api/rest/reference/online-store/page#count-2020-07

**Comment by andyw8** [comment]
Hi @jonathanahern 

Pages are supported, there's an ActiveResource model for it here:
https://github.com/Shopify/shopify_api/blob/master/lib/shopify_api/resources/page.rb

Hope that helps you.

**Comment by jonathanahern** [comment]
Thanks! I don't know why I couldn't get it to work earlier.
