### ISSUE TITLE
Variant#serializable_hash in 9.2.0

### ISSUE THREAD

**Issue by axlekb** [Shopify/shopify_api#775]
Hi folks,

Outside of a `ShopifyApp` session block, I was trying to call `Variant#as_json`, and kept getting the very unhelpful error:
`TypeError (compared with non class/module)` with no traceback.

I was able to track it down to this recent addition by @marschattha in `lib/shopify_api/resources/variant.rb`:

```ruby
def allow_inventory_params?
  Base.api_version < ApiVersion.find_version('2019-10')
end
```

If you're using `ShopifyApp` and do something like:
```ruby
product = shop.with_shopify_session { ShopifyAPI::Product.find(XXX) } 
```

the `Base.api_version` the api version is only set within the block, and is otherwise `ShopifyAPI::ApiVersion::NullVersion` causing the `TypeError` on comparison.

It feels weird to not be able to serialize an object outside of a session block.  Not sure how/if you'd like to solve this issue, but thought I might share my research here in case others experience the same problem.

**Comment by paulomarg** [comment]
Thanks for reporting this in, we will look into it!

**Comment by andyw8** [comment]
For reference, here's the PR where that was added: https://github.com/Shopify/shopify_api/pull/731

**Comment by shaneewert** [comment]
Upvote - been having the same issues for a few weeks
