### ISSUE TITLE
Debugging ability

### ISSUE THREAD

**Issue by TomFrost** [Shopify/shopify_api#786]
Thanks for the great library!

I'm trying to debug a request. During the day today, one of my API calls spontaneously stopped working. Searching customers by email address suddenly returns no results, but when I make the request using the same domain and API token using curl or postman, it's quite successful. Is there any way to see the exact request being constructed by this library, and the exact response with headers?

My code to trigger the call is pretty standard:

```ruby
params = { email: "existing@email.com" }
customers = ShopifyAPI::Customer.search params
puts "Customers: #{customers.to_json}" # Always "Customers: []" as of noon EDT today
```

Shopify support is asking for the request and response and it seems that this library prevents me from getting at that data. I hope I'm wrong!

**Comment by TomFrost** [comment]
For anyone else suddenly having this problem, `ShopifyAPI::Customer.where(email: email)` seems to be a workaround that returns an equivalent response. I'd still love to know how to see the details of the API call being constructed, though. I'm really concerned that since this one stopped working completely spontaneously, the other API calls my app is making could fail with the same lack of fanfare at any moment.

**Comment by andyw8** [comment]
Hi @TomFrost 

The REST behaviour of shopify_api is built on top of ActiveResouce, so you may be able to enable logging through that:

https://github.com/rails/activeresource#label-Logging

**Comment by andyw8** [comment]
I'll close for now, you can re-open if you're still having problems with this.
