### ISSUE TITLE
Cannot update order email address in orders/create or orders/updated webhook

### ISSUE THREAD

**Issue by skillmatic-co** [Shopify/shopify_api#810]
Hello, When I do this:

```
shopify_order = ShopifyAPI::Order.find(webhook[:id])
shopify_order.email = "foo@bar.com"
shopify_order.save
```

I'm not getting any errors, yet the email on the order is not saved.

When I do this:

```
shopify_order = ShopifyAPI::Order.find(webhook[:id])
shopify_order.tags = "testing"
shopify_order.email = "foo@bar.com"
shopify_order.save
```

I'm also not getting any errors, yet the "testing" tag _is_ saved and the email is still not saved.

It seems like just the email is not saved. I have also successfully saved other order variables such as note attributes and shipping address. Any idea what could be causing just the order email to not be saved?

Thanks.

**Comment by andyw8** [comment]
@skillmatic-co is this a local pickup or local delivery order by chance? Or just a regular shipped order?

**Comment by skillmatic-co** [comment]
> @skillmatic-co is this a local pickup or local delivery order by chance? Or just a regular shipped order?

It's a regular shipped order.

**Comment by andyw8** [comment]
@skillmatic-co I can reproduce this, but I was able to workaround it by also setting the customer email:

`shopify_order.customer.email = 'foo@bar.com'`

It seems the customer email gets copied to the order email as part of the update.

I'll report this to our API team. I'm not yet sure if it's a bug, but the behaviour should be documented.

**Comment by skillmatic-co** [comment]
@andyw8 got it. Let me know what you find, in my case I would like to change the email on the order but leave the customer email unchanged.

You can see in the update order examples here it appears that you can update the order's email.

https://shopify.dev/docs/admin-api/rest/reference/orders/order#update-2020-10

**Comment by andyw8** [comment]
@skillmatic-co Yes, on further investigation this appears to specific to the `shopify_api` library.

When the `order` is serialized, it also serializes the `customer` object. The update order behaviour in the API is implemented such that if a customer email is provided, it overwrites the order email when the order is updated.

If you want to update only the order email, but not the customer email, you can set the customer email to `nil`. This should leave the customer email as its original value and only update the order email.

**Comment by skillmatic-co** [comment]
@andyw8 got it, thanks! That did the trick. Closing.

**Comment by andyw8** [comment]
Good to hear. I've opened #811 to look at improving this.

**Comment by skillmatic-co** [comment]
@andyw8 a related question that you may know: is the new order confirmation email sent before or after the orders/create webhook is hit?

**Comment by andyw8** [comment]
@skillmatic-co I would expect both are asynchronous so it may not be possible to guarantee the order.
