### ISSUE TITLE
STATUS attribute is missing.

### ISSUE THREAD

**Issue by nagendrahd** [Shopify/shopify_api#824]
When finding a product the **status** attribute is missing, I am using API version _2019-10_ 

But I receive the **status** attribute in the web-hook callback payload. 

Any help would be highly appreciated.

**Comment by paulomarg** [comment]
Hi @nagendrahd, have you tried running your code with a more recent version of the API? Version `2019-10` is no longer supported and may behave differently than webhooks.

As per [the versioning documentation](https://shopify.dev/concepts/about-apis/versioning#webhooks), webhooks will default to the first supported version if they are using an unsupported version.

Could you please check whether you still have issues while using a supported API version?

**Comment by specialcookiecheck** [comment]
Hi team, adding another store with this problem. This is with the 2021-01 version of our API.

This is the call that doesn't return a status field: https://publicbikesusa.myshopify.com/admin/api/2021-01/products/1647255388223.json

However, when querying the status field specifically, it does return a result, so definitely some sort of bug there: https://publicbikesusa.myshopify.com/admin/api/2021-01/products/1647255388223.json?fields=status

It seems to be a wider problem, as I found this post on our forums: https://community.shopify.com/c/Shopify-APIs-SDKs/How-can-get-product-status-at-the-2020-10-REST-API/td-p/908976

[Internal](https://app.shopify.com/services/internal/shops/2113994815)
[Zendesk ticket](https://shopify.zendesk.com/agent/tickets/22784366)

**Comment by joseph-maddox** [comment]
I'm also observing this issue with the latest API (`2021-04`). For example, my call: `https://transformer-supply-co.myshopify.com/admin/api/2021-04/products.json` does not return `status` attributes for any of the products.

**Comment by paulomarg** [comment]
Yes, the API seems to be failing to return that field. I will report that to the appropriate team. Thank you!

**Comment by paulomarg** [comment]
The underlying issue was fixed, so the API should start returning the `status` field soon. Please allow some time for the fix to be deployed, but let us know if you still experience this issue!
