### ISSUE TITLE
301 Error on Draft Order Creation

### ISSUE THREAD

**Issue by iyerushalmi** [Shopify/shopify_api#828]
Hello, I have a script that has been working fine for a couple years which allows me to create draft orders. However, as of this week, I suddenly began getting a 301 error from Shopify when trying to save the draft order:

`ActiveResource::Redirection (Failed.  Response code = 301.  Response message = Moved Permanently. => /admin/auth/login)
`
Any idea why this could be?

UPDATE: The issue was the result of a shopify outage and has since resolved itself.

**Comment by zackwalkingstick** [comment]
I am getting a 301 when running a collections query as of this morning as well...It was working at 10pm last night so it seems like something changed in the past 12 hours

**Comment by andyw8** [comment]
@iyerushalmi @zackwalkingstick are these private apps? If so, it may be related to:
https://community.shopify.com/c/Shopify-APIs-SDKs/For-security-reasons-requests-using-HTTP-Basic-Authentication/m-p/1009119

**Comment by iyerushalmi** [comment]
Thanks for the replies - the issue was indeed the result of a shopify incident that has since resolved itself.
