### ISSUE TITLE
Deleting an order note attribute

### ISSUE THREAD

**Issue by skillmatic-co** [Shopify/shopify_api#848]
How do you delete a note attribute?

I'm trying:

```
shopify_order.note_attributes.delete(ShopifyAPI::NoteAttribute.new(
  name: 'some_attribute_to_delete',
  value: "true"
))
```

But this is deleting all note attributes.

**Comment by mkevinosullivan** [comment]
I think it's because `note_attributes` is plural, so it's deleting them all.

I think it needs to be something like `shopify_order.note_attribute.where(name: 'some_attribute_to_delete').delete`

**Comment by skillmatic-co** [comment]
> I think it's because `note_attributes` is plural, so it's deleting them all.
> 
> I think it needs to be something like `shopify_order.note_attribute.where(name: 'some_attribute_to_delete').delete`

Hmm, this doesn't seem to be working. I get `NoMethodError (undefined method `note_attribute' for #<ShopifyAPI::Order:0x000056187a8b0770>)` and if I try `shopify_order.note_attributes.where(name: 'some_attribute_to_delete').delete` I get `NoMethodError (undefined method `where' for #<Array:0x000056187a2d42c0>)`

**Comment by skillmatic-co** [comment]
I have figured it out, this worked for me:

```
shopify_order.note_attributes.delete_if {|note| note.name == 'some_attribute_to_delete'}
```
