### ISSUE TITLE
Fetch page lost prefix attribute

### ISSUE THREAD

**Issue by iiewad** [Shopify/shopify_api#849]
# Issue summary

Fetch page lost prefix_options attributes

## Expected behavior

I will get next/previous page data with prefix_options attributes

## Actual behavior

What actually happens?

```
irb(main):032:0> discount_codes = shop.with_shop_session {ShopifyAPI::DiscountCode.all(params: {price_rule_id: 919109107896, limit: 2})}

=> [#<ShopifyAPI::DiscountCode:0x00007ff659bbe3e0 @attributes={"id"=>11100111208632, "code"=>"DOB-fc93035b", "usage_count"=>0, "created_at"=>"2021-03-17T01:22:10-07:00", "updated_at"=>"2021-03-17T01:22:10-07:00"}, @prefix_options={:price_rule_id=>919109107896}, @persisted=true>, #<ShopifyAPI::DiscountCode:0x00007ff659bc7558 @attributes={"id"=>11100111175864, "code"=>"DOB-3fb3b6be", "usage_count"=>0, "created_at"=>"2021-03-17T01:22:10-07:00", "updated_at"=>"2021-03-17T01:22:10-07:00"}, @prefix_options={:price_rule_id=>919109107896}, @persisted=true>]

irb(main):035:0> shop.with_shop_session {discount_codes.fetch_next_page}

=> [#<ShopifyAPI::DiscountCode:0x00007ff6572eb058 @attributes={"id"=>11100111143096, "code"=>"DOB-2d3e1f60", "usage_count"=>0, "created_at"=>"2021-03-17T01:22:10-07:00", "updated_at"=>"2021-03-17T01:22:10-07:00"}, @prefix_options={}, @persisted=true>, #<ShopifyAPI::DiscountCode:0x00007ff6572eac20 @attributes={"id"=>11100111110328, "code"=>"DOB-977640e7", "usage_count"=>0, "created_at"=>"2021-03-17T01:22:10-07:00", "updated_at"=>"2021-03-17T01:22:10-07:00"}, @prefix_options={}, @persisted=true>]
```

## Steps to reproduce the problem

1. get resource normal with prefix params
2. fetch page

## Logs
-

## Specifications

- `shopify_api` version: shopify_api (9.2.0)
- `activeresource` version: activeresource (5.1.1)
- Shopify API version used (example: `2020-07`):  2020-07

**Comment by mllemango** [comment]
Hey @iiewad, thanks for bringing this up. Pagination doesn't trigger the `prefix_options` setting (which in this case will be `price_rule_id`). Does the issue stem from the fact that you're trying to access `price_rule_id`?

**Comment by iiewad** [comment]
@mllemango Yes,  I need get the price_rule_id when I fetch the page. Maybe I can get the price_rule_id with other way, but I think the prefix_options setting is necessary!
I'm sorry about my english~

**Comment by mllemango** [comment]
I would suggest getting `price_rule_id` from the DiscountCode class, you can use `discount_code.price_rule_id` instead. 
Below is a snippet of code I used
```
discounts = shopify.DiscountCode.find(price_rule_id=PRICE_RULE_ID, limit=2)
    for discount in discounts:
        print(discount.price_rule_id)
```

**Comment by iiewad** [comment]
@mllemango Ok, Thanks for your answer!
