### ISSUE TITLE
GET fulfillment_orders/{fulfillment_order_id}/fulfillments Does Not Work

### ISSUE THREAD

**Issue by hrdwdmrbl** [Shopify/shopify_api#855]
# Issue summary

Attempting to use the API `GET /admin/api/2021-01/fulfillment_orders/{fulfillment_order_id}/fulfillments.json` does not work.

## Expected behavior

It should return an array of Fulfillments

## Actual behavior

API returns

```
{
    "errors": "Fulfillment order does not exist."
}
```

## Steps to reproduce the problem

1. Get a fulfillment_order.id
2. Use it to try to fetch Fulfillments associated with it.
3. Get error

### Using the API

```
> shop.with_shopify_session { fulfillment_order.fulfillments }

ActiveResource::ResourceNotFound: Failed.  Response code = 404.  Response message = Not Found (Fulfillment order does not exist.).
from /Users/marcbeaupre/.rvm/gems/ruby-2.7.2/gems/activeresource-5.1.1/lib/active_resource/connection.rb:147:in `handle_response'
```

### Using Postman

https://user-images.githubusercontent.com/554881/114761361-5bd9f800-9d2e-11eb-86b3-eddefc3f434c.mp4

## Specifications

- `shopify_api` version: 9.4.1
- `activeresource` version: 5.1.1
- Shopify API version used (example: `2020-07`): 2021-01

## Associated Question

If a FulfillmentOrder `has_many` Fulfillments, then why does Fulfillment not have a fulfillment_order_id attribute?

**Comment by andyw8** [comment]
@hrdwdmrbl please allow an hour for this to fully deploy and confirm the fix is working for you, thanks.

**Comment by hrdwdmrbl** [comment]
@andyw8 There is life behind the iron curtain of Shopify! It's great to see it! Can you grant 3 wishes?
1. Can I request an API to fetch FulfillmentOrders for multiple Order IDs? `/fulfillment_orders.json?order_ids=111,222`
2. Why don't you expose the `fulfillment_order_id` property of FulfillmentOrders?
3. Have a nice day!
