### ISSUE TITLE
How do I use since_id on the ShopifyAPI::Checkout when it doesn't return the actual ID?

### ISSUE THREAD

**Issue by marcamillion** [Shopify/shopify_api#862]
# Issue summary

Even though the [REST API for AbandonedCheckout documentation](https://shopify.dev/docs/admin-api/rest/reference/orders/abandoned-checkouts#index-2021-04) indicates that I should be able to GET a list of abandoned checkouts since some ID by the attribute `since_id`, whenever I try to get the `id` of a checkout object, it returns the `token`. So I am not sure how to use `since_id` for Checkouts given the current implementation.

## Expected behavior

I should receive an integer ID on an Abandoned Checkout object. 

## Actual behavior

Instead I get an alphanumeric string from `token`.

```
[141] pry(main)> Checkout.last
=> #<ShopifyAPI::Checkout:0x00007fa9664e1fd0
 @attributes=
  {"id"=>20899858677942,
   "token"=>"7133c7aeb0ff3b4b506c2a66e4190ee3",
[140] pry(main)> Checkout.last.id
=> "7133c7aeb0ff3b4b506c2a66e4190ee3"
```

When I try to pass the token as the `since_id` parameter, it returns an error:

```
[139] pry(main)> Checkout.find(:all, params: { since_id: "7133c7aeb0ff3b4b506c2a66e4190ee3"})
E, [2021-05-17T11:06:36.920571 #82915] ERROR -- : GET https://mystore.myshopify.com:443/admin/api/2021-04/checkouts.json?since_id=7133c7aeb0ff3b4b506c2a66e4190ee3
E, [2021-05-17T11:06:36.920662 #82915] ERROR -- : --> 400 Bad Request 57 (520.0ms)
ActiveResource::BadRequest: Failed.  Response code = 400.  Response message = Bad Request (since_id; expected String to be a Integer).
from /.rvm/gems/ruby-3.0.1@myapp/gems/activeresource-5.1.1/lib/active_resource/connection.rb:141:in `handle_response'
```

## Steps to reproduce the problem

Simply 

1. Simply try to execute a REST API call for the resource `ShopifyAPI::Checkout.find(:all, params: { since_id: checkout.token })` 
2. Or try to get the `id` of a `checkout` object like `ShopifyAPI::Checkout.last.id` (you will get the token).

## Specifications

- `shopify_api` version: 1.9.1
- `activeresource` version: 5.1.1
- Shopify API version used: `2021-04`

**Comment by mllemango** [comment]
Hey @marcamillion, the Checkout object uses `token` as its primary key which is why you're seeing token returned on `ShopifyAPI::Checkout.last.id`. Use the resource `ShopifyAPI::AbandonedCheckout` and that should return the id you're looking for. 

This will also fix your bad request error since the API expects the checkout ID, not token.

**Comment by marcamillion** [comment]
Ahh perfect @mllemango. That works. Thanks!
