### ISSUE TITLE
ShopifyAPI::DraftOrder where customer_id

### ISSUE THREAD

**Issue by dsounded** [Shopify/shopify_api#867]
# Issue summary

So currently there is no way to query draft orders for specific customer I tried e.g.
`where(customer_id: id) `

and

`where(customer: { id: id })`

## Expected behavior

It's possible to perform such a query

## Actual behavior

It ignores this condition and returns full list

## Steps to reproduce the problem

1. Create draft order for specific customer
1. Query draft orders with customer id
1. See result

## Specifications

- `shopify_api` version: 9.3.0
- `activeresource` version: 6.1.3
- Shopify API version used (example: `2020-07`): 2020-10

**Comment by dsounded** [comment]
So currently there is only `status` available for filtering which helps to reduce the scope but still, currently we need to while loop by 250 each time and then manually do `Array#select` which is definitely not a production ready solution

**Comment by mllemango** [comment]
Unfortunately this is not something that the REST API supports. An alternative would be to look into what GraphQL allows.
