### ISSUE TITLE
Rails 7 support?

### ISSUE THREAD

**Issue by cgs** [Shopify/shopify_api#890]
Any timeline for supporting Rails 7? Thanks!

**Comment by schappim** [comment]
Yup, I'm getting: 
```

web    | DEPRECATION WARNING: `active_support/core_ext/uri` is deprecated and will be removed in Rails 7.1. (called from <main> at /Users/admin/code/book-import/config/application.rb:7)
web    | /Users/admin/.rvm/gems/ruby-3.0.3/gems/activeresource-4.0.0.beta1/lib/active_resource/validations.rb:103:in `block in <module:Validations>': undefined method `alias_method_chain' for ActiveResource::Base:Class (NoMethodError)
web    | Did you mean?  alias_method
```

**Comment by m0n9oose** [comment]
ActiveResource is waiting for Rails 7 support https://github.com/rails/activeresource/pull/367

**Comment by anark** [comment]
`activeresource 6.0.0` has been released. To support rails 7 we would need https://github.com/Shopify/shopify_api/pull/892 merged and released.

**Comment by anark** [comment]
Looks like https://github.com/Shopify/shopify_api/pull/891 has been merged.  To resolve this we would just need a version bump and a new release and it should be good.

To avoid deprecation notices you will need to update activeresource in your project to v6.0.0 or later
