### ISSUE TITLE
Downloading Schema Results in GraphQL Error Objects Returned From API

### ISSUE THREAD

**Issue by jasonbuehler** [Shopify/shopify_api#900]
# Issue summary

When I try to download the schema the api is returning a number of errors. 

## Expected behavior

When I try to download the schema the api should return the schema.

## Actual behavior

When I download the schema for 2022-01 I get a graphql error document back. 
<code>
{"errors"=>
  [{"message"=>"Field 'description' doesn't exist on type '__Schema'",
    "locations"=>[{"line"=>3, "column"=>5}],
    "path"=>["query IntrospectionQuery", "__schema", "description"],
    "extensions"=>{"code"=>"undefinedField", "typeName"=>"__Schema", "fieldName"=>"description"}},
   {"message"=>"Field 'isRepeatable' doesn't exist on type '__Directive'",
    "locations"=>[{"line"=>20, "column"=>7}],
    "path"=>["query IntrospectionQuery", "__schema", "directives", "isRepeatable"],
    "extensions"=>{"code"=>"undefinedField", "typeName"=>"__Directive", "fieldName"=>"isRepeatable"}},
   {"message"=>"Field 'specifiedByUrl' doesn't exist on type '__Type'", "locations"=>[{"line"=>32, "column"=>3}], "path"=>["fragment FullType", "specifiedByUrl"], "extensions"=>{"code"=>"undefinedField", "typeName"=>"__Type", "fieldName"=>"specifiedByUrl"}}]}
</code>

## Steps to reproduce the problem

1. Download the schema as detailed in the README (rake shopify_api:graphql:dump SHOP_DOMAIN="[FILTERED]" ACCESS_TOKEN="[FILTERED]" API_VERSION=2022-01)
2. View the resulting downloaded schema file

## Specifications

- `shopify_api` version: 9.5.1
- `activeresource` version: 6.0.0
- Shopify API version used (example: `2020-07`): '2022-01'

**Comment by sneakingJ** [comment]
I created this issue just two days ago: https://github.com/Shopify/shopify_api/issues/898

But glad to see I'm not the only one with the problem. Using and older shopify_api gem version worked though.

**Comment by andyw8** [comment]
Hi @jasonbuehler, thanks for reporting this. It seems to be same issue as in #898, so I'll close this and you can follow along there.
