### ISSUE TITLE
Shops no longer able to select carrier service

### ISSUE THREAD

**Issue by Trimakas** [Shopify/shopify_api#904]
# Issue summary

Write a short description of the issue here ↓

## Expected behavior

What do you think should happen?
We have installed a Shopify Carrier Service on many stores. For some reason stores no longer can see this carrier service, nor can they select it. ALL stores, n

## Actual behavior
[Here is a video of what shop owners are seeing
](https://screencast-o-matic.com/watch/c3ef2kVFnfQ\)

What actually happens?
Nothing, the shop owner sees nothing for ALL our stores, not just the example below.

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

This is the carrier service installed on: [fitfido-co.myshopify.com](https://fitfido-co.myshopify.com/)

`{"id"=>57227968546, "name"=>"FBA Shipping by ByteStand", "active"=>true, "service_discovery"=>true, "carrier_service_type"=>"api", "admin_graphql_api_id"=>"gid://shopify/DeliveryCarrierService/57227968546", "format"=>"json", "callback_url"=>"https://shipping-production.herokuapp.com/receive/rates"}`

They are unable to select it.

## Steps to reproduce the problem

1. Create a CarrierService

## Specifications

- `shopify_api` version: 18.1.1
- `activeresource` version: 6.0.0
- Shopify API version used (example: `2020-07`):  2021-10

**Comment by andyw8** [comment]
@Trimakas I believe there was an issue relating to another system in Shopify which has just been resolved, is it working for you now?

**Comment by Trimakas** [comment]
It is.. @andyw8 working now.. thanks
