### ISSUE TITLE
Cannot eager load in Rails 6 from uninitialized constant ShopifyAPI::AdminVersions

### ISSUE THREAD

**Issue by ericotto** [Shopify/shopify_api#913]
# Issue summary

Application fails to start with eager loading in Rails 6.

## Expected behavior

The library loads successfully when the application starts.

## Actual behavior

The library fails to load when rails 6 eager loading if utilized:
 ```
`const_get’: uninitialized constant ShopifyAPI::AdminVersions (NameError)
````

## Steps to reproduce the problem

1. Start Rails 6 application with `eager_load` set to  `true`

## Logs
If applicable, enable the logs as described in the README, and paste the relevant portion here.

```
/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `const_get’: uninitialized constant ShopifyAPI::AdminVersions (NameError)
from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `cget’
from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `cget’
from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:237:in `block (2 levels) in eager_load’
from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:237:in `block (2 levels) in eager_load’
```

## Specifications

- `shopify_api` version: Main Branch

**Comment by scart88** [comment]
+1 
I'm getting the same error

**Comment by scart88** [comment]
@paulomarg I pushed a fix for this issue. 
Could you please review it when you got some time?

Thank you very much!
