### ISSUE TITLE
v10 should not depend on OJ

### ISSUE THREAD

**Issue by jeffblake** [Shopify/shopify_api#917]
OJ should be an optional dependency for people who want to use the stlib JSON.

**Comment by andyw8** [comment]
@jeffblake is there a particular problem this is causing?

**Comment by andyw8** [comment]
We chose OJ as it has better performance than the standard library JSON, and so provides a benefit to majority of users. I'm going to close this for now, but feel free to re-open if you encounter a specific problem.
