### ISSUE TITLE
Is there any any reason why cannot make request for v10 ?

### ISSUE THREAD

**Issue by assoumemba** [Shopify/shopify_api#922]
# Issue summary

After upgrade gem to v10, got multiple issues to access data.  I implemented the new model to use "CustomSessionStorage" but not called. Some example use "session = ShopifyAPI::Auth::SessionLoader.load_current_session(headers, cookies, is_online)" It seams SessionLoader is not implemented. Got error uninitialized constant ShopifyAPI::Auth::SessionLoader.
what should go into: headers, cookies, is_online ?

## Specifications

- `shopify_api` version: v10
- Shopify API version used (example: `2020-07`):

**Comment by scart88** [comment]
There is no Class defining ShopifyAPI::Auth::SessionLoader in the lib folder. 
It seems to be available only on the docs.
