### ISSUE TITLE
Is the type of `ShopifyAPI::Variant#weight` Integer?

### ISSUE THREAD

**Issue by koshigoe** [Shopify/shopify_api#931]
# Issue summary

The `ShopifyAPI::Variant` defines `weight` as `Integer`.

https://github.com/Shopify/shopify_api/blob/1d76f06f623812ff06c57e1523da275f3e889583/lib/shopify_api/rest/resources/2022_01/variant.rb#L39

But, in the API reference specified `weight` as `Float`.

- https://shopify.dev/api/admin-rest/2022-01/resources/product-variant#get-products-product-id-variants
- https://shopify.dev/api/admin-graphql/2022-01/objects/ProductVariant#field-productvariant-weight

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/18269/162870147-bc8b9654-eca9-4e59-ac55-33dd4d2f058a.png">

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/18269/162869993-092f22bd-5b96-4593-b006-0bdfa8a8335b.png">

## Expected behavior

The type of `ShopifyAPI::Variant#weight` should be `Float`?

## Actual behavior

The type of `ShopifyAPI::Variant#weight` is `Integer`.
Is this correct?

## Specifications

- `shopify_api` version: 10.0.2
- Shopify API version used `2022-01`

**Comment by paulomarg** [comment]
Great catch, I'm pretty sure it should indeed be a `Float`. We'll look into it!
