### ISSUE TITLE
Thread safety of pagination in v10?

### ISSUE THREAD

**Issue by stevenou** [Shopify/shopify_api#953]
I am looking at upgrading from v9 to v10 of the gem and it looks like the old `PaginatedCollection` no longer exists. 

I was looking at this example from https://github.com/Shopify/shopify_api/blob/main/docs/usage/rest.md:
```
session = ShopifyAPI::Utils::SessionUtils.load_current_session(headers, cookies, is_online)

products = ShopifyAPI::Product.all(session: session, limit: 10)

loop do
  some_function(products)
  break unless ShopifyAPI::Product.next_page?
  products = ShopifyAPI::Product.all(session: session, limit: 10, page_info: ShopifyAPI::Product.next_page_info)
end
```

Am I mistaken to think that this implementation of pagination (using an instance variable on the class), is not thread safe?

**Comment by ilyabyar** [comment]
Have stumbled across the same question, but quickly digging into lib's source lead me to 
https://github.com/Shopify/shopify_api/blob/main/lib/shopify_api/rest/resources/2022_04/order.rb#L8-L9

And it is based on another lib, which has next class
https://github.com/ruby-concurrency/concurrent-ruby/blob/master/lib/concurrent-ruby/concurrent/atomic/thread_local_var.rb

So, my guess will be that it is thead-safe
