### ISSUE TITLE
Instance of `ShopifyAPI::Webhook` `#save` returns `T::Private::Types::Void::VOID`

### ISSUE THREAD

**Issue by vfonic** [Shopify/shopify_api#974]
# Issue summary

The new Sorbet types added to the gem are interfering with the gem's functionality.

I just added a webhook to my app like this:

```rb
> wh = ShopifyAPI::Webhook.new(session:)
> wh.topic = 'orders/create'
> wh.address = 'https://example.com/webhooks/orders_create'
> wh.save
# => T::Private::Types::Void::VOID
```

## Expected behavior

I believe that `.save` (without bang `!`) should return `true`/`false` based on whether the method executed successfully or not.

## Actual behavior

I get some "random" artifact from Sorbet type checking.

## Specifications

- `shopify_api` version: 10.1.0
- Shopify API version used (example: `2020-07`): 2022-04

**Comment by psaravanan** [comment]
Getting same error. Any solution?

I am trying to create Recurring Application charge and getting "T::Private::Types::Void::VOID:Module" error.

```
recurring_application_charge = ShopifyAPI::RecurringApplicationCharge.new(session: test_session)
recurring_application_charge.name = "Super Duper Plan"
recurring_application_charge.price = 10.0
recurring_application_charge.return_url = "http://super-duper.shopifyapps.com"
recurring_application_charge.trial_days = 5
recurring_application_charge.save!
```

**Comment by Alagaesia93** [comment]
It looks like .save! triggers an internal update on the object itself, so if you @psaravanan check recurring_application_charge, it should have the id

```
recurring_application_charge = ShopifyAPI::RecurringApplicationCharge.new(session: test_session)
recurring_application_charge.name = "Super Duper Plan"
recurring_application_charge.price = 10.0
recurring_application_charge.return_url = "http://super-duper.shopifyapps.com"
recurring_application_charge.trial_days = 5
recurring_application_charge.id => returns nil
recurring_application_charge.save!
recurring_application_charge.id => returns something not nil
```

**Comment by psaravanan** [comment]
Yes, you are right. Thanks for the response.
